import { BadgeDollarSign, CircleDollarSign, CreditCard, WalletCards } from "lucide-react";
import { Card, DataTable, ExportCsvButton, MetricCard, SectionHeader, type DataTableColumn } from "../../shared/components";
import { gamingStore, orderReconciliation, type GamingOrder } from "../data/gamingStore";
import { gamingLkr } from "../shared/format";
import { GamingStatus } from "../shared/GamingStatus";
import { useGamingStore } from "../shared/useGamingStore";

export function FinancePage(){
 const orders=useGamingStore(gamingStore.getOrders); const customers=useGamingStore(gamingStore.getCustomers); const products=useGamingStore(gamingStore.getProducts); const paid=orders.filter((o)=>o.customerPaid&&o.status!=="refunded"); const gross=paid.reduce((s,o)=>s+o.sellingPrice,0); const supplier=paid.reduce((s,o)=>s+(o.supplierCharged?o.supplierCostLkr:0),0); const fees=paid.reduce((s,o)=>s+o.gatewayFee,0); const profit=paid.reduce((s,o)=>s+o.profit,0);
 const cols:DataTableColumn<GamingOrder>[]=[{key:"order",header:"Order",render:(o)=><div className="entity-cell"><strong>{o.number}</strong><small>{customers.find((c)=>c.id===o.customerId)?.name} · {products.find((p)=>p.id===o.productId)?.name}</small></div>},{key:"revenue",header:"Customer paid",render:(o)=><strong>{o.customerPaid?gamingLkr(o.sellingPrice):"-"}</strong>},{key:"supplier",header:"Supplier cost",render:(o)=><strong>{o.supplierCharged?gamingLkr(o.supplierCostLkr):"-"}</strong>},{key:"fees",header:"Gateway fee",render:(o)=><span className="muted-cell">{o.customerPaid?gamingLkr(o.gatewayFee):"-"}</span>},{key:"profit",header:"Profit",render:(o)=><strong>{gamingLkr(o.profit)}</strong>},{key:"recon",header:"Reconciliation",render:(o)=><GamingStatus value={orderReconciliation(o)}/>}];
 return <div className="page"><SectionHeader eyebrow="Gaming Store" title="Finance & Reconciliation" description="See customer money, supplier charges, payment fees and profit together so mismatches are immediately visible." action={<ExportCsvButton filename="next-f-gaming-reconciliation" rows={orders} columns={[{header:"Order",value:(row)=>row.number},{header:"Customer",value:(row)=>customers.find((c)=>c.id===row.customerId)?.email??row.customerId},{header:"Product",value:(row)=>products.find((p)=>p.id===row.productId)?.name??row.productId},{header:"Status",value:(row)=>row.status},{header:"Customer paid",value:(row)=>row.customerPaid},{header:"Selling LKR",value:(row)=>row.sellingPrice},{header:"Supplier charged",value:(row)=>row.supplierCharged},{header:"Supplier cost LKR",value:(row)=>row.supplierCostLkr},{header:"Gateway fee LKR",value:(row)=>row.gatewayFee},{header:"Profit LKR",value:(row)=>row.profit},{header:"Reconciliation",value:(row)=>orderReconciliation(row)}]}/>} /><div className="metric-grid"><MetricCard label="Gross sales" value={gamingLkr(gross)} detail="Paid, non-refunded orders" icon={CircleDollarSign}/><MetricCard label="Supplier cost" value={gamingLkr(supplier)} detail="Charged supplier orders" icon={WalletCards}/><MetricCard label="Gateway fees" value={gamingLkr(fees)} detail="Configured estimate" icon={CreditCard}/><MetricCard label="Gross profit" value={gamingLkr(profit)} detail="Before business overhead" icon={BadgeDollarSign}/></div><Card><div className="operation-section__head"><div><span>Reconciliation</span><h3>Order economics</h3></div><BadgeDollarSign size={18}/></div><DataTable rows={orders} columns={cols} getKey={(o)=>o.id}/></Card></div>;
}
