import { useMemo, useState } from "react";
import { FileArchive, Plus, Rocket } from "lucide-react";
import { Button, Card, ConfirmDialog, DataTable, FormField, MetricCard, Modal, PageToolbar, SectionHeader, SelectInput, TextInput, type DataTableColumn } from "../../shared/components";
import { useToast } from "../../shared/feedback/ToastProvider";
import { validators } from "../../shared/validation";
import { softwareStore, type ReleaseChannel, type SoftwareRelease } from "../data/softwareStore";
import { shortDate } from "../shared/format";
import { SoftwareStatus } from "../shared/SoftwareStatus";
import { useSoftwareStore } from "../shared/useSoftwareStore";

type ReleaseAction = { release:SoftwareRelease; action:"publish"|"deprecate" } | null;

export function ReleasesPage(){
  const releases=useSoftwareStore(softwareStore.getReleases), products=useSoftwareStore(softwareStore.getProducts); const {notify}=useToast(); const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [productId,setProductId]=useState(products[0]?.id??""); const [version,setVersion]=useState(""); const [channel,setChannel]=useState<ReleaseChannel>("stable"); const [attempted,setAttempted]=useState(false); const [releaseAction,setReleaseAction]=useState<ReleaseAction>(null);
  const rows=useMemo(()=>releases.filter((r)=>`${products.find((p)=>p.id===r.productId)?.name} ${r.version} ${r.channel}`.toLowerCase().includes(query.toLowerCase())),[releases,products,query]); const versionError=attempted?validators.semver(version):"";
  const applyReleaseAction=()=>{if(!releaseAction)return;const {release,action}=releaseAction;if(action==="publish"){softwareStore.publishRelease(release.id);notify({title:"Release published",description:`v${release.version} is now available on the ${release.channel.replace(/_/g," ")} channel.`,tone:"success"});}else{softwareStore.deprecateRelease(release.id);notify({title:"Release deprecated",description:`v${release.version} remains recorded but is no longer a normal published release.`,tone:"info"});}};
  const cols:DataTableColumn<SoftwareRelease>[]=[{key:"release",header:"Release",render:(r)=><div className="entity-cell"><strong>{products.find((p)=>p.id===r.productId)?.name} v{r.version}</strong><small>{r.fileName} · {r.fileSizeMb} MB</small></div>},{key:"channel",header:"Channel",render:(r)=><SoftwareStatus value={r.channel}/>},{key:"status",header:"Status",render:(r)=><SoftwareStatus value={r.status}/>},{key:"compat",header:"Compatibility",render:(r)=><div className="entity-cell"><strong>{r.compatibility}</strong><small>{r.minRuntime}</small></div>},{key:"released",header:"Released",render:(r)=><span>{shortDate(r.releasedAt)}</span>},{key:"action",header:"",render:(r)=>r.status==="draft"?<Button variant="primary" onClick={()=>setReleaseAction({release:r,action:"publish"})}>Publish</Button>:r.status==="published"?<Button className="button--danger" onClick={()=>setReleaseAction({release:r,action:"deprecate"})}>Deprecate</Button>:null}];
  const create=()=>{setAttempted(true);if(!productId||!version||versionError)return;const row=softwareStore.createRelease({productId,version:version.trim(),channel,status:"draft",minRuntime:"PHP 8.1",compatibility:"WordPress 6.5+",fileName:`${products.find((p)=>p.id===productId)?.slug}-${version.trim()}.zip`,fileSizeMb:0,checksum:"pending",changelog:"Draft release",rollbackVersion:undefined});notify({title:"Draft release created",description:`v${row.version} is ready for release preparation.`,tone:"success"});setOpen(false);setVersion("");setAttempted(false);};
  return <div className="page"><SectionHeader eyebrow="NEXT F Software" title="Releases" description="Release versions, channels, compatibility and checksums." action={<Button variant="primary" onClick={()=>{setAttempted(false);setOpen(true);}}><Plus size={15}/> Release</Button>}/><div className="compact-metrics"><MetricCard label="Published" value={String(releases.filter((r)=>r.status==="published").length)} icon={Rocket}/><MetricCard label="Stable" value={String(releases.filter((r)=>r.channel==="stable"&&r.status==="published").length)} icon={FileArchive}/></div><Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search releases…"/><DataTable rows={rows} columns={cols} getKey={(r)=>r.id}/></Card><Modal open={open} onClose={()=>setOpen(false)} title="Create release" description="Create a draft software release record."><div className="form-grid form-grid--two"><FormField label="Product" required><SelectInput value={productId} onChange={(e)=>setProductId(e.target.value)}>{products.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</SelectInput></FormField><FormField label="Version" required error={versionError}><TextInput aria-invalid={!!versionError} placeholder="1.5.0" value={version} onChange={(e)=>setVersion(e.target.value)}/></FormField><FormField label="Channel"><SelectInput value={channel} onChange={(e)=>setChannel(e.target.value as ReleaseChannel)}><option value="development">Development</option><option value="beta">Beta</option><option value="release_candidate">Release candidate</option><option value="stable">Stable</option></SelectInput></FormField></div><div className="modal-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="primary" onClick={create}>Create draft</Button></div></Modal><ConfirmDialog open={!!releaseAction} onClose={()=>setReleaseAction(null)} title={releaseAction?.action==="publish"?"Publish software release?":"Deprecate software release?"} description={releaseAction?`v${releaseAction.release.version} on ${releaseAction.release.channel.replace(/_/g," ")} will be ${releaseAction.action==="publish"?"made available to eligible update/download flows":"removed from normal published release selection"}.`:""} confirmLabel={releaseAction?.action==="publish"?"Publish release":"Deprecate release"} danger={releaseAction?.action==="deprecate"} onConfirm={applyReleaseAction}/></div>;
}
