import { BarChart3, BriefcaseBusiness, CircleDollarSign, RefreshCw, UsersRound } from "lucide-react";
import { Card, ExportCsvButton, MetricCard, SectionHeader } from "../../shared/components";
import { digitalStore } from "../data/digitalStore";
import { formatLkr } from "../shared/format";
import { useDigitalStore } from "../shared/useDigitalStore";

export function ReportsPage(){
 const leads=useDigitalStore(digitalStore.getLeads); const opps=useDigitalStore(digitalStore.getOpportunities); const proposals=useDigitalStore(digitalStore.getProposals); const clients=useDigitalStore(digitalStore.getClients); const invoices=useDigitalStore(digitalStore.getInvoices); const projects=useDigitalStore(digitalStore.getProjects); const subs=useDigitalStore(digitalStore.getSubscriptions); const tickets=useDigitalStore(digitalStore.getTickets);
 const collected=invoices.reduce((s,i)=>s+i.paidAmount,0); const outstanding=invoices.reduce((s,i)=>s+(i.amount-i.paidAmount),0); const pipeline=opps.filter((o)=>!["won","lost"].includes(o.stage)).reduce((s,o)=>s+o.value,0); const recurring=subs.filter((s)=>s.status==="active").reduce((a,s)=>a+s.amount,0); const conversion=leads.length?Math.round((clients.length/leads.length)*100):0; const accepted=proposals.filter((p)=>p.status==="accepted").length; const proposalRate=proposals.length?Math.round((accepted/proposals.length)*100):0;
 return <div className="page"><SectionHeader eyebrow="NEXT F Digital" title="Reports" description="Sales, revenue, delivery and recurring operations." action={<ExportCsvButton filename="next-f-digital-management-report" rows={[{collected,outstanding,pipeline,recurring,leads:leads.length,opportunities:opps.length,proposals:proposals.length,clients:clients.length,projects:projects.length,openSupport:tickets.filter((t)=>!["resolved","closed"].includes(t.status)).length}]} columns={[{header:"Collected revenue LKR",value:(row)=>row.collected},{header:"Outstanding LKR",value:(row)=>row.outstanding},{header:"Open pipeline LKR",value:(row)=>row.pipeline},{header:"Recurring base LKR",value:(row)=>row.recurring},{header:"Leads",value:(row)=>row.leads},{header:"Opportunities",value:(row)=>row.opportunities},{header:"Proposals",value:(row)=>row.proposals},{header:"Clients",value:(row)=>row.clients},{header:"Projects",value:(row)=>row.projects},{header:"Open support",value:(row)=>row.openSupport}]}/>} />
 <div className="metric-grid"><MetricCard label="Collected revenue" value={formatLkr(collected)} icon={CircleDollarSign}/><MetricCard label="Open pipeline" value={formatLkr(pipeline)} icon={BarChart3}/><MetricCard label="Recurring base" value={formatLkr(recurring)} icon={RefreshCw}/><MetricCard label="Active clients" value={String(clients.filter((c)=>c.status==="active").length)} icon={UsersRound}/></div>
 <div className="report-grid"><Card><div className="operation-section__head"><div><span>Sales</span><h3>Funnel health</h3></div><BarChart3 size={18}/></div><div className="report-bars"><ReportRow label="Leads" value={leads.length} max={Math.max(leads.length,1)}/><ReportRow label="Opportunities" value={opps.length} max={Math.max(leads.length,1)}/><ReportRow label="Proposals" value={proposals.length} max={Math.max(leads.length,1)}/><ReportRow label="Clients" value={clients.length} max={Math.max(leads.length,1)}/></div><p className="report-note">Proposal acceptance: <strong>{proposalRate}%</strong></p></Card>
 <Card><div className="operation-section__head"><div><span>Delivery</span><h3>Operations health</h3></div><BriefcaseBusiness size={18}/></div><div className="report-kpis"><div><span>Active projects</span><strong>{projects.filter((p)=>p.status==="active").length}</strong></div><div><span>Awaiting client</span><strong>{projects.filter((p)=>p.status==="awaiting_client").length}</strong></div><div><span>Outstanding</span><strong>{formatLkr(outstanding)}</strong></div><div><span>Open support</span><strong>{tickets.filter((t)=>!["resolved","closed"].includes(t.status)).length}</strong></div></div></Card></div></div>;
}
function ReportRow({label,value,max}:{label:string;value:number;max:number}){return <div className="report-bar"><div><span>{label}</span><strong>{value}</strong></div><div className="progress-track"><i style={{width:`${Math.min(100,(value/max)*100)}%`}}/></div></div>}
