import { useMemo, useState } from "react";
import { Boxes, ListChecks, Plus, Puzzle, Sparkles } from "lucide-react";
import { Button, Card, DataTable, FormField, MetricCard, Modal, PageToolbar, SectionHeader, SelectInput, TextInput, Toggle, type DataTableColumn } from "../../shared/components";
import { digitalStore, type ServicePackage } from "../data/digitalStore";
import { useDigitalStore } from "../shared/useDigitalStore";
import { formatLkr } from "../shared/format";
import { validators } from "../../shared/validation";
import { useToast } from "../../shared/feedback/ToastProvider";
import { digitalAdminStore, type ProjectTemplate, type ServiceAddon } from "../operations/digitalAdminStore";
import { useDigitalAdmin } from "../operations/useDigitalAdmin";

export function ServicesPage() {
  const services = useDigitalStore(digitalStore.getServices); const addons=useDigitalAdmin(digitalAdminStore.getAddons); const templates=useDigitalAdmin(digitalAdminStore.getTemplates); const { notify } = useToast();
  const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [attempted,setAttempted]=useState(false); const [name,setName]=useState(""); const [family,setFamily]=useState("Website Design & Development"); const [price,setPrice]=useState("100000"); const [billingModel,setBillingModel]=useState<ServicePackage["billingModel"]>("one_time"); const [duration,setDuration]=useState("4 weeks"); const [description,setDescription]=useState("");
  const [addonOpen,setAddonOpen]=useState(false); const [addonService,setAddonService]=useState(services[0]?.id??""); const [addonName,setAddonName]=useState(""); const [addonPrice,setAddonPrice]=useState("5000"); const [addonBilling,setAddonBilling]=useState<ServiceAddon["billing"]>("one_time");
  const [templateOpen,setTemplateOpen]=useState(false); const [templateName,setTemplateName]=useState(""); const [templateService,setTemplateService]=useState(services[0]?.id??""); const [templateStages,setTemplateStages]=useState("Discovery\nDelivery\nClient Approval");
  const rows=useMemo(()=>services.filter((service)=>`${service.name} ${service.family}`.toLowerCase().includes(query.toLowerCase())),[services,query]); const recurring=services.filter((service)=>["monthly","annual","retainer"].includes(service.billingModel)).length;
  const nameError=attempted?validators.required(name,"Service name")||(services.some((service)=>service.name.toLowerCase()===name.trim().toLowerCase())?"A service with this name already exists.":""):""; const priceError=attempted?validators.positive(price,"Base price"):""; const durationError=attempted?validators.required(duration,"Delivery / cadence"):"";
  const columns:DataTableColumn<ServicePackage>[]=[{key:"service",header:"Service",render:(row)=><div className="entity-cell"><strong>{row.name}</strong><small>{row.family}</small></div>},{key:"billing",header:"Billing",render:(row)=><span className="muted-cell">{row.billingModel.replaceAll("_"," ")}</span>},{key:"price",header:"Base price",render:(row)=><strong>{formatLkr(row.basePrice)}</strong>},{key:"duration",header:"Delivery",render:(row)=><span className="muted-cell">{row.duration}</span>},{key:"template",header:"Default stages",render:(row)=><span className="muted-cell">{row.template.length}</span>}];
  const addonColumns:DataTableColumn<ServiceAddon>[]=[{key:"addon",header:"Add-on",render:(r)=><div className="entity-cell"><strong>{r.name}</strong><small>{services.find((s)=>s.id===r.serviceId)?.name??"Service"}</small></div>},{key:"price",header:"Price",render:(r)=><strong>{formatLkr(r.price)}</strong>},{key:"billing",header:"Billing",render:(r)=><span>{r.billing.replace("_"," ")}</span>},{key:"active",header:"Active",render:(r)=><Toggle checked={r.active} onChange={(v)=>digitalAdminStore.updateAddon(r.id,{active:v})}/>}];
  const templateColumns:DataTableColumn<ProjectTemplate>[]=[{key:"template",header:"Template",render:(r)=><div className="entity-cell"><strong>{r.name}</strong><small>{services.find((s)=>s.id===r.serviceId)?.name??"General"}</small></div>},{key:"stages",header:"Stages",render:(r)=><span className="muted-cell">{r.stages.join(" → ")}</span>},{key:"active",header:"Active",render:(r)=><Toggle checked={r.active} onChange={(v)=>digitalAdminStore.updateTemplate(r.id,{active:v})}/>}];
  function submit(){setAttempted(true);if(nameError||priceError||durationError||!name.trim()||!duration.trim()||Number(price)<=0)return;const service=digitalStore.addService({name:name.trim(),family,basePrice:Number(price),billingModel,duration:duration.trim(),description:description.trim()||"Custom NEXT F service package."});notify({title:"Service created",description:`${service.name} is now available to sales and project workflows.`,tone:"success"});setOpen(false);setAttempted(false);setName("");setDescription("");}
  function createAddon(){const e=validators.required(addonName,"Add-on name")||validators.positive(addonPrice,"Price");if(e||!addonService)return notify({title:"Check add-on",description:e||"Select a service.",tone:"danger"});digitalAdminStore.addAddon({serviceId:addonService,name:addonName.trim(),price:Number(addonPrice),billing:addonBilling,active:true});notify({title:"Add-on created",tone:"success"});setAddonOpen(false);setAddonName("");}
  function createTemplate(){const stages=templateStages.split("\n").map((s)=>s.trim()).filter(Boolean);const e=validators.required(templateName,"Template name");if(e||stages.length<2)return notify({title:"Check template",description:e||"Add at least two delivery stages.",tone:"danger"});digitalAdminStore.addTemplate({name:templateName.trim(),serviceId:templateService||undefined,stages});notify({title:"Project template created",tone:"success"});setTemplateOpen(false);setTemplateName("");}
  return <div className="page services-page"><SectionHeader eyebrow="NEXT F Digital" title="Services" description="Commercial packages, optional add-ons and reusable delivery templates that power the service lifecycle."/><div className="compact-metrics"><MetricCard label="Active services" value={String(services.length)} detail="Sellable service packages" icon={Boxes}/><MetricCard label="Recurring" value={String(recurring)} detail="Monthly, annual or retainer" icon={Sparkles}/><MetricCard label="Add-ons" value={String(addons.filter((a)=>a.active).length)} detail="Optional commercial extensions" icon={Puzzle}/><MetricCard label="Project templates" value={String(templates.filter((t)=>t.active).length)} detail="Reusable delivery workflows" icon={ListChecks}/></div>
  <Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search services…"><Button variant="primary" onClick={()=>{setAttempted(false);setOpen(true)}}><Plus size={15}/>Add service</Button></PageToolbar><DataTable rows={rows} columns={columns} getKey={(row)=>row.id}/></Card>
  <Card className="operation-section"><div className="operation-section__head"><div><span>Commercial extensions</span><h3>Service add-ons</h3></div><Button onClick={()=>setAddonOpen(true)}><Plus size={14}/>Add add-on</Button></div><DataTable rows={addons} columns={addonColumns} getKey={(r)=>r.id} empty="No add-ons configured."/></Card>
  <Card className="operation-section"><div className="operation-section__head"><div><span>Delivery configuration</span><h3>Project templates</h3></div><Button onClick={()=>setTemplateOpen(true)}><Plus size={14}/>Add template</Button></div><DataTable rows={templates} columns={templateColumns} getKey={(r)=>r.id} empty="No project templates configured."/></Card>
  <Modal open={open} title="Create service package" description="Add a real service definition that can be used throughout the Digital workflow." onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="primary" onClick={submit}>Create service</Button></>}><div className="form-grid form-grid--two"><FormField label="Service name" required error={nameError}><TextInput aria-invalid={!!nameError} value={name} onChange={(e)=>setName(e.target.value)} placeholder="Business Website"/></FormField><FormField label="Family"><SelectInput value={family} onChange={(e)=>setFamily(e.target.value)}>{["Website Design & Development","Digital Marketing","SEO","Website Maintenance","Content Services","Analytics","Social Media Marketing","Custom Digital Solutions"].map((item)=><option key={item}>{item}</option>)}</SelectInput></FormField><FormField label="Base price (LKR)" required error={priceError}><TextInput aria-invalid={!!priceError} type="number" min="1" value={price} onChange={(e)=>setPrice(e.target.value)}/></FormField><FormField label="Billing model"><SelectInput value={billingModel} onChange={(e)=>setBillingModel(e.target.value as ServicePackage["billingModel"])}><option value="one_time">One-time</option><option value="monthly">Monthly</option><option value="annual">Annual</option><option value="retainer">Retainer</option><option value="custom">Custom</option></SelectInput></FormField><FormField label="Delivery / cadence" required error={durationError}><TextInput aria-invalid={!!durationError} value={duration} onChange={(e)=>setDuration(e.target.value)}/></FormField><FormField label="Description"><TextInput value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="What this package delivers"/></FormField></div></Modal>
  <Modal open={addonOpen} title="Create service add-on" onClose={()=>setAddonOpen(false)} footer={<><Button onClick={()=>setAddonOpen(false)}>Cancel</Button><Button variant="primary" onClick={createAddon}>Create add-on</Button></>}><div className="form-grid form-grid--two"><FormField label="Service"><SelectInput value={addonService} onChange={(e)=>setAddonService(e.target.value)}>{services.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</SelectInput></FormField><FormField label="Add-on name" required><TextInput value={addonName} onChange={(e)=>setAddonName(e.target.value)}/></FormField><FormField label="Price (LKR)" required><TextInput type="number" min={1} value={addonPrice} onChange={(e)=>setAddonPrice(e.target.value)}/></FormField><FormField label="Billing"><SelectInput value={addonBilling} onChange={(e)=>setAddonBilling(e.target.value as ServiceAddon["billing"])}><option value="one_time">One-time</option><option value="monthly">Monthly</option></SelectInput></FormField></div></Modal>
  <Modal open={templateOpen} title="Create project template" description="Enter one delivery stage per line." onClose={()=>setTemplateOpen(false)} footer={<><Button onClick={()=>setTemplateOpen(false)}>Cancel</Button><Button variant="primary" onClick={createTemplate}>Create template</Button></>}><div className="form-grid"><FormField label="Template name" required><TextInput value={templateName} onChange={(e)=>setTemplateName(e.target.value)}/></FormField><FormField label="Linked service"><SelectInput value={templateService} onChange={(e)=>setTemplateService(e.target.value)}><option value="">General template</option>{services.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</SelectInput></FormField><FormField label="Delivery stages" required><textarea className="text-input text-area" rows={7} value={templateStages} onChange={(e)=>setTemplateStages(e.target.value)}/></FormField></div></Modal></div>;
}
