import { useMemo, useState } from "react";
import { CircleDollarSign, ShoppingBag, UsersRound } from "lucide-react";
import { Card, DataTable, MetricCard, PageToolbar, SectionHeader, type DataTableColumn } from "../../shared/components";
import { gamingStore, type GamingCustomer } from "../data/gamingStore";
import { gamingDate, gamingLkr } from "../shared/format";
import { GamingStatus } from "../shared/GamingStatus";
import { useGamingStore } from "../shared/useGamingStore";

export function CustomersPage(){
 const customers=useGamingStore(gamingStore.getCustomers); const orders=useGamingStore(gamingStore.getOrders); const products=useGamingStore(gamingStore.getProducts); const [query,setQuery]=useState(""); const [selectedId,setSelectedId]=useState(customers[0]?.id??""); const selected=customers.find((c)=>c.id===selectedId); const rows=useMemo(()=>customers.filter((c)=>`${c.name} ${c.email} ${c.phone}`.toLowerCase().includes(query.toLowerCase())),[customers,query]); const customerOrders=orders.filter((o)=>o.customerId===selectedId);
 const cols:DataTableColumn<GamingCustomer>[]=[{key:"customer",header:"Customer",render:(c)=><button className="entity-button" onClick={()=>setSelectedId(c.id)}><strong>{c.name}</strong><small>{c.email}</small></button>},{key:"orders",header:"Orders",render:(c)=><strong>{c.orders}</strong>},{key:"value",header:"Lifetime value",render:(c)=><strong>{gamingLkr(c.lifetimeValue)}</strong>},{key:"last",header:"Last order",render:(c)=><span className="muted-cell">{gamingDate(c.lastOrderAt)}</span>}];
 return <div className="page"><SectionHeader eyebrow="Gaming Store" title="Customers" description="Compact customer history for reseller operations without turning the Gaming Store into a heavy CRM."/><div className="compact-metrics"><MetricCard label="Customers" value={String(customers.length)} detail="Local customer records" icon={UsersRound}/><MetricCard label="Customer orders" value={String(orders.length)} detail="Across all customers" icon={ShoppingBag}/><MetricCard label="Lifetime sales" value={gamingLkr(customers.reduce((s,c)=>s+c.lifetimeValue,0))} detail="Recorded paid value" icon={CircleDollarSign}/></div><div className="client-layout"><Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search customers…"/><DataTable rows={rows} columns={cols} getKey={(c)=>c.id}/></Card><Card className="client-360-card"><div className="client-360-header"><div><span>Customer 360</span><h3>{selected?.name??"Select customer"}</h3><p>{selected?.email}</p></div></div>{selected&&<><div className="client-summary-grid"><div><span>Orders</span><strong>{selected.orders}</strong></div><div><span>Lifetime value</span><strong>{gamingLkr(selected.lifetimeValue)}</strong></div><div><span>Since</span><strong>{gamingDate(selected.createdAt)}</strong></div></div><div className="client-360-section"><strong>Order history</strong>{customerOrders.length?customerOrders.map((o)=><div className="mini-record" key={o.id}><span><strong>{o.number}</strong><small>{products.find((p)=>p.id===o.productId)?.name}</small></span><span><GamingStatus value={o.status}/><small>{gamingLkr(o.sellingPrice)}</small></span></div>):<p className="empty-copy">No orders yet.</p>}</div></>}</Card></div></div>;
}
