import { useState } from "react";
import { Clock, CloudCog, Trash2 } from "lucide-react";
import { Badge, Button, Card, ConfirmDialog, FormField, MetricCard, SectionHeader, TextInput } from "../../shared/components";
import { platformOperationsStore } from "../services/platformOperationsStore";
import { usePlatformOperations } from "../shared/usePlatformOperations";
import { useToast } from "../../shared/feedback/ToastProvider";
import { readRuntimeTruth } from "../../services/production";

const runtime=readRuntimeTruth();

export function CleanupPage() {
  const stored = usePlatformOperations(platformOperationsStore.getRetention);
  const runs = usePlatformOperations(platformOperationsStore.getCleanupRuns);
  const [policy, setPolicy] = useState(stored);
  const [confirm, setConfirm] = useState(false);
  const { notify } = useToast();
  const describe = (r: {removedAudit:number;removedLogs:number;removedNotifications:number;removedBackups:number}) => `${r.removedAudit} audit · ${r.removedLogs} logs · ${r.removedNotifications} notifications · ${r.removedBackups} snapshots`;

  if(runtime.mode==="production-api") return <div className="page cleanup-page"><SectionHeader eyebrow="Platform" title="Cleanup & Retention" description="Production retention and cleanup are server-side operational controls executed by the production Worker schedule. Browser cleanup mutation is disabled."/><div className="compact-metrics"><MetricCard label="Execution" value="Server" detail="Production Worker cron" icon={CloudCog}/><MetricCard label="Browser cleanup" value="Disabled" detail="No client-side production deletion" icon={Trash2}/><MetricCard label="Evidence" value="Audit" detail="Acceptance + Worker audit trail" icon={Clock}/></div><Card className="architecture-callout"><div className="operation-section__head"><div><span>Production policy</span><h3>Server-controlled retention</h3></div><Badge tone="success">Protected</Badge></div><p>The production Worker performs retention and cleanup using the configured server-side schedule. This UI does not expose a browser button that could delete production operational history. Retention covers audit events, system logs, notifications, and backups/snapshots evidence. Use production acceptance evidence and audit records to verify scheduled maintenance.</p></Card></div>;

  const save = () => { platformOperationsStore.saveRetention(policy); notify({ title: "Retention policy saved", tone: "success" }); };
  const preview = () => { const r = platformOperationsStore.previewCleanup(); notify({ title: "Cleanup preview", description: `Would remove ${describe(r)}.`, tone: "info" }); };
  return <div className="page cleanup-page"><SectionHeader eyebrow="Platform" title="Cleanup & Retention" description="Control local prototype operational retention without touching production business records."/><div className="compact-metrics"><MetricCard label="Audit retention" value={`${policy.auditDays} days`} detail="Prototype action history" icon={Clock}/><MetricCard label="Log retention" value={`${policy.logDays} days`} detail="Prototype system logs" icon={Clock}/><MetricCard label="Snapshot retention" value={String(policy.backupCount)} detail="Latest local snapshots" icon={Trash2}/><MetricCard label="Cleanup runs" value={String(runs.filter((r) => r.mode === "executed").length)} detail="Executed locally" icon={Trash2}/></div><Card><div className="operation-section__head"><div><span>Policy</span><h3>Local retention thresholds</h3></div></div><div className="form-grid form-grid--two"><FormField label="Audit retention days"><TextInput type="number" min={30} value={policy.auditDays} onChange={(e)=>setPolicy({...policy,auditDays:Number(e.target.value)})}/></FormField><FormField label="System log retention days"><TextInput type="number" min={7} value={policy.logDays} onChange={(e)=>setPolicy({...policy,logDays:Number(e.target.value)})}/></FormField><FormField label="Notification retention days"><TextInput type="number" min={7} value={policy.notificationDays} onChange={(e)=>setPolicy({...policy,notificationDays:Number(e.target.value)})}/></FormField><FormField label="Snapshot count"><TextInput type="number" min={1} value={policy.backupCount} onChange={(e)=>setPolicy({...policy,backupCount:Number(e.target.value)})}/></FormField></div><div className="table-actions cleanup-actions"><Button onClick={save}>Save policy</Button><Button onClick={preview}>Preview cleanup</Button><Button variant="primary" onClick={()=>setConfirm(true)}>Run cleanup</Button></div></Card><Card><div className="operation-section__head"><div><span>History</span><h3>Recent cleanup evaluations</h3></div></div>{runs.slice(0,8).map((r)=><div className="mini-record" key={r.id}><div><strong>{r.mode}</strong><small>{new Date(r.createdAt).toLocaleString("en-LK")}</small></div><span>{describe(r)}</span></div>)}</Card><ConfirmDialog open={confirm} title="Run local cleanup now?" description="Only expired prototype audit events, notifications, system logs and excess local snapshots will be removed." confirmLabel="Run cleanup" danger onClose={()=>setConfirm(false)} onConfirm={()=>{const r=platformOperationsStore.runCleanup();notify({title:"Cleanup complete",description:`Removed ${describe(r)}.`,tone:"success"});setConfirm(false);}}/></div>;
}
