import { useState } from "react";
import { BadgeDollarSign, ShieldCheck } from "lucide-react";
import { Button, Card, DataTable, FormField, MetricCard, SectionHeader, TextInput, type DataTableColumn } from "../../shared/components";
import { gamingStore, type GamingProduct } from "../data/gamingStore";
import { gamingLkr, gamingMoney } from "../shared/format";
import { useGamingStore } from "../shared/useGamingStore";

export function PricingPage(){
 const settings=useGamingStore(gamingStore.getSettings); const products=useGamingStore(gamingStore.getProducts); const sources=useGamingStore(gamingStore.getSupplierProducts); const [draft,setDraft]=useState(settings);
 const economics=(p:GamingProduct)=>{const s=sources.find((x)=>x.id===p.supplierProductId); const cost=s?(s.currency==="USD"?s.cost*settings.usdToLkr:s.cost):0; const fee=p.sellingPrice*settings.gatewayFeePercent/100; return {source:s,cost,fee,profit:p.sellingPrice-cost-fee,margin:p.sellingPrice?((p.sellingPrice-cost-fee)/p.sellingPrice)*100:0};};
 const cols:DataTableColumn<GamingProduct>[]=[{key:"product",header:"Product",render:(p)=><div className="entity-cell"><strong>{p.name}</strong><small>{economics(p).source&&gamingMoney(economics(p).source!.cost,economics(p).source!.currency)} supplier cost</small></div>},{key:"cost",header:"LKR cost",render:(p)=><strong>{gamingLkr(economics(p).cost)}</strong>},{key:"sell",header:"Selling",render:(p)=><div className="entity-cell"><strong>{gamingLkr(p.sellingPrice)}</strong><small>Suggested {gamingLkr(p.suggestedPrice)}</small></div>},{key:"profit",header:"Profit",render:(p)=><div className="entity-cell"><strong>{gamingLkr(economics(p).profit)}</strong><small>{economics(p).margin.toFixed(1)}% effective</small></div>},{key:"action",header:"",width:"120px",render:(p)=><Button disabled={p.sellingPrice===p.suggestedPrice} onClick={()=>gamingStore.updateProduct(p.id,{sellingPrice:p.suggestedPrice})}>Use suggested</Button>}];
 return <div className="page"><SectionHeader eyebrow="Gaming Store" title="Pricing & Safeguards" description="Protect margin against supplier cost, currency conversion and payment fees before a storefront price goes live."/><div className="compact-metrics"><MetricCard label="USD → LKR" value={String(settings.usdToLkr)} detail="Local development rate" icon={BadgeDollarSign}/><MetricCard label="Default margin" value={`${settings.defaultMarginPercent}%`} detail="Pricing target" icon={ShieldCheck}/><MetricCard label="Minimum profit" value={gamingLkr(settings.minimumProfitLkr)} detail="Absolute safeguard" icon={ShieldCheck}/></div><Card className="operation-section"><div className="operation-section__head"><div><span>Pricing policy</span><h3>Commercial assumptions</h3></div><ShieldCheck size={18}/></div><div className="form-grid form-grid--4"><FormField label="USD to LKR"><TextInput type="number" value={draft.usdToLkr} onChange={(e)=>setDraft({...draft,usdToLkr:Number(e.target.value)})}/></FormField><FormField label="Gateway fee %"><TextInput type="number" value={draft.gatewayFeePercent} onChange={(e)=>setDraft({...draft,gatewayFeePercent:Number(e.target.value)})}/></FormField><FormField label="Default margin %"><TextInput type="number" value={draft.defaultMarginPercent} onChange={(e)=>setDraft({...draft,defaultMarginPercent:Number(e.target.value)})}/></FormField><FormField label="Minimum profit LKR"><TextInput type="number" value={draft.minimumProfitLkr} onChange={(e)=>setDraft({...draft,minimumProfitLkr:Number(e.target.value)})}/></FormField></div><div className="modal-actions"><Button onClick={()=>{gamingStore.saveSettings(draft);gamingStore.recalculatePrices();}} variant="primary">Save & recalculate</Button></div></Card><Card><div className="operation-section__head"><div><span>Product economics</span><h3>Margin review</h3></div><BadgeDollarSign size={18}/></div><DataTable rows={products} columns={cols} getKey={(p)=>p.id}/></Card></div>;
}
