import { useEffect, useState } from "react";
import { BadgeDollarSign, RefreshCw, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, DataTable, FormField, MetricCard, SectionHeader, SelectInput, TextInput, type DataTableColumn } from "../../shared/components";
import { gamingStore, type GamingProduct } from "../data/gamingStore";
import { gamingLkr, gamingMoney } from "../shared/format";
import { useGamingStore } from "../shared/useGamingStore";
import { readRuntimeTruth } from "../../services/production";
import { flushDurableWrites } from "../../services/production/durableStorage";
import { useToast } from "../../shared/feedback/ToastProvider";
import { getFazerPricing, getFazerStatus, refreshFazerPricing, refreshFazerStatus, saveFazerPricing } from "../live/fazercardsControl";

const runtime=readRuntimeTruth();

function LivePricingPage(){
 const pricing=useGamingStore(getFazerPricing); const status=useGamingStore(getFazerStatus); const {notify}=useToast();
 const [draft,setDraft]=useState(pricing); const [busy,setBusy]=useState(false); const policyReady=Boolean(draft.lkrPerUsd&&draft.markupPercent!==null);
 useEffect(()=>setDraft(pricing),[pricing]);
 useEffect(()=>{void Promise.allSettled([refreshFazerPricing(),refreshFazerStatus()]);},[]);
 const save=async()=>{setBusy(true);try{saveFazerPricing(draft);await flushDurableWrites();notify({title:"Live Gaming pricing saved",description:draft.mode==="markup"?"Catalog cards now use this LKR retail policy immediately from the already-synced private supplier cost; no supplier API resync is required.":"Catalog cards will show Check price; checkout still applies this protected LKR policy server-side.",tone:"success"});}catch(error){notify({title:"Pricing save failed",description:error instanceof Error?error.message:"Unable to persist live pricing.",tone:"danger"});}finally{setBusy(false);}};
 const refresh=async()=>{setBusy(true);try{await Promise.all([refreshFazerPricing(),refreshFazerStatus()]);notify({title:"Live pricing refreshed",description:"Latest production D1 pricing and supplier status loaded.",tone:"success"});}catch(error){notify({title:"Refresh failed",description:error instanceof Error?error.message:"Unable to refresh live pricing.",tone:"danger"});}finally{setBusy(false);}};
 return <div className="page"><SectionHeader eyebrow="Gaming Store" title="Pricing & Safeguards" description="Production pricing authority for FazerCards catalog and quotes. Changes persist to D1 and are consumed by gaming-api.nextf.lk."/>
 <div className="compact-metrics"><MetricCard label="USD → LKR" value={draft.lkrPerUsd?String(draft.lkrPerUsd):"Not set"} detail="Operator-controlled conversion" icon={BadgeDollarSign}/><MetricCard label="Markup" value={draft.markupPercent===null?"Not set":`${draft.markupPercent}%`} detail={draft.mode==="markup"?"Active retail target":"Supplier quote mode"} icon={ShieldCheck}/><MetricCard label="Supplier" value={status.connected?"Connected":"Needs check"} detail={status.balance?`${status.balance.amount} ${status.balance.currency}`:"FazerCards"} icon={RefreshCw}/></div>
 <Card className="operation-section"><div className="operation-section__head"><div><span>Live pricing policy</span><h3>FazerCards retail calculation</h3></div><div className="table-actions"><Badge tone={draft.mode==="markup"?"success":"neutral"}>{draft.mode==="markup"?"Markup pricing":"Supplier quote"}</Badge><Button onClick={refresh} disabled={busy}><RefreshCw size={14}/> Refresh</Button></div></div>
 <div className="form-grid form-grid--4"><FormField label="Pricing mode"><SelectInput value={draft.mode} onChange={(e)=>setDraft({...draft,mode:e.target.value as typeof draft.mode})}><option value="supplier_quote">Supplier quote — price at checkout</option><option value="markup">Markup — show LKR catalog prices</option></SelectInput></FormField><FormField label="USD to LKR"><TextInput type="number" min="0" step="0.01" value={draft.lkrPerUsd??""} placeholder="e.g. 315" onChange={(e)=>setDraft({...draft,lkrPerUsd:e.target.value?Number(e.target.value):null})}/></FormField><FormField label="Default markup %"><TextInput type="number" min="0" step="0.1" value={draft.markupPercent??""} placeholder="e.g. 10" onChange={(e)=>setDraft({...draft,markupPercent:e.target.value?Number(e.target.value):null})}/></FormField><FormField label="Gateway fee %"><TextInput type="number" min="0" step="0.1" value={draft.gatewayFeePercent} onChange={(e)=>setDraft({...draft,gatewayFeePercent:Number(e.target.value)})}/></FormField><FormField label="Minimum profit LKR"><TextInput type="number" min="0" value={draft.minimumProfitLkr} onChange={(e)=>setDraft({...draft,minimumProfitLkr:Number(e.target.value)})}/></FormField><FormField label="Fixed fee LKR"><TextInput type="number" min="0" value={draft.fixedFeeLkr} onChange={(e)=>setDraft({...draft,fixedFeeLkr:Number(e.target.value)})}/></FormField><FormField label="Round to LKR"><TextInput type="number" min="1" value={draft.roundToLkr} onChange={(e)=>setDraft({...draft,roundToLkr:Number(e.target.value)})}/></FormField></div>
 {!policyReady?<p className="security-note">USD → LKR and Default markup % are required before supplier products can produce a customer retail quote.</p>:null}<div className="modal-actions"><Button variant="primary" disabled={busy||!policyReady} onClick={save}>{busy?"Saving...":"Save & refresh catalog pricing"}</Button></div></Card>
 <Card className="architecture-callout"><div className="operation-section__head"><div><span>Production behavior</span><h3>CMS is the pricing control plane</h3></div><Badge tone="success">D1 backed</Badge></div><p>FazerCards API credentials remain encrypted Worker secrets. Exchange rate, markup, gateway fee, minimum profit, fixed fee and rounding are controlled here. In Markup mode the public catalog calculates LKR display prices from the already-synced private supplier cost, so normal pricing changes do not require another supplier catalog sync. Checkout recalculates the protected price server-side.</p></Card></div>;
}

function LocalPricingPage(){
 const settings=useGamingStore(gamingStore.getSettings); const products=useGamingStore(gamingStore.getProducts); const sources=useGamingStore(gamingStore.getSupplierProducts); const [draft,setDraft]=useState(settings);
 const economics=(p:GamingProduct)=>{const s=sources.find((x)=>x.id===p.supplierProductId); const cost=s?(s.currency==="USD"?s.cost*settings.usdToLkr:s.cost):0; const fee=p.sellingPrice*settings.gatewayFeePercent/100; return {source:s,cost,fee,profit:p.sellingPrice-cost-fee,margin:p.sellingPrice?((p.sellingPrice-cost-fee)/p.sellingPrice)*100:0};};
 const cols:DataTableColumn<GamingProduct>[]=[{key:"product",header:"Product",render:(p)=><div className="entity-cell"><strong>{p.name}</strong><small>{economics(p).source&&gamingMoney(economics(p).source!.cost,economics(p).source!.currency)} supplier cost</small></div>},{key:"cost",header:"LKR cost",render:(p)=><strong>{gamingLkr(economics(p).cost)}</strong>},{key:"sell",header:"Selling",render:(p)=><div className="entity-cell"><strong>{gamingLkr(p.sellingPrice)}</strong><small>Suggested {gamingLkr(p.suggestedPrice)}</small></div>},{key:"profit",header:"Profit",render:(p)=><div className="entity-cell"><strong>{gamingLkr(economics(p).profit)}</strong><small>{economics(p).margin.toFixed(1)}% effective</small></div>},{key:"action",header:"",width:"120px",render:(p)=><Button disabled={p.sellingPrice===p.suggestedPrice} onClick={()=>gamingStore.updateProduct(p.id,{sellingPrice:p.suggestedPrice})}>Use suggested</Button>}];
 return <div className="page"><SectionHeader eyebrow="Gaming Store" title="Pricing & Safeguards" description="Local development pricing sandbox."/><div className="compact-metrics"><MetricCard label="USD → LKR" value={String(settings.usdToLkr)} detail="Local assumption" icon={BadgeDollarSign}/><MetricCard label="Default margin" value={`${settings.defaultMarginPercent}%`} detail="Pricing target" icon={ShieldCheck}/><MetricCard label="Minimum profit" value={gamingLkr(settings.minimumProfitLkr)} detail="Absolute safeguard" icon={ShieldCheck}/></div><Card className="operation-section"><div className="form-grid form-grid--4"><FormField label="USD to LKR"><TextInput type="number" value={draft.usdToLkr} onChange={(e)=>setDraft({...draft,usdToLkr:Number(e.target.value)})}/></FormField><FormField label="Gateway fee %"><TextInput type="number" value={draft.gatewayFeePercent} onChange={(e)=>setDraft({...draft,gatewayFeePercent:Number(e.target.value)})}/></FormField><FormField label="Default margin %"><TextInput type="number" value={draft.defaultMarginPercent} onChange={(e)=>setDraft({...draft,defaultMarginPercent:Number(e.target.value)})}/></FormField><FormField label="Minimum profit LKR"><TextInput type="number" value={draft.minimumProfitLkr} onChange={(e)=>setDraft({...draft,minimumProfitLkr:Number(e.target.value)})}/></FormField></div><div className="modal-actions"><Button onClick={()=>{gamingStore.saveSettings(draft);gamingStore.recalculatePrices();}} variant="primary">Save & recalculate</Button></div></Card><Card><DataTable rows={products} columns={cols} getKey={(p)=>p.id}/></Card></div>;
}

export function PricingPage(){return runtime.isProduction?<LivePricingPage/>:<LocalPricingPage/>;}
