import { useMemo, useState } from "react";
import { Building2, Layers3, Plus } from "lucide-react";
import { Badge, Button, Card, DataTable, FormField, MetricCard, Modal, PageToolbar, SectionHeader, SelectInput, TextInput, type DataTableColumn } from "../../shared/components";
import { platformOperationsStore, type OrganizationRecord, type WorkspaceRecord } from "../services/platformOperationsStore";
import { usePlatformOperations } from "../shared/usePlatformOperations";
import { validators } from "../../shared/validation";
import { useToast } from "../../shared/feedback/ToastProvider";

export function OrganizationsPage(){
 const orgs=usePlatformOperations(platformOperationsStore.getOrganizations); const workspaces=usePlatformOperations(platformOperationsStore.getWorkspaces); const {notify}=useToast();
 const [query,setQuery]=useState(""); const [orgOpen,setOrgOpen]=useState(false); const [wsOpen,setWsOpen]=useState(false); const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [wsName,setWsName]=useState(""); const [wsKey,setWsKey]=useState(""); const [orgId,setOrgId]=useState(orgs[0]?.id??"");
 const rows=useMemo(()=>workspaces.filter((r)=>`${r.name} ${r.key}`.toLowerCase().includes(query.toLowerCase())),[workspaces,query]);
 const columns:DataTableColumn<WorkspaceRecord>[]=[{key:"workspace",header:"Workspace",render:(r)=><div className="entity-cell"><strong>{r.name}</strong><small>{r.key}</small></div>},{key:"org",header:"Organization",render:(r)=><span>{orgs.find((o)=>o.id===r.organizationId)?.name??"Unknown"}</span>},{key:"domains",header:"Business domains",render:(r)=><span className="muted-cell">{r.domains.join(", ")}</span>},{key:"status",header:"Status",render:(r)=><Badge tone={r.status==="active"?"success":"warning"}>{r.status}</Badge>}];
 const createOrg=()=>{const n=validators.required(name,"Organization name"),s=validators.slug(slug);if(n||s)return notify({title:"Check organization",description:n||s,tone:"danger"});platformOperationsStore.addOrganization(name.trim(),slug.trim());notify({title:"Organization created",description:name.trim(),tone:"success"});setOrgOpen(false);setName("");setSlug("");};
 const createWs=()=>{const n=validators.required(wsName,"Workspace name"),k=validators.slug(wsKey);if(n||k||!orgId)return notify({title:"Check workspace",description:n||k||"Select an organization.",tone:"danger"});platformOperationsStore.addWorkspace(orgId,wsName.trim(),wsKey.trim());notify({title:"Workspace created",description:wsName.trim(),tone:"success"});setWsOpen(false);setWsName("");setWsKey("");};
 return <div className="page"><SectionHeader eyebrow="Platform" title="Organizations & Workspaces" description="Define administrative ownership boundaries without mixing business-domain data." action={<div className="table-actions"><Button onClick={()=>setOrgOpen(true)}><Plus size={15}/>Organization</Button><Button variant="primary" onClick={()=>setWsOpen(true)}><Plus size={15}/>Workspace</Button></div>}/><div className="compact-metrics"><MetricCard label="Organizations" value={String(orgs.length)} detail="Administrative owners" icon={Building2}/><MetricCard label="Workspaces" value={String(workspaces.length)} detail="Operational boundaries" icon={Layers3}/></div><Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search workspaces…"/><DataTable rows={rows} columns={columns} getKey={(r)=>r.id}/></Card>
 <Modal open={orgOpen} onClose={()=>setOrgOpen(false)} title="Create organization" footer={<><Button onClick={()=>setOrgOpen(false)}>Cancel</Button><Button variant="primary" onClick={createOrg}>Create</Button></>}><div className="form-grid form-grid--two"><FormField label="Name" required><TextInput value={name} onChange={(e)=>setName(e.target.value)}/></FormField><FormField label="Slug" required><TextInput value={slug} onChange={(e)=>setSlug(e.target.value.toLowerCase())}/></FormField></div></Modal>
 <Modal open={wsOpen} onClose={()=>setWsOpen(false)} title="Create workspace" footer={<><Button onClick={()=>setWsOpen(false)}>Cancel</Button><Button variant="primary" onClick={createWs}>Create</Button></>}><div className="form-grid form-grid--two"><FormField label="Organization" required><SelectInput value={orgId} onChange={(e)=>setOrgId(e.target.value)}>{orgs.map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</SelectInput></FormField><FormField label="Workspace name" required><TextInput value={wsName} onChange={(e)=>setWsName(e.target.value)}/></FormField><FormField label="Key" required><TextInput value={wsKey} onChange={(e)=>setWsKey(e.target.value.toLowerCase())}/></FormField></div></Modal></div>;
}
