import { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, Clock3, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";
import { Button, Card, DataTable, SectionHeader, StatePanel, type DataTableColumn } from "../../shared/components";
import { loadFirstPartyAnalytics, type TrackingDimension, type TrackingHealth, type TrackingReport } from "./firstPartyAnalytics";
const eventLabel=(key:string)=>key.split(".").map((part)=>part.charAt(0).toUpperCase()+part.slice(1)).join(" ");
export function FirstPartyAnalyticsPage(){
  const [days,setDays]=useState<7|30|90>(30);const [report,setReport]=useState<TrackingReport>();const [health,setHealth]=useState<TrackingHealth>();const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const result=await loadFirstPartyAnalytics(days);setReport(result.report);setHealth(result.health);}catch(value){setError(value instanceof Error?value.message:"Analytics could not be loaded.");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[days]);const rows=useMemo(()=>report?.dimensions.slice().reverse().slice(0,100)??[],[report]);
  if(loading&&!report)return <div className="page"><SectionHeader eyebrow="Platform" title="First-party analytics" description="Loading the NEXT F tracking pipeline."/><StatePanel state="loading" title="Loading analytics" description="Reading aggregate reports and tracking health."/></div>;
  if(error&&!report)return <div className="page"><SectionHeader eyebrow="Platform" title="First-party analytics" description="The reporting surface is temporarily unavailable."/><StatePanel state="error" title="Analytics unavailable" description={error} action={<Button onClick={()=>void load()}><RefreshCw size={15}/>Retry</Button>}/></div>;
  const columns:DataTableColumn<TrackingDimension>[]=[{key:"time",header:"Hour",render:(row)=><span>{new Date(row.hourStart).toLocaleString("en-LK")}</span>},{key:"event",header:"Event",render:(row)=><strong>{eventLabel(row.eventKey)}</strong>},{key:"count",header:"Count",render:(row)=><strong>{row.value}</strong>}];
  return <div className="page gaming-analytics-page"><SectionHeader eyebrow="Platform" title="First-party analytics" description="Contract-aligned traffic measurement for the NEXT F main website." action={<div className="analytics-window" aria-label="Analytics window">{([7,30,90] as const).map((value)=><Button key={value} variant={days===value?"primary":"secondary"} onClick={()=>setDays(value)}>{value}d</Button>)}</div>}/><div className="analytics-kpi-strip"><div className="analytics-stat analytics-stat--accent"><div className="analytics-stat__head"><span>Received</span><Activity size={17}/></div><strong>{health?.receivedCount??0}</strong></div><div className="analytics-stat analytics-stat--success"><div className="analytics-stat__head"><span>Accepted</span><CheckCircle2 size={17}/></div><strong>{health?.acceptedCount??0}</strong></div><div className="analytics-stat analytics-stat--warning"><div className="analytics-stat__head"><span>Restricted</span><ShieldCheck size={17}/></div><strong>{health?.consentRestrictedCount??0}</strong></div><div className="analytics-stat"><div className="analytics-stat__head"><span>Rejected</span><TriangleAlert size={17}/></div><strong>{health?.rejectedCount??0}</strong></div></div><Card className="analytics-tracking-panel"><div className="operation-section__head"><div><span>Pipeline</span><h3>Tracking health</h3></div><Activity size={18}/></div><div className="analytics-health-grid"><div className="analytics-stat"><div className="analytics-stat__head"><span>Collector</span><ShieldCheck size={17}/></div><strong>{health?.collectorStatus??"unknown"}</strong></div><div className="analytics-stat"><div className="analytics-stat__head"><span>Processing</span><Clock3 size={17}/></div><strong>{health?.processingStatus??"unknown"}</strong></div><div className="analytics-stat"><div className="analytics-stat__head"><span>SDK</span><Activity size={17}/></div><strong>{health?.sdkDetected?health.sdkVersion:"Not detected"}</strong></div><div className="analytics-stat"><div className="analytics-stat__head"><span>Last event</span><Clock3 size={17}/></div><strong>{health?.lastEventReceivedAt?new Date(health.lastEventReceivedAt).toLocaleString("en-LK"):"No events"}</strong></div></div></Card><Card className="analytics-table-card"><div className="operation-section__head"><div><span>Aggregate stream</span><h3>Event activity</h3></div><RefreshCw size={18}/></div><DataTable rows={rows} columns={columns} getKey={(row)=>`${row.hourStart}:${row.eventKey}`} empty="No accepted first-party events have been processed in this window."/></Card>{error?<Card className="architecture-callout"><strong>Last refresh warning</strong><p>{error}</p></Card>:null}</div>;
}
