import { platformStore, type PlatformNotification } from "../../platform/services/platformStore";
import { digitalStore } from "../../next-f/data/digitalStore";
import { softwareStore } from "../../software/data/softwareStore";
import { helpCenterStore } from "../../platform/help-center/data/helpCenterStore";
import { loadGamingOperationsSnapshot, type LiveGamingOperationsSnapshot } from "../../gaming-store/live-operations/operations";
import { loadGamingSupportSnapshot, type GamingSupportSnapshot } from "../../gaming-store/support/support";
import { readDurableValue, writeDurableValue } from "../production/durableStorage";

const ACK_PREFIX = "nextf.v0.7.operations.acknowledged.";
const ackKey = (staffUserId = "local") => `${ACK_PREFIX}${staffUserId}`;
const acked = (staffUserId = "local") => readDurableValue<string[]>(ackKey(staffUserId), []);
const generated = (staffUserId: string, id: string, title: string, detail: string, domain: string, tone: PlatformNotification["tone"], createdAt: string, href?: string): PlatformNotification => ({ id, title, detail, domain, tone, read: acked(staffUserId).includes(id), createdAt, ...(href ? { href } : {}) });

function staticOperationalNotifications(staffUserId: string): PlatformNotification[] {
  const items: PlatformNotification[] = [...platformStore.getNotifications()];
  helpCenterStore.getRequests().filter((request) => ["high", "urgent"].includes(request.priority) && !["resolved", "closed"].includes(request.status)).forEach((request) => items.push(generated(staffUserId, `ops:help:${request.id}`, `${request.number} · ${request.subject}`, `${request.customerName} · ${request.business} · ${request.status.replace(/_/g, " ")}`, "Help Center", request.priority === "urgent" ? "danger" : "warning", request.updatedAt, "/platform/help-center")));
  digitalStore.getSites().filter((site) => site.status === "offline" || site.status === "degraded").forEach((site) => items.push(generated(staffUserId, `ops:site:${site.id}`, `${site.domain} is ${site.status}`, `${site.name} requires Digital operations attention.`, "Digital", site.status === "offline" ? "danger" : "warning", site.updatedAt, "/next-f-digital/sites")));
  digitalStore.getTickets().filter((ticket) => ["high", "urgent"].includes(ticket.priority) && !["resolved", "closed"].includes(ticket.status)).forEach((ticket) => items.push(generated(staffUserId, `ops:ticket:${ticket.id}`, `${ticket.priority.toUpperCase()} support ticket`, `${ticket.number} · ${ticket.subject}`, "Digital", ticket.priority === "urgent" ? "danger" : "warning", ticket.updatedAt, "/next-f-digital/support")));
  const now = Date.now();
  digitalStore.getSubscriptions().filter((sub) => sub.status === "active" && new Date(sub.nextRenewalAt).getTime() - now < 14 * 86400000).forEach((sub) => items.push(generated(staffUserId, `ops:renewal:${sub.id}`, "Digital renewal approaching", `${sub.name} renews ${new Date(sub.nextRenewalAt).toLocaleDateString()}.`, "Digital", "info", sub.nextRenewalAt, "/next-f-digital/billing")));
  softwareStore.getLicenses().filter((license) => license.status === "active" && license.expiresAt && new Date(license.expiresAt).getTime() - now < 30 * 86400000).forEach((license) => items.push(generated(staffUserId, `ops:license:${license.id}`, "Software license expiring", `${license.key} expires ${new Date(license.expiresAt!).toLocaleDateString()}.`, "Software", "info", license.expiresAt!, "/next-f-software/licenses")));
  softwareStore.getSupportCases().filter((ticket) => ticket.status !== "closed" && ticket.priority !== "normal").forEach((ticket) => items.push(generated(staffUserId, `ops:software-support:${ticket.id}`, `${ticket.priority.toUpperCase()} software support`, `${ticket.number} · ${ticket.subject}`, "Software", ticket.priority === "urgent" ? "danger" : "warning", ticket.updatedAt, "/next-f-software/support")));
  return items;
}
function gamingNotifications(staffUserId: string, snapshot: LiveGamingOperationsSnapshot): PlatformNotification[] {
  const items: PlatformNotification[] = [];
  snapshot.paymentProofs.filter((row) => row.status === "pending_review").forEach((row) => items.push(generated(staffUserId, `ops:gaming:payment:${row.proofId}`, "Payment review required", `${row.orderNumber} · ${row.paymentMethodLabel} · LKR ${row.amountLkr.toLocaleString("en-LK")}`, "Gaming · Payments", "warning", row.submittedAt, "/gaming-store/live-operations")));
  snapshot.fulfillmentJobs.filter((row) => ["retry", "blocked", "failed"].includes(row.state)).forEach((row) => items.push(generated(staffUserId, `ops:gaming:fulfillment:${row.jobId}`, row.state === "failed" ? "Gaming fulfillment failed" : "Gaming fulfillment needs attention", `${row.orderId} · ${row.state.replace(/_/g, " ")}${row.lastError ? ` · ${row.lastError}` : ""}`, "Gaming · Fulfillment", row.state === "failed" ? "danger" : "warning", row.updatedAt, "/gaming-store/live-operations")));
  snapshot.riskAssessments.filter((row) => row.requiresReview || ["held", "review"].includes(row.state)).forEach((row) => items.push(generated(staffUserId, `ops:gaming:risk:${row.assessmentId}`, "Gaming order held for review", `${row.orderNumber} · ${row.level} risk · score ${row.score}`, "Gaming · Risk", row.level === "high" ? "danger" : "warning", row.updatedAt, "/gaming-store/live-operations")));
  snapshot.refunds.filter((row) => ["requested", "approved", "sent"].includes(row.status)).forEach((row) => items.push(generated(staffUserId, `ops:gaming:refund:${row.refundId}:${row.status}`, row.status === "requested" ? "Refund decision required" : row.status === "approved" ? "Refund payout pending" : "Refund completion pending", `${row.orderNumber} · LKR ${row.amountLkr.toLocaleString("en-LK")}`, "Gaming · Refunds", row.status === "requested" ? "warning" : "info", row.updatedAt, "/gaming-store/live-operations")));
  snapshot.notifications.forEach((row) => { const deliveryState=row.delivery?.state||""; const attention=["retry","blocked","failed"].includes(row.state)||["delayed","bounced","complained","failed","suppressed"].includes(deliveryState); if(!attention)return; const danger=["failed","bounced","complained","suppressed"].includes(row.state)||["bounced","complained","failed","suppressed"].includes(deliveryState); items.push(generated(staffUserId,`ops:gaming:notification:${row.notificationId}:${deliveryState||row.state}`,"Customer notification needs attention",`${row.orderNumber} · ${row.templateKey.replace(/_/g," ")} · ${deliveryState||row.state}${row.delivery?.reason||row.lastError?` · ${row.delivery?.reason||row.lastError}`:""}`,"Gaming · Notifications",danger?"danger":"warning",row.delivery?.lastEventAt||row.updatedAt,"/gaming-store/live-operations")); });
  return items;
}
function gamingSupportNotifications(staffUserId: string, snapshot: GamingSupportSnapshot): PlatformNotification[] {
  return snapshot.cases.filter((row) => !["resolved", "closed"].includes(row.status) && (row.status === "waiting_internal" || row.priority === "urgent" || row.sla.firstResponseBreached || row.sla.resolutionBreached || !row.assignee)).map((row) => { const breached=row.sla.firstResponseBreached||row.sla.resolutionBreached; const title=row.status==="waiting_internal"?"Customer replied to Gaming support":breached?"Gaming support SLA needs attention":row.priority==="urgent"?"Urgent Gaming support case":"Unassigned Gaming support case"; return generated(staffUserId,`ops:gaming:support:${row.caseId}:${row.updatedAt}`,title,`${row.caseNumber} · ${row.subject} · ${row.orderNumber}`,"Gaming · Support",breached||row.priority==="urgent"?"danger":"warning",row.updatedAt,"/gaming-store/support"); });
}
export async function loadGamingOperationsNotifications(staffUserId: string, includeSupport: boolean): Promise<PlatformNotification[]> { try { const [operations,support]=await Promise.all([loadGamingOperationsSnapshot(),includeSupport?loadGamingSupportSnapshot().catch(()=>undefined):Promise.resolve(undefined)]); return [...gamingNotifications(staffUserId,operations),...(support?gamingSupportNotifications(staffUserId,support):[])]; } catch { return [generated(staffUserId,'ops:gaming:feed-unavailable','Gaming operations feed unavailable','The CMS could not refresh live Gaming operational notifications.','Gaming · Operations','warning',new Date().toISOString(),'/gaming-store/live-operations')]; } }
export function getOperationsNotifications(staffUserId="local",live:PlatformNotification[]=[]):PlatformNotification[]{const byId=new Map<string,PlatformNotification>();for(const item of [...staticOperationalNotifications(staffUserId),...live])byId.set(item.id,item);return[...byId.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export function markOperationsNotification(staffUserId:string,id:string,readState=true){if(!id.startsWith("ops:"))return platformStore.markNotification(id,readState);const set=new Set(acked(staffUserId));if(readState)set.add(id);else set.delete(id);writeDurableValue(ackKey(staffUserId),[...set]);window.dispatchEvent(new CustomEvent("nextf:operations-center"));}
export function markAllOperationsNotifications(staffUserId:string,items?:PlatformNotification[]){platformStore.markAllNotifications();const generatedIds=(items??getOperationsNotifications(staffUserId)).filter((item)=>item.id.startsWith("ops:")).map((item)=>item.id);writeDurableValue(ackKey(staffUserId),generatedIds);window.dispatchEvent(new CustomEvent("nextf:operations-center"));}
