import { useState } from "react";
import { Plus } from "lucide-react";
import { Badge, Button, Card, DataTable, FormField, Modal, SelectInput, TextInput, type DataTableColumn } from "../../../shared/components";
import { useToast } from "../../../shared/feedback/ToastProvider";
import { helpCenterStore } from "../data/helpCenterStore";
import type { HelpAnnouncement, HelpAudience, HelpContentStatus } from "../data/types";
import { useHelpCenter } from "../shared/useHelpCenter";

export function AnnouncementsPanel(){
  const rows=useHelpCenter(helpCenterStore.getAnnouncements); const {notify}=useToast(); const [open,setOpen]=useState(false); const [form,setForm]=useState({title:"",message:"",audience:"all" as HelpAudience,status:"draft" as HelpContentStatus,publishAt:new Date().toISOString().slice(0,16)});
  const cols:DataTableColumn<HelpAnnouncement>[]=[{key:"notice",header:"Announcement",render:(r)=><div className="entity-cell"><strong>{r.title}</strong><small>{r.message}</small></div>},{key:"audience",header:"Audience",render:(r)=><Badge>{r.audience}</Badge>},{key:"publish",header:"Publish",render:(r)=><span>{new Date(r.publishAt).toLocaleString("en-LK")}</span>},{key:"status",header:"Status",render:(r)=><Badge tone={r.status==="published"?"success":r.status==="draft"?"warning":"neutral"}>{r.status}</Badge>},{key:"action",header:"",render:(r)=><Button onClick={()=>helpCenterStore.updateAnnouncement(r.id,{status:r.status==="published"?"archived":"published"})}>{r.status==="published"?"Archive":"Publish"}</Button>}];
  const create=()=>{if(!form.title.trim()||!form.message.trim())return;helpCenterStore.addAnnouncement({...form,publishAt:new Date(form.publishAt).toISOString(),expiresAt:undefined});notify({title:"Announcement created",tone:"success"});setOpen(false);setForm({...form,title:"",message:"",status:"draft"});};
  return <><div className="section-actions"><Button variant="primary" onClick={()=>setOpen(true)}><Plus size={15}/> Announcement</Button></div><Card><DataTable rows={rows} columns={cols} getKey={(r)=>r.id}/></Card><Modal open={open} onClose={()=>setOpen(false)} title="Create announcement"><div className="form-grid form-grid--two"><FormField label="Title" required><TextInput value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></FormField><FormField label="Audience"><SelectInput value={form.audience} onChange={(e)=>setForm({...form,audience:e.target.value as HelpAudience})}><option value="all">All NEXT F</option><option value="digital">Digital</option><option value="gaming">Gaming Store</option><option value="software">Software</option></SelectInput></FormField><FormField label="Publish time"><TextInput type="datetime-local" value={form.publishAt} onChange={(e)=>setForm({...form,publishAt:e.target.value})}/></FormField><FormField label="Initial status"><SelectInput value={form.status} onChange={(e)=>setForm({...form,status:e.target.value as HelpContentStatus})}><option value="draft">Draft</option><option value="published">Published</option></SelectInput></FormField><FormField label="Message"><textarea className="text-input help-textarea" value={form.message} onChange={(e)=>setForm({...form,message:e.target.value})}/></FormField></div><div className="modal-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="primary" onClick={create}>Create</Button></div></Modal></>;
}
