import { useState } from "react";
import { Copy, Plus } from "lucide-react";
import { Badge, Button, Card, DataTable, FormField, Modal, SelectInput, TextInput, type DataTableColumn } from "../../../shared/components";
import { useToast } from "../../../shared/feedback/ToastProvider";
import { helpCenterStore } from "../data/helpCenterStore";
import type { HelpAudience, HelpSavedReply } from "../data/types";
import { useHelpCenter } from "../shared/useHelpCenter";

export function RepliesPanel(){const rows=useHelpCenter(helpCenterStore.getReplies);const {notify}=useToast();const [open,setOpen]=useState(false);const [form,setForm]=useState({title:"",shortcut:"",body:"",audience:"all" as HelpAudience});const cols:DataTableColumn<HelpSavedReply>[]=[{key:"reply",header:"Saved reply",render:(r)=><div className="entity-cell"><strong>{r.title}</strong><small>/{r.shortcut} · {r.body}</small></div>},{key:"audience",header:"Audience",render:(r)=><Badge>{r.audience}</Badge>},{key:"status",header:"Status",render:(r)=><Badge tone={r.active?"success":"neutral"}>{r.active?"active":"disabled"}</Badge>},{key:"action",header:"",render:(r)=><div className="table-actions"><Button onClick={()=>{navigator.clipboard?.writeText(r.body);notify({title:"Reply copied",tone:"success"});}}><Copy size={14}/> Copy</Button><Button onClick={()=>helpCenterStore.updateReply(r.id,{active:!r.active})}>{r.active?"Disable":"Enable"}</Button></div>}];const create=()=>{if(!form.title.trim()||!form.shortcut.trim()||!form.body.trim())return;helpCenterStore.addReply({...form,shortcut:form.shortcut.toLowerCase().replace(/[^a-z0-9-]/g,"-")});notify({title:"Saved reply created",tone:"success"});setOpen(false);setForm({title:"",shortcut:"",body:"",audience:"all"});};return <Card><div className="operation-section__head"><div><span>Agent productivity</span><h3>Saved replies</h3></div><Button variant="primary" onClick={()=>setOpen(true)}><Plus size={15}/> Reply</Button></div><DataTable rows={rows} columns={cols} getKey={(r)=>r.id}/><Modal open={open} onClose={()=>setOpen(false)} title="Create saved reply"><div className="form-grid form-grid--two"><FormField label="Title"><TextInput value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></FormField><FormField label="Shortcut"><TextInput placeholder="payment-review" value={form.shortcut} onChange={(e)=>setForm({...form,shortcut:e.target.value})}/></FormField><FormField label="Audience"><SelectInput value={form.audience} onChange={(e)=>setForm({...form,audience:e.target.value as HelpAudience})}><option value="all">All NEXT F</option><option value="digital">Digital</option><option value="gaming">Gaming</option><option value="software">Software</option></SelectInput></FormField><FormField label="Reply body"><textarea className="text-input help-textarea" value={form.body} onChange={(e)=>setForm({...form,body:e.target.value})}/></FormField></div><div className="modal-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="primary" onClick={create}>Create</Button></div></Modal></Card>}
