import { useMemo, useState } from "react";
import { Boxes, Plus, Tags } from "lucide-react";
import { Button, Card, DataTable, FormField, MetricCard, Modal, PageToolbar, SectionHeader, SelectInput, TextInput, Toggle, type DataTableColumn } from "../../shared/components";
import { softwareStore, type SoftwareEdition, type SoftwareProduct } from "../data/softwareStore";
import { usd } from "../shared/format";
import { SoftwareStatus } from "../shared/SoftwareStatus";
import { useSoftwareStore } from "../shared/useSoftwareStore";
import { validators } from "../../shared/validation";
import { useToast } from "../../shared/feedback/ToastProvider";

export function ProductsPage(){
 const products=useSoftwareStore(softwareStore.getProducts), editions=useSoftwareStore(softwareStore.getEditions); const {notify}=useToast();
 const [query,setQuery]=useState(""); const [productModal,setProductModal]=useState(false); const [editionModal,setEditionModal]=useState(false); const [attemptedProduct,setAttemptedProduct]=useState(false); const [attemptedEdition,setAttemptedEdition]=useState(false);
 const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [type,setType]=useState<SoftwareProduct["type"]>("plugin"); const [editionProduct,setEditionProduct]=useState(products[0]?.id??""); const [editionName,setEditionName]=useState("Personal"); const [price,setPrice]=useState("39"); const [limit,setLimit]=useState("1");
 const rows=useMemo(()=>products.filter((p)=>`${p.name} ${p.slug} ${p.type}`.toLowerCase().includes(query.toLowerCase())),[products,query]);
 const productNameError=attemptedProduct?validators.required(name,"Product name"):""; const slugError=attemptedProduct?(validators.required(slug,"Slug")||validators.slug(slug)||(products.some((p)=>p.slug===slug.trim())?"This product slug already exists.":"")):"";
 const editionNameError=attemptedEdition?validators.required(editionName,"Edition name"):""; const priceError=attemptedEdition?validators.positive(price,"Price"):""; const limitError=attemptedEdition?validators.positive(limit,"Activation limit"):""; const duplicateEdition=attemptedEdition&&editions.some((e)=>e.productId===editionProduct&&e.name.toLowerCase()===editionName.trim().toLowerCase())?"This edition already exists for the selected product.":"";
 const cols:DataTableColumn<SoftwareProduct>[]=[{key:"product",header:"Product",render:(p)=><div className="entity-cell"><strong>{p.name}</strong><small>{p.slug} · {p.type}</small></div>},{key:"editions",header:"Editions",render:(p)=><strong>{editions.filter((e)=>e.productId===p.id).length}</strong>},{key:"status",header:"Status",render:(p)=><SoftwareStatus value={p.status}/>},{key:"action",header:"",render:(p)=><Toggle checked={p.status==="active"} onChange={(active)=>{softwareStore.updateProduct(p.id,{status:active?"active":"draft"});notify({title:active?"Product activated":"Product moved to draft",description:p.name,tone:"success"});}}/>}];
 const ecols:DataTableColumn<SoftwareEdition>[]=[{key:"edition",header:"Edition",render:(e)=><div className="entity-cell"><strong>{products.find((p)=>p.id===e.productId)?.name} · {e.name}</strong><small>{e.billingModel.replace(/_/g," ")} · {e.activationLimit} activations</small></div>},{key:"price",header:"Price",render:(e)=><strong>{usd(e.price)}</strong>},{key:"entitlement",header:"Entitlement",render:(e)=><div className="entity-cell"><strong>{e.updateMonths} mo updates</strong><small>{e.supportMonths} mo support</small></div>},{key:"active",header:"Sell",render:(e)=><Toggle checked={e.active} onChange={(active)=>{softwareStore.updateEdition(e.id,{active});notify({title:active?"Edition enabled":"Edition disabled",description:e.name,tone:"success"});}}/>}];
 const createProduct=()=>{setAttemptedProduct(true);if(productNameError||slugError||!name.trim()||!slug.trim())return;const row=softwareStore.addProduct({name:name.trim(),slug:slug.trim(),type,description:""});notify({title:"Software product created",description:row.name,tone:"success"});setProductModal(false);setAttemptedProduct(false);setName("");setSlug("");};
 const createEdition=()=>{setAttemptedEdition(true);if(!editionProduct||editionNameError||priceError||limitError||duplicateEdition||!editionName.trim())return;const row=softwareStore.addEdition({productId:editionProduct,name:editionName.trim(),billingModel:"annual",price:Number(price),currency:"USD",activationLimit:Number(limit),updateMonths:12,supportMonths:12,active:true});notify({title:"Edition created",description:`${row.name} is ready for commercial use.`,tone:"success"});setEditionModal(false);setAttemptedEdition(false);};
 return <div className="page"><SectionHeader eyebrow="NEXT F Software" title="Products & Editions" description="Commercial product definitions stay separate from release files and license records." action={<Button variant="primary" onClick={()=>{setAttemptedProduct(false);setProductModal(true);}}><Plus size={15}/> Product</Button>}/><div className="compact-metrics"><MetricCard label="Products" value={String(products.length)} detail={`${products.filter((p)=>p.status==="active").length} active`} icon={Boxes}/><MetricCard label="Editions" value={String(editions.length)} detail="Plans and activation limits" icon={Tags}/></div><Card className="operation-section"><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search software products…"><Button onClick={()=>{setEditionProduct(products[0]?.id??"");setAttemptedEdition(false);setEditionModal(true);}} disabled={products.length===0}><Plus size={14}/> Edition</Button></PageToolbar><DataTable rows={rows} columns={cols} getKey={(p)=>p.id}/></Card><Card><div className="operation-section__head"><div><span>Commercial model</span><h3>Editions</h3></div><Tags size={18}/></div><DataTable rows={editions} columns={ecols} getKey={(e)=>e.id}/></Card>
 <Modal open={productModal} onClose={()=>setProductModal(false)} title="Create software product"><div className="form-grid"><FormField label="Name" required error={productNameError}><TextInput aria-invalid={!!productNameError} value={name} onChange={(e)=>setName(e.target.value)}/></FormField><FormField label="Slug" required error={slugError}><TextInput aria-invalid={!!slugError} value={slug} onChange={(e)=>setSlug(e.target.value)}/></FormField><FormField label="Type"><SelectInput value={type} onChange={(e)=>setType(e.target.value as SoftwareProduct["type"])}><option value="plugin">Plugin</option><option value="addon">Add-on</option><option value="bundle">Bundle</option></SelectInput></FormField></div><div className="modal-actions"><Button onClick={()=>setProductModal(false)}>Cancel</Button><Button variant="primary" onClick={createProduct}>Create</Button></div></Modal>
 <Modal open={editionModal} onClose={()=>setEditionModal(false)} title="Create edition"><div className="form-grid form-grid--two"><FormField label="Product" required><SelectInput value={editionProduct} onChange={(e)=>setEditionProduct(e.target.value)}>{products.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</SelectInput></FormField><FormField label="Edition name" required error={editionNameError||duplicateEdition}><TextInput aria-invalid={!!(editionNameError||duplicateEdition)} value={editionName} onChange={(e)=>setEditionName(e.target.value)}/></FormField><FormField label="Annual price (USD)" required error={priceError}><TextInput aria-invalid={!!priceError} type="number" min="0.01" step="0.01" value={price} onChange={(e)=>setPrice(e.target.value)}/></FormField><FormField label="Activation limit" required error={limitError}><TextInput aria-invalid={!!limitError} type="number" min="1" step="1" value={limit} onChange={(e)=>setLimit(e.target.value)}/></FormField></div><div className="modal-actions"><Button onClick={()=>setEditionModal(false)}>Cancel</Button><Button variant="primary" onClick={createEdition}>Create edition</Button></div></Modal></div>;
}
