import { useMemo, useState } from "react";
import { ArrowRight, FilePlus2, Plus, Target, UserCheck, UsersRound } from "lucide-react";
import { Button, Card, ConfirmDialog, DataTable, FormField, MetricCard, Modal, PageToolbar, SectionHeader, SelectInput, TextInput, type DataTableColumn } from "../../shared/components";
import { useToast } from "../../shared/feedback/ToastProvider";
import { firstError, validators } from "../../shared/validation";
import { digitalStore, type DigitalLead, type DigitalOpportunity, type DigitalProposal } from "../data/digitalStore";
import { DigitalStatus } from "../shared/DigitalStatus";
import { formatDate, formatLkr } from "../shared/format";
import { useDigitalStore } from "../shared/useDigitalStore";

type View = "leads" | "opportunities" | "proposals";

export function SalesPage() {
  const leads = useDigitalStore(digitalStore.getLeads); const opportunities = useDigitalStore(digitalStore.getOpportunities); const proposals = useDigitalStore(digitalStore.getProposals); const services = useDigitalStore(digitalStore.getServices); const { notify } = useToast();
  const [view, setView] = useState<View>("leads"); const [query, setQuery] = useState(""); const [leadModal, setLeadModal] = useState(false); const [proposalOpportunity, setProposalOpportunity] = useState<DigitalOpportunity | null>(null); const [accepting, setAccepting] = useState<DigitalProposal|null>(null); const [attemptedLead,setAttemptedLead]=useState(false); const [attemptedProposal,setAttemptedProposal]=useState(false);
  const [leadForm, setLeadForm] = useState({ name: "", company: "", email: "", phone: "", source: "Website", serviceId: services[0]?.id ?? "", estimatedValue: "180000", nextAction: "Initial response" }); const [proposalAmount, setProposalAmount] = useState("");
  const pipelineValue = opportunities.filter((item) => !["won", "lost"].includes(item.stage)).reduce((sum, item) => sum + item.value, 0); const sentValue = proposals.filter((item) => item.status === "sent").reduce((sum, item) => sum + item.amount, 0); const wonValue = opportunities.filter((item) => item.stage === "won").reduce((sum, item) => sum + item.value, 0);
  const filteredLeads = useMemo(() => leads.filter((item) => `${item.name} ${item.company} ${item.email}`.toLowerCase().includes(query.toLowerCase())), [leads, query]); const filteredOpportunities = useMemo(() => opportunities.filter((item) => `${item.name} ${item.company}`.toLowerCase().includes(query.toLowerCase())), [opportunities, query]); const filteredProposals = useMemo(() => proposals.filter((item) => `${item.number} ${item.title}`.toLowerCase().includes(query.toLowerCase())), [proposals, query]);
  const serviceName = (id?: string) => id ? services.find((service) => service.id === id)?.name ?? "Unknown service" : "Not specified";
  const leadNameError=attemptedLead?validators.required(leadForm.name,"Contact name"):""; const leadEmailError=attemptedLead?firstError(validators.required(leadForm.email,"Email"),leadForm.email.trim()?validators.email(leadForm.email):""):""; const leadServiceError=attemptedLead?validators.required(leadForm.serviceId,"Service"):""; const leadValueError=attemptedLead?validators.positive(leadForm.estimatedValue,"Estimated value"):""; const proposalAmountError=attemptedProposal?validators.positive(proposalAmount,"Proposal amount"):"";
  const qualify=(row:DigitalLead)=>{const opportunity=digitalStore.qualifyLead(row.id);notify({title:"Lead qualified",description:`${row.company||row.name} moved into the opportunity pipeline.`,tone:"success"});setView("opportunities");setQuery("");return opportunity;};
  const leadColumns: DataTableColumn<DigitalLead>[] = [
    { key: "lead", header: "Lead", render: (row) => <div className="entity-cell"><strong>{row.company || row.name}</strong><small>{row.name} · {row.email}</small></div> }, { key: "service", header: "Interest", render: (row) => <span className="muted-cell">{serviceName(row.serviceId)}</span> }, { key: "value", header: "Est. value", render: (row) => <strong>{formatLkr(row.estimatedValue)}</strong> }, { key: "source", header: "Source", render: (row) => <span className="muted-cell">{row.source}</span> }, { key: "status", header: "Status", render: (row) => <DigitalStatus value={row.status} /> }, { key: "action", header: "", width: "130px", render: (row) => row.status !== "qualified" && row.status !== "lost" ? <Button onClick={() => qualify(row)}>Qualify <ArrowRight size={13}/></Button> : <span className="muted-cell">{row.nextAction}</span> },
  ];
  const opportunityColumns: DataTableColumn<DigitalOpportunity>[] = [
    { key: "opportunity", header: "Opportunity", render: (row) => <div className="entity-cell"><strong>{row.name}</strong><small>{row.company}</small></div> }, { key: "value", header: "Value", render: (row) => <strong>{formatLkr(row.value)}</strong> }, { key: "stage", header: "Stage", render: (row) => <DigitalStatus value={row.stage} /> }, { key: "probability", header: "Probability", render: (row) => <span className="probability-cell"><i style={{ width: `${row.probability}%` }} />{row.probability}%</span> }, { key: "close", header: "Expected close", render: (row) => <span className="muted-cell">{formatDate(row.expectedCloseAt)}</span> }, { key: "action", header: "", width: "145px", render: (row) => ["won", "lost"].includes(row.stage) ? <span className="muted-cell">{row.nextAction}</span> : <Button onClick={() => { setProposalOpportunity(row); setProposalAmount(String(row.value)); setAttemptedProposal(false); }}><FilePlus2 size={13}/> Proposal</Button> },
  ];
  const proposalColumns: DataTableColumn<DigitalProposal>[] = [
    { key: "proposal", header: "Proposal", render: (row) => <div className="entity-cell"><strong>{row.number}</strong><small>{row.title}</small></div> }, { key: "service", header: "Service", render: (row) => <span className="muted-cell">{serviceName(row.serviceId)}</span> }, { key: "amount", header: "Amount", render: (row) => <strong>{formatLkr(row.amount)}</strong> }, { key: "status", header: "Status", render: (row) => <DigitalStatus value={row.status} /> }, { key: "valid", header: "Valid until", render: (row) => <span className="muted-cell">{formatDate(row.validUntil)}</span> }, { key: "action", header: "", width: "135px", render: (row) => row.status === "sent" ? <Button variant="primary" onClick={() => setAccepting(row)}><UserCheck size={13}/> Accept</Button> : <span className="muted-cell">Converted</span> },
  ];
  function createLead() { setAttemptedLead(true); if (leadNameError||leadEmailError||leadServiceError||leadValueError||!leadForm.name.trim()||!leadForm.email.trim()||!leadForm.serviceId) return; const lead=digitalStore.addLead({ ...leadForm, name: leadForm.name.trim(), company: leadForm.company.trim(), email: leadForm.email.trim(), phone: leadForm.phone.trim(), estimatedValue: Number(leadForm.estimatedValue) || 0 }); notify({title:"Lead created",description:`${lead.company||lead.name} was added to Sales.`,tone:"success"}); setLeadModal(false); setAttemptedLead(false); setLeadForm({ name: "", company: "", email: "", phone: "", source: "Website", serviceId: services[0]?.id ?? "", estimatedValue: "180000", nextAction: "Initial response" }); }
  function createProposal() { setAttemptedProposal(true); if (!proposalOpportunity||proposalAmountError) return; const proposal=digitalStore.createProposal(proposalOpportunity.id, { amount: Number(proposalAmount) || proposalOpportunity.value }); notify({title:"Proposal created",description:`${proposal.number} is now marked sent.`,tone:"success"}); setProposalOpportunity(null); setAttemptedProposal(false); setView("proposals"); }
  function acceptProposal(){if(!accepting)return;const result=digitalStore.acceptProposal(accepting.id);notify({title:"Proposal accepted",description:`${accepting.number} created ${result.client?.company||result.client?.name||"the client"}, an invoice and a planned project.`,tone:"success"});}
  return <div className="page">
    <SectionHeader eyebrow="NEXT F Digital" title="Sales" description="Move enquiries through a real service-sales pipeline and convert accepted work directly into operations." />
    <div className="compact-metrics digital-sales-metrics"><MetricCard label="Open pipeline" value={formatLkr(pipelineValue)} detail={`${opportunities.filter((item) => !["won", "lost"].includes(item.stage)).length} opportunities`} icon={Target} /><MetricCard label="New / contacted leads" value={String(leads.filter((item) => ["new", "contacted"].includes(item.status)).length)} detail="Need qualification" icon={UsersRound} /><MetricCard label="Proposals out" value={formatLkr(sentValue)} detail={`${proposals.filter((item) => item.status === "sent").length} awaiting decision`} icon={FilePlus2} /><MetricCard label="Won value" value={formatLkr(wonValue)} detail="Converted opportunities" icon={UserCheck} /></div>
    <Card><div className="segmented-nav" role="tablist"><button className={view === "leads" ? "is-active" : ""} onClick={() => { setView("leads"); setQuery(""); }}>Leads <span>{leads.length}</span></button><button className={view === "opportunities" ? "is-active" : ""} onClick={() => { setView("opportunities"); setQuery(""); }}>Opportunities <span>{opportunities.length}</span></button><button className={view === "proposals" ? "is-active" : ""} onClick={() => { setView("proposals"); setQuery(""); }}>Proposals <span>{proposals.length}</span></button></div><PageToolbar query={query} onQueryChange={setQuery} placeholder={`Search ${view}…`}>{view === "leads" && <Button variant="primary" onClick={() => {setAttemptedLead(false);setLeadModal(true);}}><Plus size={15}/> New lead</Button>}</PageToolbar>{view === "leads" && <DataTable rows={filteredLeads} columns={leadColumns} getKey={(row) => row.id} />}{view === "opportunities" && <DataTable rows={filteredOpportunities} columns={opportunityColumns} getKey={(row) => row.id} />}{view === "proposals" && <DataTable rows={filteredProposals} columns={proposalColumns} getKey={(row) => row.id} />}</Card>
    <Modal open={leadModal} title="Create lead" description="Capture enough information to qualify the enquiry without turning lead entry into a long form." onClose={() => setLeadModal(false)} footer={<><Button onClick={() => setLeadModal(false)}>Cancel</Button><Button variant="primary" onClick={createLead}>Create lead</Button></>}><div className="form-grid form-grid--two"><FormField label="Contact name" required error={leadNameError}><TextInput aria-invalid={!!leadNameError} value={leadForm.name} onChange={(e) => setLeadForm({ ...leadForm, name: e.target.value })} /></FormField><FormField label="Company"><TextInput value={leadForm.company} onChange={(e) => setLeadForm({ ...leadForm, company: e.target.value })} /></FormField><FormField label="Email" required error={leadEmailError}><TextInput aria-invalid={!!leadEmailError} type="email" value={leadForm.email} onChange={(e) => setLeadForm({ ...leadForm, email: e.target.value })} /></FormField><FormField label="Phone"><TextInput value={leadForm.phone} onChange={(e) => setLeadForm({ ...leadForm, phone: e.target.value })} /></FormField><FormField label="Interested service" required error={leadServiceError}><SelectInput aria-invalid={!!leadServiceError} value={leadForm.serviceId} onChange={(e) => setLeadForm({ ...leadForm, serviceId: e.target.value })}>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</SelectInput></FormField><FormField label="Estimated value (LKR)" required error={leadValueError}><TextInput aria-invalid={!!leadValueError} type="number" value={leadForm.estimatedValue} onChange={(e) => setLeadForm({ ...leadForm, estimatedValue: e.target.value })} /></FormField><FormField label="Source"><SelectInput value={leadForm.source} onChange={(e) => setLeadForm({ ...leadForm, source: e.target.value })}>{["Website","Email","Facebook","Instagram","WhatsApp","Referral","Organic","Paid Ads","Manual","Other"].map((source) => <option key={source}>{source}</option>)}</SelectInput></FormField><FormField label="Next action"><TextInput value={leadForm.nextAction} onChange={(e) => setLeadForm({ ...leadForm, nextAction: e.target.value })} /></FormField></div></Modal>
    <Modal open={Boolean(proposalOpportunity)} title="Create proposal" description={proposalOpportunity?.name} onClose={() => setProposalOpportunity(null)} footer={<><Button onClick={() => setProposalOpportunity(null)}>Cancel</Button><Button variant="primary" onClick={createProposal}>Create & send</Button></>}><div className="proposal-summary"><div><span>Client / company</span><strong>{proposalOpportunity?.company}</strong></div><div><span>Service</span><strong>{proposalOpportunity ? serviceName(proposalOpportunity.serviceId) : ""}</strong></div><div><span>Pipeline probability</span><strong>{proposalOpportunity?.probability}%</strong></div></div><FormField label="Proposal amount (LKR)" required error={proposalAmountError}><TextInput aria-invalid={!!proposalAmountError} type="number" value={proposalAmount} onChange={(e) => setProposalAmount(e.target.value)} /></FormField><p className="form-note">The proposal uses a 14-day validity period in local development. Production document delivery will be connected later.</p></Modal>
    <ConfirmDialog open={!!accepting} onClose={()=>setAccepting(null)} title="Accept proposal and create operations?" description={accepting?`${accepting.number} will create or link the client, issue an invoice, create a planned project and create recurring service data when the service requires it.`:""} confirmLabel="Accept & create operations" onConfirm={acceptProposal}/>
  </div>;
}
