import { useState } from "react";
import { ArchiveRestore, CloudCog, DatabaseBackup, HardDriveDownload, Trash2 } from "lucide-react";
import { Badge, Button, Card, ConfirmDialog, DataTable, MetricCard, SectionHeader, type DataTableColumn } from "../../shared/components";
import { platformOperationsStore, type BackupSnapshot } from "../services/platformOperationsStore";
import { usePlatformOperations } from "../shared/usePlatformOperations";
import { useToast } from "../../shared/feedback/ToastProvider";
import { readRuntimeTruth } from "../../services/production";

const runtime=readRuntimeTruth();

export function BackupPage(){
  const backups=usePlatformOperations(platformOperationsStore.getBackups);const [restore,setRestore]=useState<string|null>(null);const [remove,setRemove]=useState<string|null>(null);const {notify}=useToast();
  if(runtime.mode==="production-api") return <div className="page"><SectionHeader eyebrow="Platform" title="Backup & Recovery" description="Production recovery uses Cloudflare D1 Time Travel; browser restore is disabled."/><div className="compact-metrics"><MetricCard label="Recovery authority" value="D1" icon={CloudCog}/><MetricCard label="Browser restore" value="Disabled" icon={ArchiveRestore}/></div><Card className="architecture-callout"><div className="operation-section__head"><div><span>Production recovery</span><h3>Use D1 Time Travel</h3></div><Badge tone="success">Authoritative</Badge></div><p>Use D1 Time Travel for rollback and recovery. Data Management exports are for portability.</p></Card></div>;
  const columns:DataTableColumn<BackupSnapshot>[]=[{key:"name",header:"Snapshot",render:(r)=><div className="entity-cell"><strong>{r.name}</strong><small>{new Date(r.createdAt).toLocaleString("en-LK")}</small></div>},{key:"records",header:"Records",render:(r)=><strong>{r.records}</strong>},{key:"size",header:"Size",render:(r)=><span>{Math.max(1,Math.round(r.bytes/1024))} KB</span>},{key:"actions",header:"",render:(r)=><div className="table-actions"><Button onClick={()=>setRestore(r.id)}><ArchiveRestore size={14}/>Restore</Button><Button variant="ghost" onClick={()=>setRemove(r.id)}><Trash2 size={14}/></Button></div>}];
  return <div className="page"><SectionHeader eyebrow="Platform" title="Local Snapshot Management" description="Create and restore local development snapshots." action={<Button variant="primary" onClick={()=>{const b=platformOperationsStore.createBackup();notify({title:"Snapshot created",description:`${b.records} local records captured.`,tone:"success"});}}><DatabaseBackup size={15}/>Create snapshot</Button>}/><div className="compact-metrics"><MetricCard label="Snapshots" value={String(backups.length)} icon={DatabaseBackup}/><MetricCard label="Latest" value={backups[0]?new Date(backups[0].createdAt).toLocaleDateString("en-LK"):"None"} icon={HardDriveDownload}/></div><Card><DataTable rows={backups} columns={columns} getKey={(r)=>r.id} empty="No local snapshots yet."/></Card><ConfirmDialog open={!!restore} title="Restore this local snapshot?" description="Matching local CMS data will be overwritten by the selected snapshot." confirmLabel="Restore snapshot" danger onClose={()=>setRestore(null)} onConfirm={()=>{if(restore)platformOperationsStore.restoreBackup(restore);notify({title:"Snapshot restored",description:"Reload the CMS if a visible page does not refresh automatically.",tone:"success"});setRestore(null);}}/><ConfirmDialog open={!!remove} title="Delete snapshot?" description="This snapshot cannot be recovered after deletion." confirmLabel="Delete" danger onClose={()=>setRemove(null)} onConfirm={()=>{if(remove)platformOperationsStore.deleteBackup(remove);notify({title:"Snapshot deleted",tone:"success"});setRemove(null);}}/></div>;
}
