import { platformStore } from "../../platform/services/platformStore";
import { customerAccessStore } from "../../platform/customer-access/customerAccessStore";
import { digitalStore } from "../data/digitalStore";
import { websitePlatformStore } from "./websitePlatformStore";
import { workspaceProvisioningStore } from "./workspaceProvisioningStore";
import { readDurableValue, writeDurableValue } from "../../services/production/durableStorage";

export type OffboardingReason = "project_complete" | "service_ended" | "subscription_expired" | "customer_termination" | "nextf_termination" | "site_migration" | "other";
export type OffboardingPlanStatus = "draft" | "reviewed" | "in_progress" | "ready_to_close" | "completed" | "cancelled";
export type ExportStatus = "requested" | "preparing" | "ready" | "downloaded" | "expired" | "failed";
export type OwnershipKind = "customer" | "nextf" | "third_party" | "shared" | "unresolved";
export type PortabilityMode = "exportable" | "reference_only" | "not_exportable" | "contract_dependent";
export type ContractMigrationStatus = "draft" | "blocked" | "validated" | "scheduled" | "completed" | "cancelled";
export type AcceptanceGateStatus = "pending_external" | "source_passed" | "passed" | "failed" | "not_applicable";

export type OffboardingPlanRecord = {
  id:string; workspaceId:string; clientId:string; organizationId:string; reason:OffboardingReason; status:OffboardingPlanStatus;
  requestedBy:string; requestedAt:string; reviewedBy?:string; reviewedAt?:string; completedAt?:string; note:string;
  membershipIds:string[]; siteConnectionIds:string[]; projectIds:string[]; serviceIds:string[];
  overdueInvoiceIds:string[]; activeSubscriptionIds:string[];
  paymentRestrictionPolicy:"never_auto_shutdown_site";
  exportRequired:boolean; siteDisposition:"retain"|"suspend"|"revoke"|"transfer_pending"; workspaceDisposition:"read_only"|"suspend"|"close";
};
export type DataExportRequestRecord = { id:string; workspaceId:string; status:ExportStatus; requestedBy:string; requestedAt:string; preparedAt?:string; expiresAt?:string; manifest:{included:string[];excluded:string[]}; artifactReference?:string; checksum?:string };
export type AssetOwnershipRecord = { id:string; workspaceId:string; assetType:string; assetReference:string; owner:OwnershipKind; portability:PortabilityMode; basis:string; confirmedBy:string; confirmedAt:string };
export type ContractMigrationPlanRecord = { id:string; siteConnectionId:string; fromVersion:string; toVersion:string; status:ContractMigrationStatus; registrySnapshotId?:string; validationEvidenceId?:string; blockers:string[]; createdBy:string; createdAt:string; updatedAt:string };
export type ProductionAcceptanceEvidence = { gateId:string; status:AcceptanceGateStatus; evidence?:string; recordedBy?:string; recordedAt?:string };

const K={plans:"nextf.v0.22.website-platform.offboarding-plans",exports:"nextf.v0.22.website-platform.data-exports",ownership:"nextf.v0.22.website-platform.asset-ownership",migrations:"nextf.v0.22.website-platform.contract-migrations",acceptance:"nextf.v0.22.website-platform.production-acceptance"};
const read=<T>(key:string,seed:T):T=>readDurableValue(key,seed);
const write=<T>(key:string,value:T)=>{const result=writeDurableValue(key,value);window.dispatchEvent(new CustomEvent("nextf:website-platform",{detail:key}));return result;};
const uid=(prefix:string)=>`${prefix}_${crypto.randomUUID()}`;
const now=()=>new Date().toISOString();

export const PRODUCTION_ACCEPTANCE_GATES = [
  {id:"dependency_build",label:"Locked dependency install + TypeScript/Vite production build",critical:true,defaultStatus:"pending_external" as const},
  {id:"browser_smoke",label:"Desktop/tablet/mobile browser smoke + console review",critical:true,defaultStatus:"pending_external" as const},
  {id:"cloudflare_bindings",label:"Production Workers/D1/R2/Queues/Rate Limiter bindings deployed",critical:true,defaultStatus:"pending_external" as const},
  {id:"access_auth",label:"Cloudflare Access application + JWT audience + staff identity mapping validated",critical:true,defaultStatus:"pending_external" as const},
  {id:"d1_migrations",label:"Production D1 migrations applied and migration rollback procedure reviewed",critical:true,defaultStatus:"pending_external" as const},
  {id:"restore_drill",label:"D1 Time Travel/backup restore drill completed",critical:true,defaultStatus:"pending_external" as const},
  {id:"tenant_isolation",label:"Cross-organization/workspace authorization and tenancy penetration tests",critical:true,defaultStatus:"source_passed" as const},
  {id:"public_abuse",label:"nextf.lk rate limiting + Turnstile + idempotency verified in deployed environment",critical:true,defaultStatus:"pending_external" as const},
  {id:"contract_registry",label:"Authoritative Contracts Registry snapshot/API and real Site Manifest validation connected",critical:true,defaultStatus:"pending_external" as const},
  {id:"managed_site_adapter",label:"Real managed-site revision/apply/publish adapter credentials and receipts validated",critical:true,defaultStatus:"pending_external" as const},
  {id:"offboarding_e2e",label:"Production offboarding/export/revocation end-to-end acceptance",critical:true,defaultStatus:"pending_external" as const},
  {id:"demo_cleanup",label:"Demo expiry/reset/revocation scheduled cleanup acceptance",critical:true,defaultStatus:"source_passed" as const},
  {id:"audit_retention",label:"Audit/log retention and export/privacy review",critical:true,defaultStatus:"source_passed" as const},
] as const;

function currentAcceptance(){
  const stored=read<ProductionAcceptanceEvidence[]>(K.acceptance,[]); return PRODUCTION_ACCEPTANCE_GATES.map((gate)=>stored.find((row)=>row.gateId===gate.id)??{gateId:gate.id,status:gate.defaultStatus});
}

export const lifecycleGovernanceStore={
  getOffboardingPlans:()=>read<OffboardingPlanRecord[]>(K.plans,[]),
  getDataExports:()=>read<DataExportRequestRecord[]>(K.exports,[]),
  getAssetOwnership:()=>read<AssetOwnershipRecord[]>(K.ownership,[]),
  getContractMigrations:()=>read<ContractMigrationPlanRecord[]>(K.migrations,[]),
  getProductionAcceptance:currentAcceptance,
  getProductionAcceptanceSummary(){const rows=currentAcceptance();const criticalPending=rows.filter((row)=>PRODUCTION_ACCEPTANCE_GATES.find((gate)=>gate.id===row.gateId)?.critical&&!(["passed","not_applicable"] as AcceptanceGateStatus[]).includes(row.status));return{total:rows.length,passed:rows.filter((row)=>row.status==="passed").length,sourcePassed:rows.filter((row)=>row.status==="source_passed").length,pendingExternal:rows.filter((row)=>row.status==="pending_external").length,failed:rows.filter((row)=>row.status==="failed").length,productionReleaseAllowed:criticalPending.length===0,criticalPending:criticalPending.map((row)=>row.gateId)}} ,

  createOffboardingPlan(input:{workspaceId:string;reason:OffboardingReason;requestedBy:string;note:string;siteDisposition?:OffboardingPlanRecord["siteDisposition"];workspaceDisposition?:OffboardingPlanRecord["workspaceDisposition"]}){
    const workspace=websitePlatformStore.getWorkspaces().find((row)=>row.id===input.workspaceId); if(!workspace||workspace.status==="closed")throw new Error("An open Customer Workspace is required");
    const existing=this.getOffboardingPlans().find((row)=>row.workspaceId===workspace.id&&!['completed','cancelled'].includes(row.status)); if(existing)return existing;
    const attachments=workspaceProvisioningStore.getAttachments().filter((row)=>row.workspaceId===workspace.id); const memberships=customerAccessStore.getMemberships().filter((row)=>row.workspaceId===workspace.id&&row.status!=="revoked"); const sites=websitePlatformStore.getSiteConnections().filter((row)=>row.workspaceId===workspace.id&&row.status!=="revoked");
    const invoices=digitalStore.getInvoices().filter((row)=>row.clientId===workspace.clientId&&row.status==="overdue"); const subscriptions=digitalStore.getSubscriptions().filter((row)=>row.clientId===workspace.clientId&&["active","past_due","paused"].includes(row.status));
    const row:OffboardingPlanRecord={id:uid("offboarding"),workspaceId:workspace.id,clientId:workspace.clientId,organizationId:workspace.organizationId,reason:input.reason,status:"draft",requestedBy:input.requestedBy,requestedAt:now(),note:input.note.trim(),membershipIds:memberships.map((item)=>item.id),siteConnectionIds:sites.map((item)=>item.id),projectIds:attachments.filter((item)=>item.type==="project").map((item)=>item.resourceId),serviceIds:attachments.filter((item)=>item.type==="service").map((item)=>item.resourceId),overdueInvoiceIds:invoices.map((item)=>item.id),activeSubscriptionIds:subscriptions.map((item)=>item.id),paymentRestrictionPolicy:"never_auto_shutdown_site",exportRequired:true,siteDisposition:input.siteDisposition??"transfer_pending",workspaceDisposition:input.workspaceDisposition??"read_only"};
    write(K.plans,[row,...this.getOffboardingPlans()]); platformStore.addAudit("Admin","Customer Workspace offboarding plan created",workspace.name,"NEXT F Digital",`${row.reason}; payment state will never automatically shut down a managed site.`,"warning"); return row;
  },
  reviewOffboardingPlan(id:string,reviewerId:string){const target=this.getOffboardingPlans().find((row)=>row.id===id);if(!target||target.status!=="draft")throw new Error("Only draft offboarding plans can be reviewed");const updated={...target,status:"reviewed" as const,reviewedBy:reviewerId,reviewedAt:now()};write(K.plans,[updated,...this.getOffboardingPlans().filter((row)=>row.id!==id)]);return updated},
  startOffboarding(id:string,actorId:string){const target=this.getOffboardingPlans().find((row)=>row.id===id);if(!target||target.status!=="reviewed")throw new Error("Reviewed offboarding plan required");const workspace=websitePlatformStore.getWorkspaces().find((row)=>row.id===target.workspaceId);if(!workspace)throw new Error("Workspace not found");if(target.workspaceDisposition==="read_only"&&workspace.status==="active")websitePlatformStore.transitionWorkspace(workspace.id,"read_only",`Offboarding plan ${id} started by ${actorId}.`);if(target.workspaceDisposition==="suspend"&&["active","read_only"].includes(workspace.status))websitePlatformStore.transitionWorkspace(workspace.id,"suspended",`Offboarding plan ${id} started by ${actorId}.`);for(const membershipId of target.membershipIds)customerAccessStore.suspendMembership(membershipId);const updated={...target,status:"in_progress" as const};write(K.plans,[updated,...this.getOffboardingPlans().filter((row)=>row.id!==id)]);platformStore.addAudit("Admin","Customer Workspace offboarding started",workspace.name,"NEXT F Digital","Customer memberships suspended. Managed-site disposition remains an explicit separate action.","warning");return updated},
  applySiteDisposition(id:string,actorId:string){const target=this.getOffboardingPlans().find((row)=>row.id===id);if(!target||target.status!=="in_progress")throw new Error("Offboarding plan must be in progress");for(const connectionId of target.siteConnectionIds){const connection=websitePlatformStore.getSiteConnections().find((row)=>row.id===connectionId);if(!connection||connection.status==="revoked")continue;if(target.siteDisposition==="suspend"&&["connected","ready","incompatible"].includes(connection.status))websitePlatformStore.transitionSiteConnection(connection.id,"suspended",{});if(target.siteDisposition==="revoke")websitePlatformStore.transitionSiteConnection(connection.id,"revoked",{});}platformStore.addAudit("Admin","Managed-site offboarding disposition applied",target.workspaceId,"NEXT F Digital",`${target.siteDisposition}; actor ${actorId}. This was an explicit staff action, never an automatic billing shutdown.`,"warning");return target},
  requestDataExport(workspaceId:string,requestedBy:string){const workspace=websitePlatformStore.getWorkspaces().find((row)=>row.id===workspaceId);if(!workspace)throw new Error("Workspace not found");const row:DataExportRequestRecord={id:uid("export"),workspaceId,status:"requested",requestedBy,requestedAt:now(),manifest:{included:["customer-owned website content references","customer-visible project/deliverable records","contracts/invoices permitted by policy","customer-uploaded file metadata","customer-visible activity"],excluded:["staff notes","security logs","credentials/secrets","deployment internals","other customer data","internal cost/margin data"]}};write(K.exports,[row,...this.getDataExports()]);platformStore.addAudit("Admin","Customer data export requested",workspace.name,"NEXT F Digital","Export scope excludes internal/security/secrets and is subject to ownership/retention rules.","info");return row},
  markExportReady(id:string,artifactReference:string,checksum:string){if(!artifactReference||!checksum)throw new Error("Artifact reference and checksum are required");const target=this.getDataExports().find((row)=>row.id===id);if(!target||!["requested","preparing"].includes(target.status))throw new Error("Export is not awaiting preparation");const updated={...target,status:"ready" as const,preparedAt:now(),expiresAt:new Date(Date.now()+7*86400000).toISOString(),artifactReference,checksum};write(K.exports,[updated,...this.getDataExports().filter((row)=>row.id!==id)]);return updated},
  confirmAssetOwnership(input:{workspaceId:string;assetType:string;assetReference:string;owner:OwnershipKind;portability:PortabilityMode;basis:string;confirmedBy:string}){if(!input.basis.trim())throw new Error("Ownership basis is required; ownership must not be inferred from a technical connection");const row:AssetOwnershipRecord={id:uid("ownership"),...input,basis:input.basis.trim(),confirmedAt:now()};write(K.ownership,[row,...this.getAssetOwnership().filter((item)=>!(item.workspaceId===input.workspaceId&&item.assetType===input.assetType&&item.assetReference===input.assetReference))]);return row},
  createContractMigrationPlan(input:{siteConnectionId:string;toVersion:string;createdBy:string}){const connection=websitePlatformStore.getSiteConnections().find((row)=>row.id===input.siteConnectionId);if(!connection)throw new Error("Managed Site Connection not found");if(!input.toVersion.trim()||input.toVersion===connection.contractVersion)throw new Error("A different target contract version is required");const row:ContractMigrationPlanRecord={id:uid("contract_migration"),siteConnectionId:connection.id,fromVersion:connection.contractVersion,toVersion:input.toVersion.trim(),status:"blocked",blockers:["Trusted target Registry snapshot and official compatibility validation are required before scheduling."],createdBy:input.createdBy,createdAt:now(),updatedAt:now()};write(K.migrations,[row,...this.getContractMigrations()]);return row},
  recordAcceptanceEvidence(gateId:string,status:AcceptanceGateStatus,evidence:string,recordedBy:string){const gate=PRODUCTION_ACCEPTANCE_GATES.find((row)=>row.id===gateId);if(!gate)throw new Error("Unknown production acceptance gate");if(status==="passed"&&!evidence.trim())throw new Error("Passed production gates require concrete evidence");const row:ProductionAcceptanceEvidence={gateId,status,evidence:evidence.trim()||undefined,recordedBy,recordedAt:now()};write(K.acceptance,[row,...read<ProductionAcceptanceEvidence[]>(K.acceptance,[]).filter((item)=>item.gateId!==gateId)]);return row},
  completeOffboarding(id:string,actorId:string){const target=this.getOffboardingPlans().find((row)=>row.id===id);if(!target||target.status!=="in_progress")throw new Error("Offboarding plan must be in progress");const exportReady=this.getDataExports().some((row)=>row.workspaceId===target.workspaceId&&["ready","downloaded"].includes(row.status));if(target.exportRequired&&!exportReady)throw new Error("Required customer data export must be ready before workspace closure");for(const membershipId of target.membershipIds)customerAccessStore.revokeMembership(membershipId);const sites=websitePlatformStore.getSiteConnections().filter((row)=>target.siteConnectionIds.includes(row.id));if(sites.some((row)=>row.status!=="revoked")&&target.siteDisposition==="revoke")throw new Error("All managed Site Connections must be explicitly revoked before closure");const workspace=websitePlatformStore.getWorkspaces().find((row)=>row.id===target.workspaceId);if(!workspace)throw new Error("Workspace not found");if(workspace.status!=="closed")websitePlatformStore.transitionWorkspace(workspace.id,"closed",`Offboarding plan ${id} completed by ${actorId}.`);const updated={...target,status:"completed" as const,completedAt:now()};write(K.plans,[updated,...this.getOffboardingPlans().filter((row)=>row.id!==id)]);platformStore.addAudit("Admin","Customer Workspace offboarding completed",workspace.name,"NEXT F Digital","Memberships revoked and workspace closed after export/site disposition checks.","warning");return updated},
};
