import { useMemo, useState } from "react";
import { CircleDollarSign, KeyRound, Plus, ShoppingCart } from "lucide-react";
import { Button, Card, ConfirmDialog, DataTable, FormField, MetricCard, Modal, PageToolbar, SectionHeader, SelectInput, type DataTableColumn } from "../../shared/components";
import { useToast } from "../../shared/feedback/ToastProvider";
import { softwareStore, type SoftwareOrder } from "../data/softwareStore";
import { shortDate, usd } from "../shared/format";
import { SoftwareStatus } from "../shared/SoftwareStatus";
import { useSoftwareStore } from "../shared/useSoftwareStore";

export function OrdersPage(){
  const orders=useSoftwareStore(softwareStore.getOrders), customers=useSoftwareStore(softwareStore.getCustomers), products=useSoftwareStore(softwareStore.getProducts), editions=useSoftwareStore(softwareStore.getEditions), licenses=useSoftwareStore(softwareStore.getLicenses); const {notify}=useToast();
  const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [refund,setRefund]=useState<SoftwareOrder|null>(null); const [customerId,setCustomerId]=useState(customers[0]?.id??""); const [productId,setProductId]=useState(products[0]?.id??""); const compatible=editions.filter((e)=>e.productId===productId&&e.active); const [editionId,setEditionId]=useState(compatible[0]?.id??editions[0]?.id??"");
  const rows=useMemo(()=>orders.filter((o)=>`${o.number} ${customers.find((c)=>c.id===o.customerId)?.name} ${products.find((p)=>p.id===o.productId)?.name}`.toLowerCase().includes(query.toLowerCase())),[orders,customers,products,query]);
  const markPaid=(o:SoftwareOrder)=>{const updated=softwareStore.markOrderPaid(o.id);if(updated)notify({title:"Payment recorded",description:`${o.number} is paid and its license entitlement was issued.`,tone:"success"});};
  const completeRefund=()=>{if(!refund)return;softwareStore.refundOrder(refund.id);notify({title:"Software order refunded",description:`${refund.number} was refunded and its associated license was revoked.`,tone:"success"});};
  const cols:DataTableColumn<SoftwareOrder>[]=[{key:"order",header:"Order",render:(o)=><div className="entity-cell"><strong>{o.number}</strong><small>{customers.find((c)=>c.id===o.customerId)?.name} · {products.find((p)=>p.id===o.productId)?.name}</small></div>},{key:"edition",header:"Edition",render:(o)=><span>{editions.find((e)=>e.id===o.editionId)?.name}</span>},{key:"amount",header:"Amount",render:(o)=><strong>{usd(o.amount)}</strong>},{key:"status",header:"Status",render:(o)=><SoftwareStatus value={o.status}/>},{key:"date",header:"Created",render:(o)=><span>{shortDate(o.createdAt)}</span>},{key:"action",header:"",render:(o)=>o.status==="pending"?<Button variant="primary" onClick={()=>markPaid(o)}>Mark paid</Button>:o.status==="paid"?<Button className="button--danger" onClick={()=>setRefund(o)}>Refund</Button>:null}];
  const paid=orders.filter((o)=>o.status==="paid");
  const create=()=>{if(!customerId||!productId||!editionId){notify({title:"Order not created",description:"Select a customer, product and edition.",tone:"danger"});return;}const order=softwareStore.createOrder({customerId,productId,editionId});if(order){notify({title:"Software order created",description:`${order.number} is awaiting payment.`,tone:"success"});setOpen(false);}};
  return <div className="page"><SectionHeader eyebrow="NEXT F Software" title="Orders" description="Purchase records drive license issuance. Payment gateway integration is required before production payment capture." action={<Button variant="primary" onClick={()=>setOpen(true)}><Plus size={15}/> Order</Button>}/><div className="compact-metrics"><MetricCard label="Orders" value={String(orders.length)} detail={`${orders.filter((o)=>o.status==="pending").length} pending`} icon={ShoppingCart}/><MetricCard label="Paid revenue" value={usd(paid.reduce((s,o)=>s+o.amount,0))} detail="Recorded payments" icon={CircleDollarSign}/><MetricCard label="Licenses issued" value={String(licenses.length)} detail="Entitlements" icon={KeyRound}/></div><Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search software orders…"/><DataTable rows={rows} columns={cols} getKey={(o)=>o.id}/></Card><Modal open={open} onClose={()=>setOpen(false)} title="Create software order"><div className="form-grid"><FormField label="Customer" required><SelectInput value={customerId} onChange={(e)=>setCustomerId(e.target.value)}>{customers.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</SelectInput></FormField><FormField label="Product" required><SelectInput value={productId} onChange={(e)=>{const id=e.target.value;setProductId(id);setEditionId(editions.find((x)=>x.productId===id&&x.active)?.id??"");}}>{products.filter((p)=>p.status==="active").map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</SelectInput></FormField><FormField label="Edition" required><SelectInput value={editionId} onChange={(e)=>setEditionId(e.target.value)}>{editions.filter((e)=>e.productId===productId&&e.active).map((e)=><option key={e.id} value={e.id}>{e.name} · {usd(e.price)}</option>)}</SelectInput></FormField></div><div className="modal-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="primary" onClick={create}>Create order</Button></div></Modal><ConfirmDialog open={!!refund} onClose={()=>setRefund(null)} title="Refund software order?" description={refund?`${refund.number} will be marked refunded and the associated license entitlement will be revoked.`:""} confirmLabel="Refund and revoke" danger onConfirm={completeRefund}/></div>;
}
