import { useMemo, useState } from "react";
import { Bell, CheckCheck, CircleAlert, CircleCheck, ExternalLink, Info, TriangleAlert } from "lucide-react";
import { useSession } from "../../app/auth/SessionProvider";
import { useRouter } from "../../app/router/RouterProvider";
import { Badge, Button, Card, PageToolbar, SectionHeader } from "../../shared/components";
import type { PlatformNotification } from "../services/platformStore";
import { markAllOperationsNotifications, markOperationsNotification } from "../../services/shared/operationsCenter";
import { useOperationsCenter } from "../../services/shared/useOperationsCenter";
const iconFor=(item:PlatformNotification)=>item.tone==="danger"?<CircleAlert size={18}/>:item.tone==="warning"?<TriangleAlert size={18}/>:item.tone==="success"?<CircleCheck size={18}/>:<Info size={18}/>;
export function NotificationsPage(){const{user}=useSession();const{navigate}=useRouter();const items=useOperationsCenter();const[query,setQuery]=useState("");const filtered=useMemo(()=>items.filter((item)=>`${item.title} ${item.detail} ${item.domain}`.toLowerCase().includes(query.toLowerCase())),[items,query]);const unread=items.filter((item)=>!item.read).length;const openItem=(item:PlatformNotification)=>{markOperationsNotification(user.id,item.id,true);if(item.href)navigate(item.href);};return <div className="page"><SectionHeader eyebrow="Platform" title="Operations inbox" description="Operational alerts across Platform, Digital, Gaming and Software." action={<Button onClick={()=>markAllOperationsNotifications(user.id,items)} disabled={unread===0}><CheckCheck size={16}/>Mark all read</Button>}/><div className="compact-metrics"><Card><span><Bell size={17}/>Total</span><strong>{items.length}</strong></Card><Card><span><CircleAlert size={17}/>Unread</span><strong>{unread}</strong></Card><Card><span><TriangleAlert size={17}/>Warnings</span><strong>{items.filter((item)=>item.tone==="warning"||item.tone==="danger").length}</strong></Card><Card><span><CircleCheck size={17}/>Acknowledged</span><strong>{items.filter((item)=>item.read).length}</strong></Card></div><Card className="notification-card"><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search operational notifications"/><div className="notification-list">{filtered.length===0?<div className="command-empty">No notifications match this search.</div>:filtered.map((item)=><button key={item.id} className={`notification-row ${item.read?"is-read":""}`} onClick={()=>item.href?openItem(item):markOperationsNotification(user.id,item.id,!item.read)}><span className={`notification-row__icon notification-row__icon--${item.tone}`}>{iconFor(item)}</span><span className="notification-row__content"><span><strong>{item.title}</strong>{!item.read&&<i/>}</span><small>{item.detail}</small><em>{new Intl.DateTimeFormat("en-LK",{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.createdAt))}</em></span><span className="notification-row__meta"><Badge tone={item.id.startsWith("ops:")?"info":"neutral"}>{item.domain}</Badge>{item.href&&<ExternalLink size={14}/>}</span></button>)}</div></Card></div>;}
