import { useMemo, useState } from "react";
import { Activity, CircleGauge, Globe2, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { Button, Card, ConfirmDialog, FormField, MetricCard, Modal, PageToolbar, SectionHeader, SelectInput, TextInput } from "../../shared/components";
import { digitalStore, type DigitalSite } from "../data/digitalStore";
import { DigitalStatus } from "../shared/DigitalStatus";
import { formatDate } from "../shared/format";
import { useDigitalStore } from "../shared/useDigitalStore";
import { validators } from "../../shared/validation";
import { useToast } from "../../shared/feedback/ToastProvider";

const validDomain=(value:string)=>/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i.test(value.trim());

export function SitesPage() {
  const sites = useDigitalStore(digitalStore.getSites); const clients = useDigitalStore(digitalStore.getClients); const projects = useDigitalStore(digitalStore.getProjects); const {notify}=useToast();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [open, setOpen] = useState(false); const [attempted,setAttempted]=useState(false); const [maintenanceSite,setMaintenanceSite]=useState<DigitalSite|null>(null);
  const [form, setForm] = useState({ clientId: clients[0]?.id ?? "", projectId: "", name: "", domain: "", productionUrl: "", maintenancePlan: "Website Maintenance", domainExpiresAt: new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10) });
  const rows = useMemo(() => sites.filter((site) => { const client = clients.find((item) => item.id === site.clientId); const match = `${site.name} ${site.domain} ${client?.company ?? ""}`.toLowerCase().includes(query.toLowerCase()); return match && (filter === "all" || site.status === filter); }), [sites, clients, query, filter]);
  const clientError=attempted&&!form.clientId?"Select a client.":""; const nameError=attempted?validators.required(form.name,"Site name"):""; const domainError=attempted?(validators.required(form.domain,"Domain")||(!validDomain(form.domain)?"Enter a valid domain such as example.com.":"")):""; const urlError=attempted&&form.productionUrl.trim()?validators.url(form.productionUrl):""; const expiryError=attempted&&(!form.domainExpiresAt||Number.isNaN(new Date(form.domainExpiresAt).getTime()))?"Select a valid domain expiry date.":"";

  const submit = () => { setAttempted(true); if(clientError||nameError||domainError||urlError||expiryError||!form.clientId||!form.name.trim()||!validDomain(form.domain))return; const row=digitalStore.addSite({ clientId: form.clientId, projectId: form.projectId || undefined, name: form.name.trim(), domain: form.domain.trim().toLowerCase(), productionUrl: form.productionUrl.trim() || `https://${form.domain.trim().toLowerCase()}`, maintenancePlan: form.maintenancePlan, domainExpiresAt: new Date(form.domainExpiresAt).toISOString() }); notify({title:"Managed site added",description:`${row.domain} is now tracked in Client Sites.`,tone:"success"}); setOpen(false); setAttempted(false); };
  const toggleMaintenance=(site:DigitalSite)=>{const next=site.status==="maintenance"?"online":"maintenance";digitalStore.updateSite(site.id,{status:next});notify({title:next==="maintenance"?"Maintenance mode recorded":"Site returned online",description:site.domain,tone:"success"});setMaintenanceSite(null);};

  return <div className="page">
    <SectionHeader eyebrow="NEXT F Digital" title="Client Sites" description="Operate client websites after delivery: domain lifecycle, maintenance state, backups and local health checks in one operational workspace." action={<Button variant="primary" onClick={() => {setAttempted(false);setOpen(true);}}><Plus size={15}/> Add site</Button>} />
    <div className="compact-metrics"><MetricCard label="Managed sites" value={String(sites.length)} detail="Connected client properties" icon={Globe2} /><MetricCard label="Healthy" value={String(sites.filter((site) => site.status === "online").length)} detail="Currently online" icon={Activity} /><MetricCard label="Needs attention" value={String(sites.filter((site) => !["online", "maintenance"].includes(site.status)).length)} detail="Degraded or offline" icon={CircleGauge} /><MetricCard label="SSL valid" value={String(sites.filter((site) => site.sslStatus === "valid").length)} detail="Certificate state" icon={ShieldCheck} /></div>
    <Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search managed sites…"><SelectInput value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All health states</option><option value="online">Online</option><option value="degraded">Degraded</option><option value="offline">Offline</option><option value="maintenance">Maintenance</option></SelectInput></PageToolbar>
      <div className="site-grid">{rows.map((site) => { const client = clients.find((item) => item.id === site.clientId); return <article className="site-card" key={site.id}><header><div><span>{client?.company || client?.name}</span><h3>{site.name}</h3><a href={site.productionUrl} target="_blank" rel="noreferrer">{site.domain}</a></div><DigitalStatus value={site.status}/></header><div className="site-stats"><div><span>Response</span><strong>{site.responseMs ? `${site.responseMs} ms` : "No response"}</strong></div><div><span>SSL</span><DigitalStatus value={site.sslStatus}/></div><div><span>Domain expires</span><strong>{formatDate(site.domainExpiresAt)}</strong></div><div><span>Billing</span><DigitalStatus value={site.billingState}/></div></div><div className="site-meta"><span>Maintenance: <strong>{site.maintenancePlan}</strong></span><span>Last backup: <strong>{site.lastBackupAt ? formatDate(site.lastBackupAt) : "Not recorded"}</strong></span></div><footer><Button onClick={() => {digitalStore.runSiteCheck(site.id);notify({title:"Local site check complete",description:`${site.domain} health state was refreshed.`,tone:"success"});}}><RefreshCw size={14}/> Run check</Button><Button variant={site.status === "maintenance" ? "primary" : "secondary"} onClick={() => site.status==="maintenance"?toggleMaintenance(site):setMaintenanceSite(site)}>{site.status === "maintenance" ? "Return online" : "Maintenance mode"}</Button></footer></article>; })}</div>
    </Card>
    <Modal open={open} onClose={() => setOpen(false)} title="Add managed client site" description="Create the operational record now. Production hosting integrations will be connected later."><div className="form-grid"><FormField label="Client" required error={clientError}><SelectInput aria-invalid={!!clientError} value={form.clientId} onChange={(e) => setForm({...form, clientId:e.target.value})}>{clients.map((client) => <option key={client.id} value={client.id}>{client.company || client.name}</option>)}</SelectInput></FormField><FormField label="Project"><SelectInput value={form.projectId} onChange={(e) => setForm({...form, projectId:e.target.value})}><option value="">No linked project</option>{projects.filter((project) => project.clientId === form.clientId).map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</SelectInput></FormField><FormField label="Site name" required error={nameError}><TextInput aria-invalid={!!nameError} value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/></FormField><FormField label="Domain" required error={domainError}><TextInput aria-invalid={!!domainError} placeholder="example.com" value={form.domain} onChange={(e) => setForm({...form,domain:e.target.value})}/></FormField><FormField label="Production URL" error={urlError}><TextInput aria-invalid={!!urlError} placeholder="https://example.com" value={form.productionUrl} onChange={(e) => setForm({...form,productionUrl:e.target.value})}/></FormField><FormField label="Domain expiry" required error={expiryError}><TextInput aria-invalid={!!expiryError} type="date" value={form.domainExpiresAt} onChange={(e) => setForm({...form,domainExpiresAt:e.target.value})}/></FormField></div><div className="modal-actions"><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="primary" onClick={submit}>Add site</Button></div></Modal>
    <ConfirmDialog open={!!maintenanceSite} onClose={()=>setMaintenanceSite(null)} title="Record maintenance mode?" description={maintenanceSite?`${maintenanceSite.domain} will be marked in maintenance state. Production hosting control is not connected yet.`:""} confirmLabel="Enter maintenance" onConfirm={()=>maintenanceSite&&toggleMaintenance(maintenanceSite)}/>
  </div>;
}
