import {
  Activity,
  ArchiveRestore,
  BadgeDollarSign,
  Bell,
  Blocks,
  Boxes,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesCombined,
  CircleDollarSign,
  CloudCog,
  Code2,
  ContactRound,
  CreditCard,
  DatabaseBackup,
  FileArchive,
  FileCheck2,
  FileClock,
  Gauge,
  Globe2,
  Headphones,
  BookOpen,
  HeartPulse,
  KeyRound,
  LayoutDashboard,
  LifeBuoy,
  PackageCheck,
  PanelsTopLeft,
  ReceiptText,
  RefreshCw,
  Rocket,
  ScrollText,
  Settings2,
  ShieldCheck,
  ShieldAlert,
  Store,
  Trash2,
  Tags,
  UsersRound,
  UserRoundCheck,
  Workflow,
  Wrench,
} from "lucide-react";
import type { DomainDefinition } from "./types";

export const domains: DomainDefinition[] = [
  {
    id: "platform",
    label: "Platform",
    shortLabel: "Platform",
    description:
      "Shared administration, security, identity and system operations.",
    path: "/platform/dashboard",
    icon: ShieldCheck,
    navigation: [
      {
        label: "Dashboard",
        path: "/platform/dashboard",
        icon: LayoutDashboard,
        description: "Platform health and shared operations.",
      },
      {
        label: "Users",
        path: "/platform/users",
        icon: UsersRound,
        description: "Staff accounts and access state.",
      },
      {
        label: "NEXT F Accounts",
        path: "/platform/identity",
        icon: UserRoundCheck,
        description: "Canonical identity records separated from staff and customer authorization.",
      },
      {
        label: "Organizations",
        path: "/platform/organizations",
        icon: Building2,
        description: "Organizations, workspaces and operational boundaries.",
      },
      {
        label: "Domains",
        path: "/platform/domains",
        icon: Globe2,
        description: "Admin, business and managed-domain inventory.",
      },
      {
        label: "Shared Accounts",
        path: "/platform/accounts",
        icon: ContactRound,
        description:
          "Legacy cross-business customer profile aggregation; not authentication identity.",
      },
      {
        label: "Payments",
        path: "/platform/payments",
        icon: CircleDollarSign,
        description: "Shared Checkout providers, availability, transactions, webhooks and payment operations.",
      },
      {
        label: "Roles & Permissions",
        path: "/platform/access",
        icon: KeyRound,
        description: "Role and permission policy.",
      },
      {
        label: "Audit",
        path: "/platform/audit",
        icon: ScrollText,
        description: "Sensitive administrative activity.",
      },
      {
        label: "Notifications",
        path: "/platform/notifications",
        icon: Bell,
        description: "Cross-business admin notifications.",
      },
      {
        label: "Customer Help Center",
        path: "/platform/help-center",
        icon: BookOpen,
        description:
          "Knowledge, FAQs, announcements, customer requests, routing and feedback.",
      },
      {
        label: "Integrations",
        path: "/platform/integrations",
        icon: Blocks,
        description: "Shared external connections.",
      },
      {
        label: "Security",
        path: "/platform/security",
        icon: ShieldAlert,
        description: "Security policy, sessions and security events.",
      },
      {
        label: "System Logs",
        path: "/platform/logs",
        icon: FileClock,
        description: "Application and operational log history.",
      },
      {
        label: "Infrastructure",
        path: "/platform/infrastructure",
        icon: CloudCog,
        description: "Infrastructure adapter readiness.",
      },
      {
        label: "Health",
        path: "/platform/health",
        icon: HeartPulse,
        description: "System health and diagnostics.",
      },
      {
        label: "Acceptance",
        path: "/platform/acceptance",
        icon: FileCheck2,
        description: "Final CMS product and data-integrity completion gate.",
      },
      {
        label: "Backup",
        path: "/platform/backup",
        icon: ArchiveRestore,
        description: "Production recovery guidance and local-only snapshot tooling.",
      },
      {
        label: "Cleanup",
        path: "/platform/cleanup",
        icon: Trash2,
        description: "Retention policy and safe operational cleanup.",
      },
      {
        label: "Data Management",
        path: "/platform/data",
        icon: DatabaseBackup,
        description: "Controlled application-data export and maintenance safeguards.",
      },
      {
        label: "Settings",
        path: "/platform/settings",
        icon: Settings2,
        description: "Global organization settings.",
      },
    ],
  },
  {
    id: "next-f",
    label: "NEXT F Digital",
    shortLabel: "Digital",
    description: "Sell, deliver, bill, maintain and renew digital services.",
    path: "/next-f/dashboard",
    icon: BriefcaseBusiness,
    navigation: [
      {
        label: "Dashboard",
        path: "/next-f/dashboard",
        icon: LayoutDashboard,
        description: "Digital business operations overview.",
      },
      {
        label: "Sales",
        path: "/next-f/sales",
        icon: ChartNoAxesCombined,
        description: "Leads, opportunities, pipeline and proposals.",
      },
      {
        label: "Clients",
        path: "/next-f/clients",
        icon: ContactRound,
        description: "Client 360, contacts and Customer Workspace relationship.",
      },
      {
        label: "Services",
        path: "/next-f/services",
        icon: PanelsTopLeft,
        description: "Packages, custom services, pricing and templates.",
      },
      {
        label: "Projects",
        path: "/next-f/projects",
        icon: BriefcaseBusiness,
        description: "Projects, tasks, milestones and deliverables.",
      },
      {
        label: "Billing",
        path: "/next-f/billing",
        icon: ReceiptText,
        description: "Orders, invoices, payments and renewals.",
      },
      {
        label: "Client Sites",
        path: "/next-f/sites",
        icon: Activity,
        description: "Websites, deployments, domains and maintenance.",
      },
      {
        label: "Website Platform",
        path: "/next-f/website-platform",
        icon: Boxes,
        description: "Customer Workspace provisioning, managed-site connections, contracts and demo access.",
      },
      {
        label: "Support",
        path: "/next-f/support",
        icon: Headphones,
        description: "Tickets, service requests and issues.",
      },
      {
        label: "Automation",
        path: "/next-f/automation",
        icon: Workflow,
        description: "Business workflows and communication automation.",
      },
      {
        label: "Reports",
        path: "/next-f/reports",
        icon: Gauge,
        description: "Revenue, pipeline and delivery reporting.",
      },
      {
        label: "Settings",
        path: "/next-f/settings",
        icon: Settings2,
        description: "Digital business workflow defaults.",
      },
    ],
  },
  {
    id: "gaming-store",
    label: "Gaming Store",
    shortLabel: "Gaming",
    description:
      "Supplier-powered catalog, pricing, fulfillment and reconciliation.",
    path: "/gaming-store/dashboard",
    icon: Store,
    navigation: [
      {
        label: "Dashboard",
        path: "/gaming-store/dashboard",
        icon: LayoutDashboard,
        description: "Live commerce health, operational attention and supplier status.",
      },
      {
        label: "Live Operations",
        path: "/gaming-store/live-operations",
        icon: Activity,
        description: "Production orders, payments, fulfillment jobs and commerce events.",
      },
      {
        label: "Catalog",
        path: "/gaming-store/catalog",
        icon: Blocks,
        description: "NEXT F products, retail offers and canonical supplier routing.",
      },
      {
        label: "Storefront",
        path: "/gaming-store/storefront",
        icon: Store,
        description: "Homepage merchandising, game-family artwork and visual presentation.",
      },
      {
        label: "Pricing",
        path: "/gaming-store/pricing",
        icon: Tags,
        description: "Selling prices, margins and safeguards.",
      },
      {
        label: "Promotions",
        path: "/gaming-store/promotions",
        icon: BadgeDollarSign,
        description: "Coupons, campaigns, redemption limits and margin-safe discounts.",
      },
      {
        label: "Suppliers",
        path: "/gaming-store/suppliers",
        icon: Boxes,
        description: "Supplier connections, sync, balance and API health.",
      },
      {
        label: "Customers",
        path: "/gaming-store/customers",
        icon: UsersRound,
        description: "Customer 360, purchase history and marketing consent.",
      },
      {
        label: "Finance",
        path: "/gaming-store/finance",
        icon: CircleDollarSign,
        description: "Payments, costs, profit and reconciliation.",
      },
      {
        label: "Analytics",
        path: "/gaming-store/analytics",
        icon: ChartNoAxesCombined,
        description: "Commerce funnel, conversion, product and supplier performance.",
      },
      {
        label: "Support",
        path: "/gaming-store/support",
        icon: LifeBuoy,
        description: "Failed orders, issues and refunds.",
      },
    ],
  },
  {
    id: "software",
    label: "NEXT F Software",
    shortLabel: "Software",
    description: "Build, release, license, update and renew software products.",
    path: "/software/dashboard",
    icon: Code2,
    navigation: [
      {
        label: "Dashboard",
        path: "/software/dashboard",
        icon: LayoutDashboard,
        description: "Software revenue, releases and license health.",
      },
      {
        label: "Products",
        path: "/software/products",
        icon: Boxes,
        description: "Plugins, editions, add-ons and bundles.",
      },
      {
        label: "Releases",
        path: "/software/releases",
        icon: Rocket,
        description: "Versions, channels, changelogs and compatibility.",
      },
      {
        label: "Licenses",
        path: "/software/licenses",
        icon: KeyRound,
        description: "Licenses, activations, expirations and revocations.",
      },
      {
        label: "Customers",
        path: "/software/customers",
        icon: UsersRound,
        description: "Software customer accounts.",
      },
      {
        label: "Orders",
        path: "/software/orders",
        icon: CreditCard,
        description: "Software purchases and order records.",
      },
      {
        label: "Subscriptions",
        path: "/software/subscriptions",
        icon: RefreshCw,
        description: "Plans, renewals and expirations.",
      },
      {
        label: "Updates",
        path: "/software/updates",
        icon: PackageCheck,
        description: "Update entitlement and release rollout.",
      },
      {
        label: "Downloads",
        path: "/software/downloads",
        icon: FileArchive,
        description: "Secure software download records.",
      },
      {
        label: "Support",
        path: "/software/support",
        icon: Wrench,
        description: "Product support and customer issues.",
      },
      {
        label: "Analytics",
        path: "/software/analytics",
        icon: BadgeDollarSign,
        description: "Software growth and commercial performance.",
      },
      {
        label: "Settings",
        path: "/software/settings",
        icon: Settings2,
        description: "Software business settings.",
      },
    ],
  },
];

export const allNavigation = domains.flatMap((domain) =>
  domain.navigation.map((item) => ({ ...item, domain })),
);

export function getDomainByPath(pathname: string) {
  return (
    domains.find((domain) => pathname.startsWith(`/${domain.id}`)) ?? domains[1]
  );
}
