import { useMemo, useState } from "react";
import { KeyRound, MonitorCheck, ShieldBan } from "lucide-react";
import { Button, Card, ConfirmDialog, DataTable, FormField, MetricCard, Modal, PageToolbar, SectionHeader, TextInput, type DataTableColumn } from "../../shared/components";
import { useToast } from "../../shared/feedback/ToastProvider";
import { validators } from "../../shared/validation";
import { softwareStore, type SoftwareActivation, type SoftwareLicense } from "../data/softwareStore";
import { shortDate } from "../shared/format";
import { SoftwareStatus } from "../shared/SoftwareStatus";
import { useSoftwareStore } from "../shared/useSoftwareStore";

export function LicensesPage(){
  const licenses=useSoftwareStore(softwareStore.getLicenses), acts=useSoftwareStore(softwareStore.getActivations), products=useSoftwareStore(softwareStore.getProducts), customers=useSoftwareStore(softwareStore.getCustomers); const {notify}=useToast();
  const [query,setQuery]=useState(""); const [selectedId,setSelectedId]=useState<string|undefined>(undefined); const selected=licenses.find((l)=>l.id===selectedId); const [site,setSite]=useState(""); const [message,setMessage]=useState(""); const [attempted,setAttempted]=useState(false); const [revokeOpen,setRevokeOpen]=useState(false); const [deactivate,setDeactivate]=useState<SoftwareActivation|null>(null);
  const rows=useMemo(()=>licenses.filter((l)=>`${l.key} ${customers.find((c)=>c.id===l.customerId)?.name} ${products.find((p)=>p.id===l.productId)?.name}`.toLowerCase().includes(query.toLowerCase())),[licenses,customers,products,query]); const siteError=attempted&&site?validators.url(site):attempted?validators.required(site,"Site URL"):"";
  const activate=()=>{if(!selected)return;setAttempted(true);if(siteError||!site)return;const result=softwareStore.addActivation(selected.id,site);setMessage(result?.ok?"Activation created.":result?.reason??"Unable to activate.");if(result?.ok){notify({title:"Site activated",description:`${site} now uses ${selected.key}.`,tone:"success"});setSite("");setAttempted(false);}else notify({title:"Activation blocked",description:result?.reason??"Unable to activate.",tone:"danger"});};
  const toggleLicense=()=>{if(!selected)return;const next=selected.status==="revoked"?"active":"revoked";softwareStore.updateLicense(selected.id,{status:next});notify({title:next==="active"?"License restored":"License revoked",description:selected.key,tone:next==="active"?"success":"info"});};
  const doDeactivate=()=>{if(!deactivate)return;softwareStore.deactivateActivation(deactivate.id);notify({title:"Activation deactivated",description:deactivate.siteUrl,tone:"success"});};
  const cols:DataTableColumn<SoftwareLicense>[]=[{key:"license",header:"License",render:(l)=><div className="entity-cell"><strong>{l.key}</strong><small>{products.find((p)=>p.id===l.productId)?.name} · {customers.find((c)=>c.id===l.customerId)?.name}</small></div>},{key:"use",header:"Activations",render:(l)=>{const n=acts.filter((a)=>a.licenseId===l.id&&a.status==="active").length;return <strong>{n} / {l.activationLimit}</strong>}},{key:"status",header:"Status",render:(l)=><SoftwareStatus value={l.status}/>},{key:"expiry",header:"Expires",render:(l)=><span>{shortDate(l.expiresAt)}</span>},{key:"action",header:"",render:(l)=><Button onClick={()=>{setSelectedId(l.id);setMessage("");setAttempted(false);}}>Manage</Button>}];
  const acols:DataTableColumn<SoftwareActivation>[]=[{key:"site",header:"Site",render:(a)=><div className="entity-cell"><strong>{a.siteUrl}</strong><small>{a.fingerprint}</small></div>},{key:"status",header:"Status",render:(a)=><SoftwareStatus value={a.status}/>},{key:"last",header:"Last seen",render:(a)=><span>{shortDate(a.lastSeenAt)}</span>},{key:"action",header:"",render:(a)=>a.status==="active"?<Button className="button--danger" onClick={()=>setDeactivate(a)}>Deactivate</Button>:null}];
  return <div className="page"><SectionHeader eyebrow="NEXT F Software" title="Licenses & Activations" description="License entitlement, seat limits and active installations."/><div className="compact-metrics"><MetricCard label="Active licenses" value={String(licenses.filter((l)=>l.status==="active").length)} icon={KeyRound}/><MetricCard label="Active sites" value={String(acts.filter((a)=>a.status==="active").length)} icon={MonitorCheck}/><MetricCard label="Restricted" value={String(licenses.filter((l)=>["suspended","revoked","expired"].includes(l.status)).length)} icon={ShieldBan}/></div><Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search licenses…"/><DataTable rows={rows} columns={cols} getKey={(l)=>l.id}/></Card><Modal open={!!selected} onClose={()=>setSelectedId(undefined)} title="Manage license" description={selected?.key}>{selected&&<><div className="form-grid"><FormField label="Add activation" required error={siteError}><TextInput aria-invalid={!!siteError} placeholder="https://customer-site.com" value={site} onChange={(e)=>setSite(e.target.value)}/></FormField>{message&&<small>{message}</small>}</div><div className="modal-actions"><Button className={selected.status==="revoked"?"":"button--danger"} onClick={()=>selected.status==="revoked"?toggleLicense():setRevokeOpen(true)}>{selected.status==="revoked"?"Restore":"Revoke license"}</Button><Button variant="primary" onClick={activate}>Activate site</Button></div><Card><DataTable rows={acts.filter((a)=>a.licenseId===selected.id)} columns={acols} getKey={(a)=>a.id} empty="No activations yet."/></Card></>}</Modal><ConfirmDialog open={revokeOpen} onClose={()=>setRevokeOpen(false)} title="Revoke software license?" description={selected?`${selected.key} will lose normal update, download and activation entitlement until restored.`:""} confirmLabel="Revoke license" danger onConfirm={toggleLicense}/><ConfirmDialog open={!!deactivate} onClose={()=>setDeactivate(null)} title="Deactivate site?" description={deactivate?`${deactivate.siteUrl} will no longer count as an active installation for this license.`:""} confirmLabel="Deactivate site" danger onConfirm={doDeactivate}/></div>;
}
