import { platformStore } from "./platformStore";

export type OrganizationRecord={id:string;name:string;slug:string;status:"active"|"archived";createdAt:string};
export type WorkspaceRecord={id:string;organizationId:string;name:string;key:string;domains:Array<"platform"|"next-f"|"gaming-store"|"software">;status:"active"|"archived";createdAt:string};
export type DomainRecord={id:string;hostname:string;purpose:"admin"|"digital"|"gaming"|"software"|"client-site";workspaceId:string;status:"active"|"pending"|"disabled";ssl:"valid"|"pending"|"issue";expiresAt?:string;notes:string;createdAt:string;updatedAt:string};
export type SecurityPolicy={id:string;name:string;description:string;enabled:boolean;severity:"recommended"|"required";updatedAt:string};
export type SecuritySession={id:string;userId:string;device:string;location:string;lastSeenAt:string;status:"active"|"revoked"};
export type SecurityEvent={id:string;title:string;detail:string;tone:"info"|"warning"|"danger";createdAt:string};
export type SystemLog={id:string;level:"info"|"warning"|"error";source:string;message:string;context:string;createdAt:string};
export type BackupSnapshot={id:string;name:string;records:number;bytes:number;createdAt:string;payload:Record<string,string>};
export type RetentionPolicy={auditDays:number;logDays:number;notificationDays:number;backupCount:number};
export type CleanupRun={id:string;removedAudit:number;removedLogs:number;removedNotifications:number;removedBackups:number;createdAt:string;mode:"preview"|"executed"};

const K={orgs:"nextf.v0.10.platform.organizations",workspaces:"nextf.v0.10.platform.workspaces",domains:"nextf.v0.10.platform.domains",policies:"nextf.v0.10.platform.security-policies",sessions:"nextf.v0.10.platform.security-sessions",securityEvents:"nextf.v0.10.platform.security-events",logs:"nextf.v0.10.platform.logs",backups:"nextf.v0.10.platform.backups",retention:"nextf.v0.10.platform.retention",cleanup:"nextf.v0.10.platform.cleanup-runs"};
const now=Date.now(); const ago=(h:number)=>new Date(now-h*3600000).toISOString(); const ahead=(d:number)=>new Date(now+d*86400000).toISOString();
const orgSeed:OrganizationRecord[]=[{id:"org_nextf",name:"NEXT F",slug:"next-f",status:"active",createdAt:ago(9000)}];
const workspaceSeed:WorkspaceRecord[]=[{id:"ws_main",organizationId:"org_nextf",name:"NEXT F Business Platform",key:"main",domains:["platform","next-f","gaming-store","software"],status:"active",createdAt:ago(8000)}];
const domainSeed:DomainRecord[]=[{id:"dom_admin",hostname:"cms.nextf.local",purpose:"admin",workspaceId:"ws_main",status:"active",ssl:"valid",expiresAt:ahead(365),notes:"Local development admin hostname placeholder.",createdAt:ago(7000),updatedAt:ago(3)},{id:"dom_main",hostname:"nextf.com.lk",purpose:"digital",workspaceId:"ws_main",status:"active",ssl:"valid",expiresAt:ahead(210),notes:"NEXT F public business domain reference.",createdAt:ago(7000),updatedAt:ago(20)},{id:"dom_gaming",hostname:"nextfgamingstore.web.lk",purpose:"gaming",workspaceId:"ws_main",status:"active",ssl:"valid",expiresAt:ahead(190),notes:"Gaming Store public domain reference.",createdAt:ago(7000),updatedAt:ago(20)}];
const policySeed:SecurityPolicy[]=[{id:"sec_mfa",name:"Administrator MFA",description:"Require multi-factor authentication for privileged production accounts.",enabled:true,severity:"required",updatedAt:ago(5)},{id:"sec_session",name:"Session timeout",description:"Enforce bounded administrative sessions and revoke stale sessions.",enabled:true,severity:"required",updatedAt:ago(5)},{id:"sec_audit",name:"Sensitive action auditing",description:"Record access, finance, refund, release and configuration changes.",enabled:true,severity:"required",updatedAt:ago(5)},{id:"sec_export",name:"Protected data exports",description:"Treat business data exports as privileged administrative actions.",enabled:true,severity:"recommended",updatedAt:ago(5)}];
const sessionSeed:SecuritySession[]=[{id:"sess_local",userId:"usr_admin",device:"Local development browser",location:"Local session",lastSeenAt:ago(.05),status:"active"}];
const securityEventSeed:SecurityEvent[]=[{id:"se_1",title:"Production identity provider deferred",detail:"Local session provider is intentionally active until infrastructure integration.",tone:"info",createdAt:ago(4)}];
const logSeed:SystemLog[]=[{id:"log_1",level:"info",source:"application",message:"CMS product acceptance initialized",context:"V0.10 architecture-complete product layer",createdAt:ago(3)},{id:"log_2",level:"info",source:"repository",message:"Browser persistence adapter healthy",context:"localStorage",createdAt:ago(2)},{id:"log_3",level:"warning",source:"infrastructure",message:"Production adapters are not connected",context:"Expected before final deployment stage",createdAt:ago(1)}];
const retentionSeed:RetentionPolicy={auditDays:365,logDays:90,notificationDays:90,backupCount:10};
function read<T>(key:string,seed:T):T{if(typeof window==="undefined")return seed;try{const raw=window.localStorage.getItem(key);if(!raw){window.localStorage.setItem(key,JSON.stringify(seed));return seed;}return JSON.parse(raw) as T;}catch{return seed;}}
function write<T>(key:string,value:T){window.localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new CustomEvent("nextf:platform-operations",{detail:key}));return value;}
function uid(prefix:string){return `${prefix}_${crypto.randomUUID()}`;}
function log(level:SystemLog["level"],source:string,message:string,context=""){const rows=read(K.logs,logSeed);const row:SystemLog={id:uid("log"),level,source,message,context,createdAt:new Date().toISOString()};write(K.logs,[row,...rows].slice(0,500));return row;}
function collectNextfStorage(){const payload:Record<string,string>={};for(let i=0;i<window.localStorage.length;i++){const key=window.localStorage.key(i);if(key?.startsWith("nextf.")){const value=window.localStorage.getItem(key);if(value!==null)payload[key]=value;}}return payload;}

export const platformOperationsStore={
 getOrganizations:()=>read(K.orgs,orgSeed),getWorkspaces:()=>read(K.workspaces,workspaceSeed),getDomains:()=>read(K.domains,domainSeed),getSecurityPolicies:()=>read(K.policies,policySeed),getSecuritySessions:()=>read(K.sessions,sessionSeed),getSecurityEvents:()=>read(K.securityEvents,securityEventSeed),getLogs:()=>read(K.logs,logSeed),getBackups:()=>read<BackupSnapshot[]>(K.backups,[]),getRetention:()=>read(K.retention,retentionSeed),getCleanupRuns:()=>read<CleanupRun[]>(K.cleanup,[]),
 addOrganization(name:string,slug:string){const row:OrganizationRecord={id:uid("org"),name,slug,status:"active",createdAt:new Date().toISOString()};write(K.orgs,[row,...this.getOrganizations()]);platformStore.addAudit("Admin","Organization created",name,"Platform",`Organization ${slug} added.`,"info");log("info","organizations","Organization created",name);return row;},
 addWorkspace(organizationId:string,name:string,key:string){const row:WorkspaceRecord={id:uid("ws"),organizationId,name,key,domains:["platform"],status:"active",createdAt:new Date().toISOString()};write(K.workspaces,[row,...this.getWorkspaces()]);platformStore.addAudit("Admin","Workspace created",name,"Platform",`Workspace ${key} added.`,"info");return row;},
 updateWorkspace(id:string,patch:Partial<WorkspaceRecord>){const rows=this.getWorkspaces().map((r)=>r.id===id?{...r,...patch}:r);write(K.workspaces,rows);return rows.find((r)=>r.id===id);},
 addDomain(input:Pick<DomainRecord,"hostname"|"purpose"|"workspaceId"|"notes">){const row:DomainRecord={...input,id:uid("domain"),status:"pending",ssl:"pending",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};write(K.domains,[row,...this.getDomains()]);platformStore.addAudit("Admin","Domain registered",row.hostname,"Platform",`Domain purpose: ${row.purpose}.`,"info");return row;},
 updateDomain(id:string,patch:Partial<DomainRecord>){const rows=this.getDomains().map((r)=>r.id===id?{...r,...patch,updatedAt:new Date().toISOString()}:r);write(K.domains,rows);return rows.find((r)=>r.id===id);},
 updateSecurityPolicy(id:string,enabled:boolean){const rows=this.getSecurityPolicies().map((r)=>r.id===id?{...r,enabled,updatedAt:new Date().toISOString()}:r);write(K.policies,rows);platformStore.addAudit("Admin","Security policy updated",id,"Platform",enabled?"Policy enabled.":"Policy disabled.",enabled?"info":"warning");return rows.find((r)=>r.id===id);},
 revokeSession(id:string){const rows=this.getSecuritySessions().map((r)=>r.id===id?{...r,status:"revoked" as const}:r);write(K.sessions,rows);platformStore.addAudit("Admin","Admin session revoked",id,"Platform","Administrative session was revoked locally.","warning");return rows.find((r)=>r.id===id);},
 addLog:(level:SystemLog["level"],source:string,message:string,context="")=>log(level,source,message,context),
 createBackup(name=`Manual snapshot ${new Date().toLocaleString("en-LK")}`){const payload=collectNextfStorage();const json=JSON.stringify(payload);const row:BackupSnapshot={id:uid("backup"),name,records:Object.keys(payload).length,bytes:new Blob([json]).size,createdAt:new Date().toISOString(),payload};const policy=this.getRetention();const rows=[row,...this.getBackups()].slice(0,Math.max(1,policy.backupCount));write(K.backups,rows);platformStore.addAudit("Admin","Local backup created",row.name,"Platform",`${row.records} local records captured.`,"info");log("info","backup","Local snapshot created",row.name);return row;},
 restoreBackup(id:string){const snapshot=this.getBackups().find((r)=>r.id===id);if(!snapshot)throw new Error("Backup not found");Object.entries(snapshot.payload).forEach(([key,value])=>{if(key.startsWith("nextf."))window.localStorage.setItem(key,value);});window.dispatchEvent(new CustomEvent("nextf:platform-operations",{detail:"restore"}));platformStore.addAudit("Admin","Local backup restored",snapshot.name,"Platform",`${snapshot.records} local records restored.`,"warning");return snapshot;},
 deleteBackup(id:string){const target=this.getBackups().find((r)=>r.id===id);write(K.backups,this.getBackups().filter((r)=>r.id!==id));if(target)platformStore.addAudit("Admin","Local backup deleted",target.name,"Platform","Backup snapshot removed.","warning");},
 saveRetention(policy:RetentionPolicy){write(K.retention,policy);platformStore.addAudit("Admin","Retention policy updated","Platform retention","Local retention thresholds changed.","info");return policy;},
 previewCleanup(){const policy=this.getRetention();const now=Date.now();const auditCutoff=now-policy.auditDays*86400000;const logCutoff=now-policy.logDays*86400000;const notificationCutoff=now-policy.notificationDays*86400000;const removedAudit=platformStore.getAudit().filter((r)=>new Date(r.timestamp).getTime()<auditCutoff).length;const removedLogs=this.getLogs().filter((r)=>new Date(r.createdAt).getTime()<logCutoff).length;const removedNotifications=platformStore.getNotifications().filter((r)=>new Date(r.createdAt).getTime()<notificationCutoff).length;const removedBackups=Math.max(0,this.getBackups().length-policy.backupCount);const row:CleanupRun={id:uid("cleanup"),removedAudit,removedLogs,removedNotifications,removedBackups,createdAt:new Date().toISOString(),mode:"preview"};write(K.cleanup,[row,...this.getCleanupRuns()].slice(0,50));return row;},
 runCleanup(){const policy=this.getRetention();const now=Date.now();const auditCutoff=now-policy.auditDays*86400000;const logCutoff=now-policy.logDays*86400000;const notificationCutoff=now-policy.notificationDays*86400000;const audits=platformStore.getAudit();const logs=this.getLogs();const notifications=platformStore.getNotifications();const backups=this.getBackups();const keptAudit=audits.filter((r)=>new Date(r.timestamp).getTime()>=auditCutoff);const keptLogs=logs.filter((r)=>new Date(r.createdAt).getTime()>=logCutoff);const keptNotifications=notifications.filter((r)=>new Date(r.createdAt).getTime()>=notificationCutoff);const keptBackups=backups.slice(0,policy.backupCount);platformStore.saveAudit(keptAudit);write(K.logs,keptLogs);platformStore.saveNotifications(keptNotifications);write(K.backups,keptBackups);const row:CleanupRun={id:uid("cleanup"),removedAudit:audits.length-keptAudit.length,removedLogs:logs.length-keptLogs.length,removedNotifications:notifications.length-keptNotifications.length,removedBackups:backups.length-keptBackups.length,createdAt:new Date().toISOString(),mode:"executed"};write(K.cleanup,[row,...this.getCleanupRuns()].slice(0,50));platformStore.addAudit("Admin","Cleanup executed","Platform retention",`${row.removedAudit} audit, ${row.removedLogs} logs, ${row.removedNotifications} notifications and ${row.removedBackups} backups removed.`,"warning");return row;},
};
