import { useMemo, useState } from "react";
import { ArrowUpDown, Boxes, Eye, Link2, RefreshCw, RotateCcw, Store, Waypoints } from "lucide-react";
import { Badge, Button, Card, DataTable, FormField, MetricCard, Modal, SectionHeader, SelectInput, TextInput, Toggle, type DataTableColumn } from "../../../shared/components";
import { gamingStore } from "../../data/gamingStore";
import type { NextFGamingOffer, NextFGamingProduct, SupplierOfferMapping } from "../types";
import { gamingVNextStore } from "../runtime/store";
import { useVNextStore } from "../runtime/useVNextStore";
import { buildGamingQuote } from "../runtime/pricingEngine";
import { chooseSupplierMapping } from "../runtime/supplierRouter";
import { readExternalCapability, readRuntimeTruth } from "../../../services/production";

const runtime=readRuntimeTruth();
const storefrontCapability=readExternalCapability("gaming.public-storefront");

const lkr = (value?: number) => value == null ? "Live quote" : new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR", maximumFractionDigits: 0 }).format(value);
const money = (value: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 4 }).format(value);
const kindLabel = (kind: string) => kind.replaceAll("_", " ").replace(/\b\w/g, (m) => m.toUpperCase());

export function CatalogVNextPage() {
  const products = useVNextStore(gamingVNextStore.getProducts); const offers = useVNextStore(gamingVNextStore.getOffers); const mappings = useVNextStore(gamingVNextStore.getMappings); const suppliers = gamingStore.getSuppliers();
  const [tab, setTab] = useState<"products"|"offers"|"routing">("products"); const [selectedProduct, setSelectedProduct] = useState<NextFGamingProduct>(); const [selectedOffer, setSelectedOffer] = useState<NextFGamingOffer>(); const [selectedMapping, setSelectedMapping] = useState<SupplierOfferMapping>();
  const activeMappings = mappings.filter((m)=>m.enabled && m.availability.state==="available");
  const previewHref = "/gaming";
  const productCols: DataTableColumn<NextFGamingProduct>[] = [
    { key:"product", header:"NEXT F product", render:(p)=><div className="entity-cell"><strong>{p.name}</strong><small>/{p.slug} · {kindLabel(p.kind)}</small></div> },
    { key:"offers", header:"Offers", render:(p)=><strong>{offers.filter((o)=>o.productId===p.id).length}</strong> },
    { key:"featured", header:"Featured", render:(p)=><Toggle checked={p.featured} onChange={(featured)=>gamingVNextStore.updateProduct(p.id,{featured})}/> },
    { key:"enabled", header:"Public", render:(p)=><Toggle checked={p.enabled} onChange={(enabled)=>gamingVNextStore.updateProduct(p.id,{enabled})}/> },
    { key:"action", header:"", width:"90px", render:(p)=><Button onClick={()=>setSelectedProduct(p)}>Edit</Button> },
  ];
  const offerCols: DataTableColumn<NextFGamingOffer>[] = [
    { key:"offer", header:"Retail offer", render:(o)=>{const p=products.find((x)=>x.id===o.productId);return <div className="entity-cell"><strong>{p?.name} · {o.name}</strong><small>{kindLabel(o.kind)} · {o.purchaseFields.length} customer fields</small></div>} },
    { key:"price", header:"Retail price", render:(o)=><div className="entity-cell"><strong>{lkr(o.sellingPriceLkr)}</strong><small>{o.pricingMode.replaceAll("_"," ")}</small></div> },
    { key:"validation", header:"Validation", render:(o)=><Badge tone={o.validation.supported?"success":"neutral"}>{o.validation.supported?"Preflight":"Not required"}</Badge> },
    { key:"routes", header:"Supplier routes", render:(o)=><strong>{mappings.filter((m)=>m.offerId===o.id).length}</strong> },
    { key:"enabled", header:"Public", render:(o)=><Toggle checked={o.enabled} onChange={(enabled)=>gamingVNextStore.updateOffer(o.id,{enabled})}/> },
    { key:"action", header:"", width:"90px", render:(o)=><Button onClick={()=>setSelectedOffer(o)}>Edit</Button> },
  ];
  const mappingCols: DataTableColumn<SupplierOfferMapping>[] = [
    { key:"route", header:"Offer / supplier", render:(m)=>{const o=offers.find((x)=>x.id===m.offerId);const p=products.find((x)=>x.id===o?.productId);const s=suppliers.find((x)=>x.id===m.supplierId);return <div className="entity-cell"><strong>{p?.name} · {o?.name}</strong><small>{s?.name ?? m.supplierId} · {m.externalOfferId ?? m.externalProductId ?? "dynamic"}</small></div>} },
    { key:"priority", header:"Priority", render:(m)=><Badge tone={m.priority===1?"info":"neutral"}>#{m.priority}</Badge> },
    { key:"cost", header:"Supplier cost", render:(m)=><div className="entity-cell"><strong>{money(m.supplierCost,m.supplierCurrency)}</strong><small>{m.availability.stock == null?"Live availability":`${m.availability.stock} stock`}</small></div> },
    { key:"availability", header:"Availability", render:(m)=><Badge tone={m.availability.state==="available"?"success":m.availability.state==="unknown"?"warning":"danger"}>{m.availability.state}</Badge> },
    { key:"enabled", header:"Route", render:(m)=><Toggle checked={m.enabled} onChange={(enabled)=>gamingVNextStore.updateMapping(m.id,{enabled})}/> },
    { key:"action", header:"", width:"90px", render:(m)=><Button onClick={()=>setSelectedMapping(m)}>Edit</Button> },
  ];
  const estimated = useMemo(()=>offers.filter((o)=>o.enabled).map((offer)=>{const mapping=chooseSupplierMapping(offer,mappings); return mapping ? buildGamingQuote({offer,mapping,quantity:1,requestedAmount:offer.pricingMode==="amount_based"?offer.minAmount:undefined}) : undefined;}).filter(Boolean),[offers,mappings]);
  return <div className="page"><SectionHeader eyebrow="Gaming Store vNext" title="Digital Catalog & Supplier Routing" description="Control NEXT F retail products independently from supplier offers. Supplier APIs provide supply facts; this CMS controls the public merchandising, retail price, validation flow and routing priority." action={<Button variant="primary" disabled={!storefrontCapability.available} onClick={()=>storefrontCapability.available&&window.open(previewHref,"_blank")}><Eye size={15}/> {storefrontCapability.available?"Open local storefront":"Public storefront not connected"}</Button>}/>
    <div className="compact-metrics"><MetricCard label="Public products" value={String(products.filter((p)=>p.enabled).length)} detail="NEXT F-owned identities" icon={Store}/><MetricCard label="Retail offers" value={String(offers.filter((o)=>o.enabled).length)} detail="Top-ups, codes, dynamic amounts" icon={Boxes}/><MetricCard label="Active supplier routes" value={String(activeMappings.length)} detail="Primary + fallback mappings" icon={Waypoints}/><MetricCard label="Quoted offers" value={String(estimated.length)} detail="Currently routeable" icon={ArrowUpDown}/></div>
    <Card className="gaming-vnext-notice"><div><strong>Supplier-agnostic contract</strong><p>FazerCards is Supplier #1, not the storefront model. Add future suppliers by mapping them to the same NEXT F offers. {runtime.isProduction&&!storefrontCapability.available?"The public storefront integration is not connected, so no simulated checkout or fulfillment is exposed in production.":""}</p></div>{runtime.isLocal&&<Button onClick={()=>{if(confirm("Reset the vNext local sandbox catalog to its seeded state?")) gamingVNextStore.reset();}}><RotateCcw size={14}/> Reset local sandbox</Button>}</Card>
    <div className="segmented-nav"><button className={tab==="products"?"is-active":""} onClick={()=>setTab("products")}>Products <span>{products.length}</span></button><button className={tab==="offers"?"is-active":""} onClick={()=>setTab("offers")}>Offers <span>{offers.length}</span></button><button className={tab==="routing"?"is-active":""} onClick={()=>setTab("routing")}>Supplier routing <span>{mappings.length}</span></button></div>
    <Card>{tab==="products"?<DataTable rows={products} columns={productCols} getKey={(r)=>r.id}/>:tab==="offers"?<DataTable rows={offers} columns={offerCols} getKey={(r)=>r.id}/>:<DataTable rows={mappings.sort((a,b)=>a.offerId.localeCompare(b.offerId)||a.priority-b.priority)} columns={mappingCols} getKey={(r)=>r.id}/>}</Card>
    <Modal open={!!selectedProduct} onClose={()=>setSelectedProduct(undefined)} title="Edit NEXT F product" description="Public identity and merchandising are controlled by NEXT F, not the supplier.">{selectedProduct&&<><div className="form-grid form-grid--two"><FormField label="Public name"><TextInput value={selectedProduct.name} onChange={(e)=>setSelectedProduct({...selectedProduct,name:e.target.value})}/></FormField><FormField label="Slug"><TextInput value={selectedProduct.slug} onChange={(e)=>setSelectedProduct({...selectedProduct,slug:e.target.value})}/></FormField><FormField label="Short description"><TextInput value={selectedProduct.shortDescription??""} onChange={(e)=>setSelectedProduct({...selectedProduct,shortDescription:e.target.value})}/></FormField><FormField label="Artwork URL"><TextInput value={selectedProduct.artworkUrl??""} onChange={(e)=>setSelectedProduct({...selectedProduct,artworkUrl:e.target.value})}/></FormField></div><div className="modal-actions"><Button onClick={()=>setSelectedProduct(undefined)}>Cancel</Button><Button variant="primary" onClick={()=>{gamingVNextStore.updateProduct(selectedProduct.id,selectedProduct);setSelectedProduct(undefined);}}>Save product</Button></div></>}</Modal>
    <Modal open={!!selectedOffer} onClose={()=>setSelectedOffer(undefined)} title="Edit retail offer" description="Price and customer-facing purchase configuration.">{selectedOffer&&<><div className="form-grid form-grid--two"><FormField label="Offer label"><TextInput value={selectedOffer.name} onChange={(e)=>setSelectedOffer({...selectedOffer,name:e.target.value})}/></FormField><FormField label="Pricing mode"><SelectInput value={selectedOffer.pricingMode} onChange={(e)=>setSelectedOffer({...selectedOffer,pricingMode:e.target.value as NextFGamingOffer["pricingMode"]})}><option value="fixed">Fixed</option><option value="supplier_quote">Supplier quote</option><option value="amount_based">Amount based</option></SelectInput></FormField><FormField label="Selling price LKR"><TextInput type="number" disabled={selectedOffer.pricingMode!=="fixed"} value={selectedOffer.sellingPriceLkr??""} onChange={(e)=>setSelectedOffer({...selectedOffer,sellingPriceLkr:Number(e.target.value)||undefined})}/></FormField><FormField label="Region warning"><TextInput value={selectedOffer.regionRule.label??""} onChange={(e)=>setSelectedOffer({...selectedOffer,regionRule:{...selectedOffer.regionRule,label:e.target.value}})}/></FormField></div><p className="form-note">Customer fields are supplier-derived capabilities normalized into NEXT F field schemas. Purchase field schemas are contract-bound and remain read-only here to avoid breaking purchase contracts.</p><div className="modal-actions"><Button onClick={()=>setSelectedOffer(undefined)}>Cancel</Button><Button variant="primary" onClick={()=>{gamingVNextStore.updateOffer(selectedOffer.id,selectedOffer);setSelectedOffer(undefined);}}>Save offer</Button></div></>}</Modal>
    <Modal open={!!selectedMapping} onClose={()=>setSelectedMapping(undefined)} title="Edit supplier route" description="Set priority and cost for this supplier mapping.">{selectedMapping&&<><div className="form-grid form-grid--two"><FormField label="Supplier"><SelectInput value={selectedMapping.supplierId} onChange={(e)=>setSelectedMapping({...selectedMapping,supplierId:e.target.value})}>{suppliers.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</SelectInput></FormField><FormField label="Priority"><TextInput type="number" min="1" value={selectedMapping.priority} onChange={(e)=>setSelectedMapping({...selectedMapping,priority:Math.max(1,Number(e.target.value)||1)})}/></FormField><FormField label="Supplier cost"><TextInput type="number" step="0.0001" value={selectedMapping.supplierCost} onChange={(e)=>setSelectedMapping({...selectedMapping,supplierCost:Number(e.target.value)||0})}/></FormField><FormField label="Currency"><TextInput value={selectedMapping.supplierCurrency} onChange={(e)=>setSelectedMapping({...selectedMapping,supplierCurrency:e.target.value.toUpperCase()})}/></FormField></div><div className="modal-actions"><Button onClick={()=>setSelectedMapping(undefined)}>Cancel</Button><Button variant="primary" onClick={()=>{gamingVNextStore.updateMapping(selectedMapping.id,selectedMapping);setSelectedMapping(undefined);}}>Save route</Button></div></>}</Modal>
  </div>;
}
