import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgeCheck, Check, ChevronRight, Copy, Gamepad2, KeyRound, Search, ShieldCheck, Sparkles, Star, WalletCards, X, Zap } from "lucide-react";
import type { PublicGamingProductProjection, PublicGamingOfferProjection, PublicGamingQuoteResponse } from "../publicContract";
import { localGamingPublicService } from "../runtime/publicGamingService";
import { useVNextStore } from "../runtime/useVNextStore";
import { gamingVNextStore } from "../runtime/store";
import { readRuntimeTruth } from "../../../services/production";

const publicStorefrontRuntime=readRuntimeTruth();

const lkr = (value: number) => new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR", maximumFractionDigits: 0 }).format(value);
const typeNames: Record<string,string> = { topup:"Game Top-Ups", gift_card:"Gift Cards", game_key:"Game Keys", steam_wallet:"Steam Wallet", steam_gift:"Steam Gifts", telegram_stars:"Telegram Stars", telegram_premium:"Telegram Premium", manual_service:"Services", subscription:"Subscriptions" };

function ProductCard({ product, onOpen }: { product: PublicGamingProductProjection; onOpen: () => void }) {
  const starting = product.offers.filter((o)=>o.sellingPriceLkr).map((o)=>o.sellingPriceLkr!).sort((a,b)=>a-b)[0];
  return <button className="gp-product-card" onClick={onOpen}>
    <span className="gp-product-art" style={product.artworkUrl?{backgroundImage:`linear-gradient(180deg,transparent 25%,rgba(4,7,17,.88)),url(${product.artworkUrl})`}:undefined}><span>{typeNames[product.kind]??product.kind}</span></span>
    <span className="gp-product-copy"><strong>{product.name}</strong><small>{product.shortDescription}</small><span className="gp-card-meta"><em>{starting?`From ${lkr(starting)}`:"Live price"}</em><i><Zap size={13}/> Digital delivery</i></span></span>
    <ChevronRight size={18}/>
  </button>;
}

function FieldInput({ field, value, onChange }: { field: PublicGamingOfferProjection["purchaseFields"][number]; value: string; onChange: (value:string)=>void }) {
  return <label className="gp-field"><span>{field.label}{field.required&&<b> *</b>}</span>{field.type==="select"?<select value={value} onChange={(e)=>onChange(e.target.value)}><option value="">Choose {field.label.toLowerCase()}</option>{field.options?.map((o)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={field.type==="number"?"number":field.type==="email"?"email":field.type==="url"?"url":"text"} placeholder={field.placeholder} value={value} onChange={(e)=>onChange(e.target.value)}/>} {field.helpText&&<small>{field.helpText}</small>}</label>;
}

export function PublicGamingStorefront() {
  if(!publicStorefrontRuntime.allowsSimulation) return <div className="gaming-public"><main><section className="gp-hero"><div><span className="gp-kicker"><ShieldCheck size={14}/> Production storefront</span><h1>Open the live <em>NEXT F Gaming</em> storefront.</h1><p>The embedded CMS storefront is a local-development simulator only. Production customer browsing and checkout run on the dedicated Gaming storefront.</p><div className="gp-trust"><span><ShieldCheck size={16}/> Production API</span><span><BadgeCheck size={16}/> Live supplier fulfillment</span><span><Zap size={16}/> Dedicated storefront</span></div><a className="gp-primary-action" href="https://gaming.nextf.lk" target="_blank" rel="noreferrer">Open gaming.nextf.lk</a></div><div className="gp-hero-card"><Gamepad2/><strong>CMS manages.<br/>Gaming sells.</strong><p>Use this CMS for catalog and merchandising control; use the live storefront for the customer experience.</p></div></section></main></div>;
  return <LocalPublicGamingStorefront/>;
}

function LocalPublicGamingStorefront() {
  useVNextStore(gamingVNextStore.getProducts); useVNextStore(gamingVNextStore.getOffers); useVNextStore(gamingVNextStore.getMappings);
  const [products,setProducts]=useState<PublicGamingProductProjection[]>([]); const [selected,setSelected]=useState<PublicGamingProductProjection>(); const [offer,setOffer]=useState<PublicGamingOfferProjection>(); const [fields,setFields]=useState<Record<string,string>>({}); const [quantity,setQuantity]=useState(1); const [amount,setAmount]=useState<number|undefined>(); const [validation,setValidation]=useState<{valid:boolean;displayName?:string;region?:string;message?:string}>(); const [quote,setQuote]=useState<PublicGamingQuoteResponse>(); const [busy,setBusy]=useState(false); const [order,setOrder]=useState<{id:string;number:string;amount:number;completed?:boolean;deliverables?:Array<{label?:string;value:string}>}>(); const [query,setQuery]=useState(""); const [kind,setKind]=useState("all");
  useEffect(()=>{localGamingPublicService.products().then(setProducts);},[]);
  useEffect(()=>{localGamingPublicService.products().then(setProducts);},[selected?.id, offer?.id]);
  const filtered=useMemo(()=>products.filter((p)=>(kind==="all"||p.kind===kind)&&`${p.name} ${p.brand??""} ${p.shortDescription??""}`.toLowerCase().includes(query.toLowerCase())),[products,query,kind]);
  const open=(product:PublicGamingProductProjection)=>{setSelected(product);const first=product.offers.find((o)=>o.availability==="available")??product.offers[0];setOffer(first);setFields({});setQuantity(first?.minQuantity??1);setAmount(first?.minAmount);setValidation(undefined);setQuote(undefined);setOrder(undefined);};
  const selectOffer=(next:PublicGamingOfferProjection)=>{setOffer(next);setFields({});setQuantity(next.minQuantity??1);setAmount(next.minAmount);setValidation(undefined);setQuote(undefined);setOrder(undefined);};
  const fieldsComplete=!!offer && offer.purchaseFields.every((f)=>!f.required||fields[f.key]?.trim());
  const validate=async()=>{if(!offer)return;setBusy(true);try{setValidation(await localGamingPublicService.validate({offerId:offer.id,fields}));}finally{setBusy(false);}};
  const getQuote=async()=>{if(!offer)return;setBusy(true);try{const result=await localGamingPublicService.quote({offerId:offer.id,quantity,requestedAmount:offer.pricingMode==="amount_based"?amount:undefined});setQuote(result);}finally{setBusy(false);}};
  const checkout=async()=>{if(!offer||!quote)return;setBusy(true);try{const created=await localGamingPublicService.checkout({quoteId:quote.quoteId,offerId:offer.id,fields,quantity,requestedAmount:offer.pricingMode==="amount_based"?amount:undefined,customer:{email:"prototype@nextf.lk"}});setOrder({id:created.orderId,number:created.orderNumber,amount:created.amountLkr});const completed=await localGamingPublicService.simulatePayment(created.orderId);setOrder({id:completed.id,number:completed.number,amount:completed.quote.sellingPriceLkr,completed:true,deliverables:completed.deliverables});}finally{setBusy(false);}};
  const canQuote=!!offer && fieldsComplete && (!offer.validationSupported || validation?.valid===true) && (offer.pricingMode!=="amount_based" || !!amount);

  return <div className="gaming-public">
    <header className="gp-header"><a className="gp-brand" href="/gaming" onClick={(e)=>{e.preventDefault();setSelected(undefined);}}>NEXT <b>F</b><small>GAMING</small></a><div className="gp-search"><Search size={18}/><input aria-label="Search games and digital products" placeholder="Search games, gift cards, Steam, Telegram…" value={query} onChange={(e)=>setQuery(e.target.value)}/></div><span className="gp-secure"><ShieldCheck size={16}/> Secure digital checkout</span></header>
    <main>
      <section className="gp-hero"><div><span className="gp-kicker"><Sparkles size={14}/> Digital gaming, built for instant fulfillment</span><h1>Top up. Redeem. <em>Play.</em></h1><p>Game credits, gift cards, keys, Steam and more - one NEXT F experience powered by multiple suppliers behind the scenes.</p><div className="gp-trust"><span><Zap size={16}/> Fast digital delivery</span><span><BadgeCheck size={16}/> Account validation</span><span><ShieldCheck size={16}/> Region-aware products</span></div></div><div className="gp-hero-card"><Gamepad2/><strong>One storefront.<br/>Many suppliers.</strong><p>NEXT F controls the product experience while supplier APIs handle stock, validation and fulfillment.</p></div></section>
      <section className="gp-shop"><div className="gp-section-head"><div><span>Digital catalog</span><h2>Choose what you want to buy</h2></div><small>{filtered.length} products</small></div>
        <div className="gp-kind-tabs"><button className={kind==="all"?"active":""} onClick={()=>setKind("all")}>All</button>{[...new Set(products.map((p)=>p.kind))].map((k)=><button key={k} className={kind===k?"active":""} onClick={()=>setKind(k)}>{typeNames[k]??k}</button>)}</div>
        <div className="gp-grid">{filtered.map((product)=><ProductCard key={product.id} product={product} onOpen={()=>open(product)}/>)}</div>
      </section>
      <section className="gp-explain"><div><span>01</span><strong>Choose a digital product</strong><p>NEXT F shows one clean retail catalog, regardless of which supplier fulfills it.</p></div><div><span>02</span><strong>Verify the right account</strong><p>For supported top-ups and Steam flows, account checks happen before payment.</p></div><div><span>03</span><strong>Pay and receive digitally</strong><p>Top-ups are confirmed to the account; codes and keys are revealed securely.</p></div></section>
    </main>
    {selected&&offer&&<div className="gp-overlay" role="dialog" aria-modal="true" aria-label={`${selected.name} purchase`}><div className="gp-checkout-panel"><button className="gp-close" aria-label="Close" onClick={()=>setSelected(undefined)}><X/></button>
      <button className="gp-back" onClick={()=>setSelected(undefined)}><ArrowLeft size={15}/> Back to catalog</button>
      {!order?<><div className="gp-checkout-title"><span>{typeNames[selected.kind]}</span><h2>{selected.name}</h2><p>{selected.shortDescription}</p></div>
        <div className="gp-flow-section"><label className="gp-label">1. Choose option</label><div className="gp-offers">{selected.offers.map((o)=><button key={o.id} disabled={o.availability!=="available"} className={o.id===offer.id?"selected":""} onClick={()=>selectOffer(o)}><strong>{o.name}</strong><small>{o.sellingPriceLkr?lkr(o.sellingPriceLkr):o.pricingMode==="amount_based"?"Choose amount":"Live quote"}</small></button>)}</div></div>
        {offer.regionRule.label&&<div className="gp-region"><ShieldCheck size={16}/><div><strong>Region</strong><span>{offer.regionRule.label}</span></div></div>}
        {offer.purchaseFields.length>0&&<div className="gp-flow-section"><label className="gp-label">2. Account details</label><div className="gp-fields">{offer.purchaseFields.map((field)=><FieldInput key={field.key} field={field} value={fields[field.key]??""} onChange={(value)=>{setFields({...fields,[field.key]:value});setValidation(undefined);setQuote(undefined);}}/>)}</div>{offer.validationSupported&&<button className="gp-secondary-action" disabled={!fieldsComplete||busy} onClick={validate}><BadgeCheck size={16}/>{busy?"Checking…":"Verify account"}</button>}{validation&&<div className={`gp-validation ${validation.valid?"success":"error"}`}><span>{validation.valid?<Check size={17}/>:<X size={17}/>}</span><div><strong>{validation.valid?validation.displayName??"Account verified":"Could not verify account"}</strong><small>{validation.message}{validation.region?` · ${validation.region}`:""}</small></div></div>}</div>}
        {offer.pricingMode==="amount_based"&&<div className="gp-flow-section"><label className="gp-label">{offer.purchaseFields.length?"3":"2"}. Choose amount</label><div className="gp-amount"><button onClick={()=>setAmount(offer.minAmount)}>{offer.kind==="telegram_stars"?`${offer.minAmount} Stars`:`$${offer.minAmount}`}</button><button onClick={()=>setAmount(Math.min(offer.maxAmount??100,offer.kind==="telegram_stars"?500:10))}>{offer.kind==="telegram_stars"?"500 Stars":"$10"}</button><input type="number" min={offer.minAmount} max={offer.maxAmount} step={offer.amountStep} value={amount??""} onChange={(e)=>{setAmount(Number(e.target.value));setQuote(undefined);}}/></div><small className="gp-hint">Allowed: {offer.minAmount}-{offer.maxAmount}{offer.kind==="telegram_stars"?" Stars":""}</small></div>}
        {(offer.maxQuantity??1)>1&&<div className="gp-flow-section"><label className="gp-label">Quantity</label><div className="gp-qty"><button onClick={()=>setQuantity(Math.max(offer.minQuantity??1,quantity-1))}>−</button><strong>{quantity}</strong><button onClick={()=>setQuantity(Math.min(offer.maxQuantity??quantity+1,quantity+1))}>+</button></div></div>}
        <div className="gp-summary"><div><span>{offer.name}</span><strong>{quote?lkr(quote.sellingPriceLkr):offer.sellingPriceLkr?lkr(offer.sellingPriceLkr*quantity):"Get live price"}</strong></div>{quote?<button className="gp-primary-action" disabled={busy} onClick={checkout}><WalletCards size={18}/>{busy?"Processing…":"Continue to payment"}</button>:<button className="gp-primary-action" disabled={!canQuote||busy} onClick={getQuote}><Zap size={18}/>{busy?"Checking price…":"Continue"}</button>}<small>Local sandbox only: payment and supplier fulfillment are simulated. Production never uses this path.</small></div>
      </>:<div className="gp-success"><span><Check/></span><h2>Digital delivery complete</h2><p>Order <strong>{order.number}</strong> was fulfilled successfully.</p><div className="gp-success-amount"><span>Total</span><strong>{lkr(order.amount)}</strong></div>{order.deliverables?.map((d,i)=><div className="gp-deliverable" key={i}><KeyRound/><div><span>{d.label??"Delivery"}</span><strong>{d.value}</strong></div><button onClick={()=>navigator.clipboard?.writeText(d.value)} aria-label="Copy"><Copy size={16}/></button></div>)}<button className="gp-primary-action" onClick={()=>{setSelected(undefined);setOrder(undefined);}}>Done</button></div>}
    </div></div>}
  </div>;
}
