import { useEffect, useState } from 'react';
import { Boxes, PlugZap, RefreshCw, WalletCards } from 'lucide-react';
import { Badge, Button, Card, FormField, MetricCard, SectionHeader, TextInput, Toggle } from '../../shared/components';
import { useToast } from '../../shared/feedback/ToastProvider';
import { flushDurableWrites } from '../../services/production/durableStorage';
import { gamingDate } from '../shared/format';
import { useGamingStore } from '../shared/useGamingStore';
import { getFazerConfig, getFazerStatus, queueFazerCommand, refreshFazerConfig, refreshFazerStatus, saveFazerConfig, type FazerCatalogKind } from '../live/fazercardsControl';

const KIND_LABELS:Array<[FazerCatalogKind,string]>=[['topup','Top-ups'],['gift_card','Gift cards'],['game_key','Game keys'],['manual_service','Manual services']];

export function SuppliersPage(){
  const config=useGamingStore(getFazerConfig);const status=useGamingStore(getFazerStatus);const {notify}=useToast();
  const [draft,setDraft]=useState(config);const [busy,setBusy]=useState(false);const [pending,setPending]=useState<string|undefined>();
  useEffect(()=>setDraft(config),[config]);
  useEffect(()=>{void Promise.allSettled([refreshFazerConfig(),refreshFazerStatus()]);},[]);
  const save=async()=>{setBusy(true);try{saveFazerConfig(draft);await flushDurableWrites();notify({title:'FazerCards settings saved',description:'Production supplier configuration is stored in D1. Credentials remain Worker secrets.',tone:'success'});}catch(error){notify({title:'Supplier settings failed',description:error instanceof Error?error.message:'Unable to save supplier configuration.',tone:'danger'});}finally{setBusy(false);}};
  const refresh=async()=>{setBusy(true);try{await Promise.all([refreshFazerConfig(),refreshFazerStatus()]);notify({title:'Supplier state refreshed',description:'Latest production configuration and Worker status loaded.',tone:'success'});}catch(error){notify({title:'Refresh failed',description:error instanceof Error?error.message:'Unable to refresh supplier state.',tone:'danger'});}finally{setBusy(false);}};
  const waitForCommand=async(id:string)=>{for(let attempt=0;attempt<15;attempt+=1){await new Promise((resolve)=>setTimeout(resolve,5000));try{const next=await refreshFazerStatus();if(next.lastProcessedCommandId===id){setPending(undefined);if(next.lastError)notify({title:'FazerCards operation failed',description:next.lastError,tone:'danger'});else notify({title:'FazerCards operation completed',description:'The Gaming Worker processed the CMS request.',tone:'success'});return;}}catch{/* continue */}}setPending(undefined);notify({title:'Operation still queued',description:'The Worker runs every minute. Refresh shortly to load the result.',tone:'info'});};
  const run=async(action:'health'|'preview'|'sync')=>{setBusy(true);try{saveFazerConfig(draft);await flushDurableWrites();const cmd=queueFazerCommand(action,action==='health'?undefined:draft.catalogKinds);await flushDurableWrites();setPending(cmd.id);notify({title:action==='health'?'Health check queued':action==='preview'?'Catalog preview queued':'Catalog sync queued',description:'The production Gaming Worker will process this request within about one minute.',tone:'info'});void waitForCommand(cmd.id);}catch(error){notify({title:'Supplier command failed',description:error instanceof Error?error.message:'Unable to queue supplier operation.',tone:'danger'});}finally{setBusy(false);}};
  const toggleKind=(kind:FazerCatalogKind,enabled:boolean)=>setDraft({...draft,catalogKinds:enabled?[...new Set([...draft.catalogKinds,kind])]:draft.catalogKinds.filter((item)=>item!==kind)});
  const summary=status.lastSync;
  return <div className="page">
    <SectionHeader eyebrow="Gaming Store" title="Suppliers" description="Canonical supplier control plane. FazerCards is the active production provider; future suppliers will appear here only after a real server adapter and canonical routing integration exist."/>
    <div className="compact-metrics"><MetricCard label="FazerCards" value={status.connected?'Connected':'Needs check'} detail={status.account?.plan?`${status.account.plan} plan`:'Production adapter'} icon={PlugZap}/><MetricCard label="Supplier balance" value={status.balance?`${status.balance.amount} ${status.balance.currency}`:'—'} detail={status.lastHealthAt?`Checked ${gamingDate(status.lastHealthAt)}`:'Run health check'} icon={WalletCards}/><MetricCard label="Last catalog sync" value={summary?String(summary.productsWritten):'—'} detail={summary?`${summary.offersWritten} offers · ${gamingDate(summary.completedAt)}`:'No CMS-visible sync result yet'} icon={Boxes}/></div>
    {status.lastError?<Card className="architecture-callout"><div className="operation-section__head"><div><span>Supplier status</span><h3>Last Worker operation failed</h3></div><Badge tone="danger">Attention</Badge></div><p>{status.lastError}</p></Card>:null}
    <Card className="operation-section"><div className="operation-section__head"><div><span>FazerCards</span><h3>Production configuration</h3></div><div className="table-actions"><Badge tone={draft.enabled?'success':'neutral'}>{draft.enabled?'Enabled':'Disabled'}</Badge><Button onClick={refresh} disabled={busy}><RefreshCw size={14}/>Refresh</Button></div></div>
      <div className="form-grid form-grid--two"><FormField label="Base API URL"><TextInput value={draft.baseUrl} onChange={(e)=>setDraft({...draft,baseUrl:e.target.value})}/></FormField><FormField label="Maximum categories per sync"><TextInput type="number" min="1" max="200" value={draft.maxCategoriesPerSync} onChange={(e)=>setDraft({...draft,maxCategoriesPerSync:Number(e.target.value)})}/></FormField></div>
      <div className="settings-stack"><div className="setting-row"><div><strong>Supplier enabled</strong><small>Allow FazerCards catalog and fulfillment runtime.</small></div><Toggle checked={draft.enabled} onChange={(enabled)=>setDraft({...draft,enabled})}/></div><div className="setting-row"><div><strong>Auto-publish products</strong><small>Synced products are visible immediately when available.</small></div><Toggle checked={draft.autoPublishProducts} onChange={(autoPublishProducts)=>setDraft({...draft,autoPublishProducts})}/></div><div className="setting-row"><div><strong>Auto-publish offers</strong><small>Available supplier offers can be sold without a second publish step.</small></div><Toggle checked={draft.autoPublishOffers} onChange={(autoPublishOffers)=>setDraft({...draft,autoPublishOffers})}/></div></div>
      <div className="operation-section__head"><div><span>Catalog families</span><h3>What to synchronize</h3></div></div><div className="settings-stack">{KIND_LABELS.map(([kind,label])=><div className="setting-row" key={kind}><div><strong>{label}</strong><small>{kind}</small></div><Toggle checked={draft.catalogKinds.includes(kind)} onChange={(enabled)=>toggleKind(kind,enabled)}/></div>)}</div>
      <div className="modal-actions"><Button variant="primary" onClick={save} disabled={busy||!draft.catalogKinds.length}>{busy?'Working…':'Save supplier settings'}</Button><Button onClick={()=>run('health')} disabled={busy||!!pending}>Health check</Button><Button onClick={()=>run('preview')} disabled={busy||!!pending||!draft.catalogKinds.length}>Preview catalog</Button><Button onClick={()=>run('sync')} disabled={busy||!!pending||!draft.catalogKinds.length}><RefreshCw size={14}/>Sync catalog</Button></div>{pending?<p className="security-note">Request queued. This page is polling the Worker result automatically; the scheduled processor runs once per minute.</p>:null}
    </Card>
    <Card className="architecture-callout"><div className="operation-section__head"><div><span>Supplier architecture</span><h3>No placeholder provider registry</h3></div><Badge tone="info">Canonical only</Badge></div><p>The previous local “Add supplier” registry has been removed from production because it did not create a real provider adapter or fulfillment route. The next supplier will be added through the canonical multi-supplier layer with health, credentials, routing priority and fallback behavior.</p></Card>
    <Card className="architecture-callout"><div className="operation-section__head"><div><span>Secret boundary</span><h3>API key stays out of the CMS browser</h3></div><Badge tone="success">Server-side only</Badge></div><p>The FazerCards API key remains in the <code>nextf-gaming-api</code> Worker secret <code>FAZERCARDS_API_KEY</code>. This CMS controls non-secret settings and audited D1 commands only.</p></Card>
  </div>;
}
