import { useEffect, useMemo, useState } from 'react';
import { Activity, Boxes, CheckCircle2, Clock3, Copy, Eye, PlugZap, RefreshCw, Save, ShieldCheck, SlidersHorizontal, TriangleAlert, WalletCards } from 'lucide-react';
import { Badge, Button, Card, FormField, MetricCard, Modal, SectionHeader, SelectInput, TextInput, Toggle } from '../../shared/components';
import { useSession } from '../../app/auth/SessionProvider';
import { useToast } from '../../shared/feedback/ToastProvider';
import { flushDurableWrites } from '../../services/production/durableStorage';
import { gamingDate } from '../shared/format';
import { GamingKindBadge } from '../shared/GamingKindBadge';
import { useGamingStore } from '../shared/useGamingStore';
import { getFazerConfig, getFazerStatus, queueFazerCommand, refreshFazerConfig, refreshFazerStatus, saveFazerConfig, type FazerCatalogKind } from '../live/fazercardsControl';
import { createFazerFundingPayment, loadFazerFundingSnapshot, refreshFazerFundingPayment, verifyFazerBinancePayment, type FundingRecord, type FundingSnapshot } from '../live/fazercardsFunding';
import { PaymentQr } from '../../shared/qr/PaymentQr';

const KIND_LABELS:Array<[FazerCatalogKind,string]>=[['topup','Top-ups'],['gift_card','Gift cards'],['game_key','Game keys'],['manual_service','Manual services']];
const money=(value:number|string|undefined)=>{const amount=Number(value);return Number.isFinite(amount)?`$${amount.toFixed(2)}`:'—';};
const stateTone=(state:string):'success'|'warning'|'danger'|'info'|'neutral'=>state==='completed'?'success':state==='pending'||state==='creating'?'warning':state==='failed'||state==='uncertain'?'danger':state==='cancelled'?'neutral':'info';
const exactProviderAmount=(record:FundingRecord|undefined)=>record?.payment?.uniqueAmount?.trim()||record?.payment?.amount?.trim()||'';
const countdown=(expiresAt:string|undefined|null,now:number)=>{if(!expiresAt)return '';const target=Date.parse(expiresAt);if(!Number.isFinite(target))return '';const remaining=Math.max(0,target-now);const total=Math.floor(remaining/1000);const h=Math.floor(total/3600);const m=Math.floor((total%3600)/60);const sec=total%60;return h>0?`${h}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;};
const fundingProblem=(message:string)=>{const normalized=message.toUpperCase();if(normalized.includes('SUPPLIER_FUNDING_UNAUTHORIZED')||normalized.includes('VALID SUPPLIER-FUNDING CREDENTIAL'))return{title:'Funding bridge unavailable',detail:'The CMS and Gaming API funding credentials do not match. Correct the server-to-server credential on both Workers, then refresh funding.'};if(normalized.includes('GAMING_CONTROL_NOT_CONFIGURED'))return{title:'Funding bridge not configured',detail:'The CMS funding bridge is missing its production server credential. Configure it on both Workers, then refresh funding.'};return{title:'Funding status unavailable',detail:message.replace(/^INTERNAL_ERROR:\s*/i,'').trim()||'The live supplier funding service could not be loaded.'};};

export function SuppliersPage(){
  const config=useGamingStore(getFazerConfig);const status=useGamingStore(getFazerStatus);const {notify}=useToast();const {can}=useSession();
  const [draft,setDraft]=useState(config);const [busy,setBusy]=useState(false);const [pending,setPending]=useState<string|undefined>();
  const [funding,setFunding]=useState<FundingSnapshot>();const [fundingError,setFundingError]=useState('');const [fundingBusy,setFundingBusy]=useState(false);const [fundingOpen,setFundingOpen]=useState(false);const [fundingRecord,setFundingRecord]=useState<FundingRecord>();const [fundingMethod,setFundingMethod]=useState('');const [fundingAmount,setFundingAmount]=useState('');const [binanceOrderId,setBinanceOrderId]=useState('');const [nowMs,setNowMs]=useState(()=>Date.now());
  const canFund=can('gaming.suppliers.manage')&&can('gaming.finance.manage');
  useEffect(()=>setDraft(config),[config]);
  useEffect(()=>{void Promise.allSettled([refreshFazerConfig(),refreshFazerStatus()]);},[]);
  const loadFunding=async(silent=false)=>{if(!canFund)return;setFundingBusy(true);try{const next=await loadFazerFundingSnapshot();setFunding(next);setFundingError('');setFundingMethod((current)=>current&&next.methods.some((item)=>item.code===current)?current:next.methods.find((item)=>item.code==='binancepay')?.code??next.methods[0]?.code??'');if(!silent)notify({title:'Funding status refreshed',description:'Latest FazerCards wallet and payment methods loaded.',tone:'success'});}catch(error){const message=error instanceof Error?error.message:'Unable to load supplier funding.';setFundingError(message);if(!silent)notify({title:'Funding status unavailable',description:message,tone:'danger'});}finally{setFundingBusy(false);}};
  useEffect(()=>{void loadFunding(true);},[canFund]);
  useEffect(()=>{if(!fundingRecord?.payment?.expiresAt||fundingRecord.state==='completed'||fundingRecord.state==='cancelled'||fundingRecord.state==='failed')return;setNowMs(Date.now());const timer=window.setInterval(()=>setNowMs(Date.now()),1000);return()=>window.clearInterval(timer);},[fundingRecord?.payment?.expiresAt,fundingRecord?.state]);
  const dirty=useMemo(()=>JSON.stringify(draft)!==JSON.stringify(config),[draft,config]);
  useEffect(()=>{if(!dirty)return;const handler=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
  const save=async()=>{setBusy(true);try{saveFazerConfig(draft);await flushDurableWrites();notify({title:'FazerCards settings saved',description:'Production supplier configuration is stored in D1. Credentials remain Worker secrets.',tone:'success'});}catch(error){notify({title:'Supplier settings failed',description:error instanceof Error?error.message:'Unable to save supplier configuration.',tone:'danger'});}finally{setBusy(false);}};
  const refresh=async()=>{setBusy(true);try{await Promise.all([refreshFazerStatus(),canFund?loadFunding(true):Promise.resolve()]);notify({title:'Supplier status refreshed',description:'Latest production Worker health, supplier status and funding state loaded.',tone:'success'});}catch(error){notify({title:'Refresh failed',description:error instanceof Error?error.message:'Unable to refresh supplier state.',tone:'danger'});}finally{setBusy(false);}};
  const waitForCommand=async(id:string)=>{for(let attempt=0;attempt<15;attempt+=1){await new Promise((resolve)=>setTimeout(resolve,5000));try{const next=await refreshFazerStatus();if(next.lastProcessedCommandId===id){setPending(undefined);if(next.lastError)notify({title:'FazerCards operation failed',description:next.lastError,tone:'danger'});else notify({title:'FazerCards operation completed',description:'The Gaming Worker processed the CMS request.',tone:'success'});return;}}catch{/* continue */}}setPending(undefined);notify({title:'Operation still queued',description:'The Worker runs every minute. Refresh shortly to load the result.',tone:'info'});};
  const run=async(action:'health'|'preview'|'sync')=>{setBusy(true);try{const cmd=queueFazerCommand(action,action==='health'?undefined:draft.catalogKinds);await flushDurableWrites();setPending(cmd.id);notify({title:action==='health'?'Health check queued':action==='preview'?'Catalog preview queued':'Catalog sync queued',description:'The production Gaming Worker will process this request within about one minute.',tone:'info'});void waitForCommand(cmd.id);}catch(error){notify({title:'Supplier command failed',description:error instanceof Error?error.message:'Unable to queue supplier operation.',tone:'danger'});}finally{setBusy(false);}};
  const toggleKind=(kind:FazerCatalogKind,enabled:boolean)=>setDraft({...draft,catalogKinds:enabled?[...new Set([...draft.catalogKinds,kind])]:draft.catalogKinds.filter((item)=>item!==kind)});
  const summary=status.lastSync;const preview=status.lastPreview;const selectedKindCount=draft.catalogKinds.length;const fundingIssue=fundingError?fundingProblem(fundingError):undefined;const fundingIsLive=Boolean(funding?.balance);const fundingMethodCount=funding?.methods.length??0;
  const selectedMethod=funding?.methods.find((item)=>item.code===fundingMethod);const numericAmount=Number(fundingAmount);const amountInvalid=!selectedMethod||!Number.isFinite(numericAmount)||numericAmount<selectedMethod.minAmountUsd||numericAmount>selectedMethod.maxAmountUsd;
  const recordMethod=fundingRecord?funding?.methods.find((item)=>item.code===fundingRecord.method):undefined;const providerAmount=exactProviderAmount(fundingRecord);const providerAsset=recordMethod?.label.match(/\bUSDT\b/i)?'USDT':'';const paymentExpiresAt=fundingRecord?.payment?.expiresAt;const paymentExpiryMs=paymentExpiresAt?Date.parse(paymentExpiresAt):Number.NaN;const paymentExpired=Number.isFinite(paymentExpiryMs)&&paymentExpiryMs<=nowMs&&fundingRecord?.state!=='completed';const paymentCountdown=countdown(paymentExpiresAt,nowMs);const onChainPayment=Boolean(fundingRecord?.payment?.address)&&fundingRecord?.method!=='binancepay';
  const openFunding=()=>{setFundingRecord(undefined);setFundingAmount('');setBinanceOrderId('');setNowMs(Date.now());setFundingOpen(true);};
  const newFunding=()=>{setFundingRecord(undefined);setBinanceOrderId('');setNowMs(Date.now());};
  const createFunding=async()=>{if(amountInvalid||!selectedMethod)return;setFundingBusy(true);try{const record=await createFazerFundingPayment(selectedMethod.code,numericAmount);setFundingRecord(record);await loadFunding(true);notify({title:'FazerCards funding created',description:'Complete the payment using the provider instructions shown in this dialog.',tone:'success'});}catch(error){notify({title:'Funding request failed',description:error instanceof Error?error.message:'Unable to create FazerCards funding.',tone:'danger'});}finally{setFundingBusy(false);}};
  const refreshPayment=async()=>{if(!fundingRecord?.externalPaymentId)return;setFundingBusy(true);try{const record=await refreshFazerFundingPayment(fundingRecord.externalPaymentId);setFundingRecord(record);await loadFunding(true);notify({title:'Payment status refreshed',description:`FazerCards reports ${record.state}.`,tone:record.state==='completed'?'success':'info'});}catch(error){notify({title:'Payment refresh failed',description:error instanceof Error?error.message:'Unable to refresh payment status.',tone:'danger'});}finally{setFundingBusy(false);}};
  const verifyBinance=async()=>{if(!fundingRecord?.externalPaymentId||!binanceOrderId.trim())return;setFundingBusy(true);try{const record=await verifyFazerBinancePayment(fundingRecord.externalPaymentId,binanceOrderId.trim());setFundingRecord(record);await loadFunding(true);notify({title:record.state==='completed'?'Funding completed':'Verification submitted',description:record.state==='completed'?'FazerCards wallet funding was verified successfully.':'FazerCards returned the latest payment state.',tone:record.state==='completed'?'success':'info'});}catch(error){notify({title:'Binance verification failed',description:error instanceof Error?error.message:'Unable to verify Binance Pay.',tone:'danger'});}finally{setFundingBusy(false);}};
  const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);notify({title:'Copied',description:'Payment detail copied to clipboard.',tone:'success'});}catch{notify({title:'Copy failed',description:'Copy this value manually.',tone:'danger'});}};
  return <div className="page supplier-control-page">
    <SectionHeader eyebrow="Gaming Store" title="Suppliers" description="Monitor provider health, control runtime publishing, fund supplier balance and run catalog synchronization from one canonical supplier workspace." action={<Button onClick={refresh} disabled={busy||fundingBusy}><RefreshCw size={14}/>Refresh status</Button>}/>

    <div className="supplier-health-strip">
      <MetricCard label="FazerCards" value={status.connected?'Connected':'Needs check'} detail={status.account?.plan?`${status.account.plan} plan`:'Production adapter'} icon={PlugZap}/>
      <MetricCard label="Supplier balance" value={funding?.balance?`${funding.balance.amount} ${funding.balance.currency}`:status.balance?`${status.balance.amount} ${status.balance.currency}`:'—'} detail={funding?.generatedAt?`Live funding view · ${gamingDate(funding.generatedAt)}`:fundingIssue?'Last known balance · funding bridge unavailable':status.lastHealthAt?`Checked ${gamingDate(status.lastHealthAt)}`:'Run health check'} icon={WalletCards}/>
      <MetricCard label="Last health check" value={status.lastHealthAt?gamingDate(status.lastHealthAt):'Not checked'} detail={status.connected?'Provider connection healthy':'Health status needs confirmation'} icon={Activity}/>
      <MetricCard label="Last catalog sync" value={summary?String(summary.productsWritten):'—'} detail={summary?`${summary.offersWritten} offers · ${gamingDate(summary.completedAt)}`:'No CMS-visible sync result yet'} icon={Boxes}/>
    </div>

    {status.lastError?<Card className="supplier-alert-card"><div><span className="supplier-alert-card__icon"><Activity size={18}/></span><div><strong>Last supplier operation failed</strong><p>{status.lastError}</p></div></div><Badge tone="danger">Attention</Badge></Card>:null}

    <Card className={`supplier-funding-panel ${fundingIssue?'has-error':''}`}>
      <div className="operation-section__head"><div><span>Supplier funding</span><h3>FazerCards wallet</h3></div><div className="supplier-panel-status"><Badge tone={fundingIssue?'danger':canFund?'success':'neutral'}>{fundingIssue?'Bridge issue':canFund?'Protected':'No finance access'}</Badge></div></div>
      <div className="supplier-funding-workspace">
        <div className="supplier-funding-main">
          <div className="supplier-funding-balance"><span>{fundingIsLive?'Live supplier balance':'Last known supplier balance'}</span><strong>{funding?.balance?`${money(funding.balance.amount)} ${funding.balance.currency}`:status.balance?`${money(status.balance.amount)} ${status.balance.currency}`:'—'}</strong><small>{funding?.account?.plan?`${funding.account.plan} reseller plan`:fundingIsLive?'Live balance is read from FazerCards through the Gaming API.':'The provider health snapshot remains visible while the protected funding bridge is unavailable.'}</small></div>
          <div className="supplier-funding-facts"><div><span>Funding bridge</span><strong>{fundingIssue?'Unavailable':funding?'Connected':'Checking…'}</strong><small>CMS → Gaming API</small></div><div><span>Payment methods</span><strong>{fundingMethodCount}</strong><small>{fundingMethodCount?'Live provider methods':'Waiting for funding bridge'}</small></div></div>
          <div className="supplier-funding-actions"><Button onClick={()=>void loadFunding(false)} disabled={!canFund||fundingBusy}><RefreshCw size={14}/>{fundingBusy?'Refreshing…':'Refresh funding'}</Button><Button variant="primary" onClick={openFunding} disabled={!canFund||fundingBusy||Boolean(fundingIssue)||!funding?.methods.length}><WalletCards size={14}/>Add funds</Button></div>
        </div>
        <div className="supplier-funding-side">
          {fundingIssue?<div className="supplier-funding-error"><TriangleAlert size={18}/><div><strong>{fundingIssue.title}</strong><p>{fundingIssue.detail}</p><small>No funding request can be created until the bridge is healthy. Existing supplier runtime and catalog controls are unaffected.</small></div></div>:funding?.payments.length?<div className="supplier-funding-history"><div className="supplier-funding-history__head"><strong>Recent funding</strong><span>Last {Math.min(5,funding.payments.length)} requests</span></div>{funding.payments.slice(0,5).map((record)=><div className="supplier-funding-row" key={record.intentId}><div><strong>{money(record.amountUsd)}</strong><small>{funding.methods.find((item)=>item.code===record.method)?.label??record.method}{record.externalPaymentId?` · ${record.externalPaymentId}`:''}</small></div><div><Badge tone={stateTone(record.state)}>{record.state}</Badge><small>{gamingDate(record.updatedAt)}</small></div></div>)}</div>:<div className="supplier-funding-empty-state"><WalletCards size={18}/><div><strong>No funding activity yet</strong><p>No supplier funding requests have been recorded yet.</p></div></div>}
        </div>
      </div>
    </Card>

    <div className="supplier-control-grid">
      <Card className="supplier-panel supplier-runtime-panel">
        <div className="operation-section__head"><div><span>Runtime & publishing</span><h3>Production behavior</h3></div><div className="supplier-panel-status"><Badge tone={draft.enabled?'success':'neutral'}>{draft.enabled?'Enabled':'Disabled'}</Badge>{dirty?<Badge tone="warning">Unsaved</Badge>:<Badge tone="success">Saved</Badge>}</div></div>
        <p className="supplier-panel-copy">These settings control how FazerCards participates in live catalog and fulfillment. Credentials remain server-side.</p>
        <div className="form-grid form-grid--two supplier-runtime-fields"><FormField label="Base API URL" hint="Non-secret provider endpoint used by the Gaming Worker."><TextInput value={draft.baseUrl} onChange={(event)=>setDraft({...draft,baseUrl:event.target.value})}/></FormField><FormField label="Maximum categories per sync" hint="Safety cap for each catalog synchronization run."><TextInput type="number" min="1" max="200" value={draft.maxCategoriesPerSync} onChange={(event)=>setDraft({...draft,maxCategoriesPerSync:Number(event.target.value)})}/></FormField></div>
        <div className="supplier-toggle-grid">
          <div className="supplier-toggle-card"><div><span className="supplier-toggle-card__icon"><PlugZap size={16}/></span><span><strong>Supplier runtime</strong><small>Allow FazerCards catalog and fulfillment operations.</small></span></div><Toggle checked={draft.enabled} onChange={(enabled)=>setDraft({...draft,enabled})}/></div>
          <div className="supplier-toggle-card"><div><span className="supplier-toggle-card__icon"><Boxes size={16}/></span><span><strong>Auto-publish products</strong><small>Make synchronized NEXT F products public when available.</small></span></div><Toggle checked={draft.autoPublishProducts} onChange={(autoPublishProducts)=>setDraft({...draft,autoPublishProducts})}/></div>
          <div className="supplier-toggle-card"><div><span className="supplier-toggle-card__icon"><SlidersHorizontal size={16}/></span><span><strong>Auto-publish offers</strong><small>Allow available supplier offers to become sellable immediately.</small></span></div><Toggle checked={draft.autoPublishOffers} onChange={(autoPublishOffers)=>setDraft({...draft,autoPublishOffers})}/></div>
        </div>
        <div className="supplier-save-bar"><div>{dirty?<><strong>Unsaved changes</strong><small>Save before leaving to apply these runtime settings.</small></>:<><strong>Configuration saved</strong><small>Production D1 matches the current form.</small></>}</div><Button variant="primary" onClick={save} disabled={busy||!dirty||!draft.catalogKinds.length}><Save size={14}/>{busy?'Saving…':'Save changes'}</Button></div>
      </Card>

      <Card className="supplier-panel supplier-sync-panel">
        <div className="operation-section__head"><div><span>Catalog synchronization</span><h3>Choose what FazerCards may import</h3></div><Badge tone={selectedKindCount?'info':'warning'}>{selectedKindCount} selected</Badge></div>
        <p className="supplier-panel-copy">Select the supplier families that belong in the NEXT F catalog. Preview first when you want to inspect the incoming scope without writing it.</p>
        <div className="supplier-kind-grid">{KIND_LABELS.map(([kind,label])=>{const active=draft.catalogKinds.includes(kind);return <button type="button" key={kind} className={`supplier-kind-tile ${active?'is-active':''}`} aria-pressed={active} onClick={()=>toggleKind(kind,!active)}><span className="supplier-kind-tile__check">{active?<CheckCircle2 size={16}/>:null}</span><span><strong>{label}</strong><GamingKindBadge kind={kind}/></span></button>;})}</div>
        <div className="supplier-sync-summary">
          <div><span>Last preview</span><strong>{preview?`${preview.productsWritten} products`:'Not run'}</strong><small>{preview?`${preview.offersWritten} offers · ${gamingDate(preview.completedAt)}`:'Preview before syncing if the supplier scope changed.'}</small></div>
          <div><span>Last sync</span><strong>{summary?`${summary.productsWritten} products`:'Not run'}</strong><small>{summary?`${summary.offersWritten} offers · ${gamingDate(summary.completedAt)}`:'No completed synchronization is visible yet.'}</small></div>
        </div>
        <div className="supplier-command-grid">
          <Button onClick={()=>run('health')} disabled={busy||!!pending}><Activity size={14}/>Health check</Button>
          <Button onClick={()=>run('preview')} disabled={busy||!!pending||dirty||!selectedKindCount}><Eye size={14}/>Preview catalog</Button>
          <Button variant="primary" onClick={()=>run('sync')} disabled={busy||!!pending||dirty||!selectedKindCount}><RefreshCw size={14}/>Sync catalog</Button>
        </div>
        {dirty?<p className="supplier-command-note">Save configuration changes before previewing or syncing the supplier catalog.</p>:null}{pending?<div className="supplier-pending-state"><RefreshCw size={15}/><div><strong>Worker request queued</strong><small>This page is polling automatically. The scheduled processor runs once per minute.</small></div></div>:null}
      </Card>
    </div>

    <div className="supplier-safeguards-grid">
      <Card className="supplier-safeguard"><ShieldCheck size={18}/><div><span>Canonical supplier architecture</span><strong>No placeholder provider registry</strong><p>Future suppliers appear only after a real server adapter, credentials boundary, health state and canonical routing integration exist.</p></div><Badge tone="info">Canonical only</Badge></Card>
      <Card className="supplier-safeguard"><ShieldCheck size={18}/><div><span>Secret boundary</span><strong>Supplier credentials stay out of the CMS browser</strong><p><code>FAZERCARDS_API_KEY</code> remains a <code>nextf-gaming-api</code> Worker secret. Funding uses a separate server-to-server CMS credential and requires supplier plus finance permission.</p></div><Badge tone="success">Server-side only</Badge></Card>
    </div>

    <Modal open={fundingOpen} onClose={()=>{if(!fundingBusy)setFundingOpen(false);}} title={fundingRecord?'FazerCards payment':'Add funds to FazerCards'} description={fundingRecord?'Use only the live provider instructions below. Do not send funds after the payment window expires.':'Funding methods and limits come directly from FazerCards. The CMS never stores your wallet seed phrase or Binance credentials.'} footer={fundingRecord?<><Button disabled={fundingBusy} onClick={()=>setFundingOpen(false)}>Close</Button>{paymentExpired?<Button onClick={newFunding} disabled={fundingBusy}>Create new payment</Button>:null}{fundingRecord.state!=='completed'&&fundingRecord.externalPaymentId?<Button onClick={()=>void refreshPayment()} disabled={fundingBusy}><RefreshCw size={14}/>Refresh status</Button>:null}</>:<><Button disabled={fundingBusy} onClick={()=>setFundingOpen(false)}>Cancel</Button><Button variant="primary" disabled={fundingBusy||amountInvalid} onClick={()=>void createFunding()}>{fundingBusy?'Creating…':'Create payment'}</Button></>}>
      {!fundingRecord?<div className="form-grid form-grid--two"><FormField label="Payment method" required><SelectInput value={fundingMethod} onChange={(event)=>setFundingMethod(event.target.value)}>{funding?.methods.map((method)=><option value={method.code} key={method.code}>{method.label}</option>)}</SelectInput></FormField><FormField label="Amount (USD)" hint={selectedMethod?`Allowed ${money(selectedMethod.minAmountUsd)} to ${money(selectedMethod.maxAmountUsd)}`:'Select a payment method.'} required><TextInput type="number" min={selectedMethod?.minAmountUsd} max={selectedMethod?.maxAmountUsd} step="0.01" value={fundingAmount} onChange={(event)=>setFundingAmount(event.target.value)} /></FormField>{fundingAmount&&amountInvalid?<div className="form-error">Enter an amount inside the current FazerCards limit for this method.</div>:null}</div>:<div className="supplier-payment-details">
        <div className="supplier-payment-hero"><div className="supplier-payment-hero__status"><Badge tone={paymentExpired?'danger':stateTone(fundingRecord.state)}>{paymentExpired?'expired locally':fundingRecord.state}</Badge>{paymentCountdown&&!paymentExpired?<span><Clock3 size={13}/>{paymentCountdown}</span>:null}</div><strong>{providerAmount||money(fundingRecord.amountUsd)}{providerAsset?` ${providerAsset}`:''}</strong><small>{recordMethod?.label??fundingRecord.method}{fundingRecord.payment?.network?` · ${fundingRecord.payment.network}`:''}</small></div>
        {paymentExpired?<div className="supplier-payment-expired"><TriangleAlert size={17}/><div><strong>Payment window expired</strong><span>Do not send funds to this payment instruction. Refresh the status, then create a new payment if FazerCards still reports it as expired or cancelled.</span></div></div>:null}
        {fundingRecord.payment?.address?<div className="supplier-payment-address"><span>Payment address</span><code>{fundingRecord.payment.address}</code><Button disabled={paymentExpired} onClick={()=>void copy(fundingRecord.payment!.address!)}><Copy size={13}/>Copy address</Button></div>:null}
        {onChainPayment&&providerAmount?<div className="supplier-arrival-warning"><TriangleAlert size={18}/><div><span>Send this exact amount</span><div className="supplier-arrival-warning__amount"><strong>{providerAmount}{providerAsset?` ${providerAsset}`:''}</strong><Button disabled={paymentExpired} onClick={()=>void copy(providerAmount)}><Copy size={13}/>Copy amount</Button></div><p>The network fee is separate. Exactly <strong>{providerAmount}{providerAsset?` ${providerAsset}`:''}</strong> must arrive at the address. If Binance or your wallet deducts the fee from the sent amount, add the fee on top so the exact provider amount arrives.</p></div></div>:null}
        {fundingRecord.payment?.address&&!paymentExpired?<div className="supplier-payment-qr"><PaymentQr value={fundingRecord.payment.address}/><span>Scan to copy the provider payment address into a compatible wallet.</span></div>:null}
        <div className="supplier-payment-summary"><div><span>Requested funding</span><strong>{money(fundingRecord.amountUsd)}</strong></div><div><span>Method</span><strong>{recordMethod?.label??fundingRecord.method}</strong></div><div><span>Status</span><Badge tone={paymentExpired?'danger':stateTone(fundingRecord.state)}>{paymentExpired?'expired':fundingRecord.state}</Badge></div></div>
        {fundingRecord.payment?.network?<div className="supplier-payment-line"><span>Network</span><strong>{fundingRecord.payment.network}</strong></div>:null}
        {onChainPayment?<div className="supplier-payment-risk-note"><TriangleAlert size={15}/><span>Use only the network shown above. A wrong network, address, memo/tag or amount may cause permanent loss of funds.</span></div>:null}
        {fundingRecord.payment?.memo?<div className="supplier-payment-line"><span>Memo / tag</span><div><code>{fundingRecord.payment.memo}</code><Button disabled={paymentExpired} aria-label="Copy memo" onClick={()=>void copy(fundingRecord.payment!.memo!)}><Copy size={13}/></Button></div></div>:null}
        {fundingRecord.payment?.binanceId?<div className="supplier-payment-line"><span>Binance Pay recipient</span><div><code>{fundingRecord.payment.binanceId}</code><Button disabled={paymentExpired} aria-label="Copy Binance Pay recipient" onClick={()=>void copy(fundingRecord.payment!.binanceId!)}><Copy size={13}/></Button></div></div>:null}
        {fundingRecord.payment?.displayName?<div className="supplier-payment-line"><span>Recipient name</span><strong>{fundingRecord.payment.displayName}</strong></div>:null}
        {fundingRecord.payment?.expiresAt?<div className="supplier-payment-line"><span>Expires</span><strong>{paymentExpired?'Expired':paymentCountdown||gamingDate(fundingRecord.payment.expiresAt)}</strong><small>{gamingDate(fundingRecord.payment.expiresAt)}</small></div>:null}
        {fundingRecord.method==='binancepay'&&fundingRecord.state!=='completed'?<div className="supplier-binance-verify"><FormField label="Binance Order ID" hint={paymentExpired?'This payment window has expired. Create a new payment instead.':'After authorizing the payment in Binance, paste the Binance Order ID here.'} required><TextInput disabled={paymentExpired} value={binanceOrderId} onChange={(event)=>setBinanceOrderId(event.target.value)} placeholder="Binance Order ID"/></FormField><Button variant="primary" disabled={paymentExpired||fundingBusy||!binanceOrderId.trim()} onClick={()=>void verifyBinance()}>{fundingBusy?'Verifying…':'Verify Binance Pay'}</Button></div>:null}
        {fundingRecord.lastError?<div className="supplier-payment-warning"><Activity size={15}/><span>{fundingRecord.lastError}</span></div>:null}
      </div>}
    </Modal>
  </div>;
}
