import { AlertTriangle, CircleDollarSign, KeyRound, PackageCheck, Rocket, ShieldCheck } from "lucide-react";
import { Card, MetricCard, SectionHeader } from "../../shared/components";
import { softwareStore } from "../data/softwareStore";
import { shortDate, usd } from "../shared/format";
import { SoftwareStatus } from "../shared/SoftwareStatus";
import { useSoftwareStore } from "../shared/useSoftwareStore";

export function SoftwareDashboard(){
 const products=useSoftwareStore(softwareStore.getProducts); const releases=useSoftwareStore(softwareStore.getReleases); const licenses=useSoftwareStore(softwareStore.getLicenses); const subs=useSoftwareStore(softwareStore.getSubscriptions); const support=useSoftwareStore(softwareStore.getSupportCases); const activity=useSoftwareStore(softwareStore.getActivity);
 const activeLicenses=licenses.filter((l)=>["active","grace"].includes(l.status)); const arr=subs.filter((s)=>s.status==="active").reduce((sum,s)=>sum+s.amount*(s.interval==="monthly"?12:1),0); const stable=releases.filter((r)=>r.channel==="stable"&&r.status==="published"); const renewals=subs.filter((s)=>new Date(s.nextRenewalAt).getTime()-Date.now()<60*86400000&&new Date(s.nextRenewalAt)>new Date());
 return <div className="page software-dashboard-page"><SectionHeader eyebrow="NEXT F Software" title="Software operations" description="Products, releases, licenses, subscriptions and delivery at a glance."/><div className="compact-metrics"><MetricCard label="Active licenses" value={String(activeLicenses.length)} icon={KeyRound}/><MetricCard label="Software ARR" value={usd(arr)} icon={CircleDollarSign}/><MetricCard label="Stable releases" value={String(stable.length)} icon={PackageCheck}/><MetricCard label="Open support" value={String(support.filter((t)=>!["resolved","closed"].includes(t.status)).length)} icon={ShieldCheck}/></div><div className="dashboard-grid"><Card><div className="operation-section__head"><div><span>Attention</span><h3>Commercial & release health</h3></div><AlertTriangle size={18}/></div><div className="software-attention-list">{renewals.map((s)=><div className="software-attention-row" key={s.id}><div className="software-attention-row__main"><strong>Renewal approaching</strong><p>{licenses.find((l)=>l.id===s.licenseId)?.key} · {shortDate(s.nextRenewalAt)}</p></div><div className="software-attention-row__status"><SoftwareStatus value={s.autoRenew?"active":"pending"}/></div></div>)}{releases.filter((r)=>r.status==="draft").map((r)=><div className="software-attention-row" key={r.id}><div className="software-attention-row__main"><strong>Draft release</strong><p>{products.find((p)=>p.id===r.productId)?.name} v{r.version} · {r.channel.replace(/_/g," ")}</p></div><div className="software-attention-row__status"><SoftwareStatus value="draft"/></div></div>)}{renewals.length===0&&releases.filter((r)=>r.status==="draft").length===0&&<p className="empty-copy">No immediate software attention items.</p>}</div></Card><Card><div className="operation-section__head"><div><span>Activity</span><h3>Software lifecycle</h3></div><Rocket size={18}/></div><div className="software-activity-list">{activity.slice(0,6).map((a)=><div className="software-activity-row" key={a.id}><span className="software-activity-row__marker"/><div><strong>{a.title}</strong><p>{a.detail}</p><small>{shortDate(a.createdAt)}</small></div></div>)}</div></Card></div></div>;
}
