import { useState } from "react";
import { Clock3, Download, FileArchive } from "lucide-react";
import { Badge, Button, Card, DataTable, FormField, MetricCard, SectionHeader, SelectInput, type DataTableColumn } from "../../shared/components";
import { softwareStore, type DownloadRecord } from "../data/softwareStore";
import { shortDate } from "../shared/format";
import { SoftwareStatus } from "../shared/SoftwareStatus";
import { useSoftwareStore } from "../shared/useSoftwareStore";
import { readExternalCapability, readRuntimeTruth } from "../../services/production";

const runtime=readRuntimeTruth();
const deliveryCapability=readExternalCapability("software.license-delivery");

export function DownloadsPage(){
 const rows=useSoftwareStore(softwareStore.getDownloads), licenses=useSoftwareStore(softwareStore.getLicenses), releases=useSoftwareStore(softwareStore.getReleases), products=useSoftwareStore(softwareStore.getProducts), settings=useSoftwareStore(softwareStore.getSettings);
 const [licenseId,setLicenseId]=useState(licenses[0]?.id??""); const eligibleReleases=releases.filter((r)=>r.status==="published"&&r.productId===licenses.find((l)=>l.id===licenseId)?.productId); const [releaseId,setReleaseId]=useState(eligibleReleases[0]?.id??"");
 const cols:DataTableColumn<DownloadRecord>[]=[{key:"file",header:"Download",render:(d)=><div className="entity-cell"><strong>{d.fileName}</strong><small>{products.find((p)=>p.id===d.productId)?.name} · {d.tokenHint}</small></div>},{key:"status",header:"Status",render:(d)=><SoftwareStatus value={new Date(d.expiresAt)<new Date()?"expired":d.status}/>},{key:"usage",header:"Attempts",render:(d)=><strong>{d.downloadCount} / {settings.maxDownloadAttempts}</strong>},{key:"expires",header:"Expires",render:(d)=><span>{shortDate(d.expiresAt)}</span>},{key:"action",header:"",render:(d)=><div className="table-actions">{deliveryCapability.available&&d.status!=="expired"&&d.downloadCount<settings.maxDownloadAttempts?<Button variant="primary" onClick={()=>softwareStore.recordDownload(d.id)}><Download size={14}/> Record test download</Button>:null}{deliveryCapability.available&&d.status!=="expired"?<Button onClick={()=>softwareStore.expireDownload(d.id)}>Expire</Button>:null}{!deliveryCapability.available&&<Button disabled>Delivery not connected</Button>}</div>}];
 return <div className="page"><SectionHeader eyebrow="NEXT F Software" title="Secure Downloads" description="Entitlement-bound software delivery and download records."/><div className="compact-metrics"><MetricCard label="Issued" value={String(rows.length)} icon={FileArchive}/><MetricCard label="Downloaded" value={String(rows.filter((d)=>d.downloadCount>0).length)} icon={Download}/><MetricCard label="Token window" value={`${settings.downloadTokenHours}h`} icon={Clock3}/></div>{!deliveryCapability.available&&<Card className="architecture-callout"><div className="operation-section__head"><div><span>Delivery</span><h3>Signed delivery unavailable</h3></div><Badge tone="warning">Integration not connected</Badge></div><p>Connect the R2/license delivery integration to issue downloads.</p></Card>}<Card className="operation-section"><div className="operation-section__head"><div><span>Entitlement</span><h3>Issue download</h3></div><FileArchive size={18}/></div><div className="form-grid form-grid--two"><FormField label="License"><SelectInput value={licenseId} onChange={(e)=>{const id=e.target.value;setLicenseId(id);setReleaseId(releases.find((r)=>r.status==="published"&&r.productId===licenses.find((l)=>l.id===id)?.productId)?.id??"");}}>{licenses.filter((l)=>["active","grace"].includes(l.status)).map((l)=><option key={l.id} value={l.id}>{l.key}</option>)}</SelectInput></FormField><FormField label="Release"><SelectInput value={releaseId} onChange={(e)=>setReleaseId(e.target.value)}>{releases.filter((r)=>r.status==="published"&&r.productId===licenses.find((l)=>l.id===licenseId)?.productId).map((r)=><option key={r.id} value={r.id}>v{r.version} · {r.channel}</option>)}</SelectInput></FormField></div><div className="modal-actions"><Button variant="primary" disabled={!deliveryCapability.available} onClick={()=>deliveryCapability.available&&licenseId&&releaseId&&softwareStore.issueDownload(licenseId,releaseId)}>{deliveryCapability.available?(runtime.isLocal?"Issue test authorization":"Issue authorization"):"Integration not connected"}</Button></div></Card><Card><DataTable rows={rows} columns={cols} getKey={(d)=>d.id}/></Card></div>;
}
