import { useMemo, useState } from "react";
import { Eye, Plus, ShoppingBag } from "lucide-react";
import { Button, Card, ConfirmDialog, DataTable, Drawer, FormField, KeyValueList, MetricCard, Modal, PageToolbar, SectionHeader, SelectInput, TextInput, type DataTableColumn } from "../../shared/components";
import { useToast } from "../../shared/feedback/ToastProvider";
import { firstError, validators } from "../../shared/validation";
import { gamingStore, orderReconciliation, type GamingOrder } from "../data/gamingStore";
import { gamingDate, gamingLabel, gamingLkr } from "../shared/format";
import { GamingStatus } from "../shared/GamingStatus";
import { useGamingStore } from "../shared/useGamingStore";

function nextLabel(status: string) { return ({ payment_pending:"Confirm payment", paid:"Validate", validating:"Submit supplier", submitted:"Processing", processing:"Complete" } as Record<string,string>)[status]; }

type GuardedAction = "refund" | "complete-refund" | null;

export function OrdersPage() {
  const orders = useGamingStore(gamingStore.getOrders); const products = useGamingStore(gamingStore.getProducts); const customers = useGamingStore(gamingStore.getCustomers); const suppliers = useGamingStore(gamingStore.getSuppliers);
  const { notify } = useToast();
  const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [open,setOpen]=useState(false); const [productId,setProductId]=useState(products.find((p)=>p.enabled)?.id ?? ""); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [phone,setPhone]=useState(""); const [fields,setFields]=useState<Record<string,string>>({}); const [attempted,setAttempted]=useState(false); const [selectedId,setSelectedId]=useState<string|null>(null); const [guardedAction,setGuardedAction]=useState<GuardedAction>(null);
  const selectedProduct=products.find((p)=>p.id===productId); const selectedOrder=orders.find((o)=>o.id===selectedId)??null;
  const rows=useMemo(()=>orders.filter((o)=>{const customer=customers.find((c)=>c.id===o.customerId); const product=products.find((p)=>p.id===o.productId); const match=`${o.number} ${customer?.name??""} ${customer?.email??""} ${product?.name??""}`.toLowerCase().includes(query.toLowerCase()); return match&&(filter==="all"||o.status===filter);}),[orders,customers,products,query,filter]);
  const columns:DataTableColumn<GamingOrder>[]=[
    {key:"order",header:"Order",render:(o)=><div className="entity-cell"><strong>{o.number}</strong><small>{gamingDate(o.createdAt)}</small></div>},
    {key:"customer",header:"Customer",render:(o)=><div className="entity-cell"><strong>{customers.find((c)=>c.id===o.customerId)?.name??"Unknown"}</strong><small>{customers.find((c)=>c.id===o.customerId)?.email??""}</small></div>},
    {key:"product",header:"Product",render:(o)=><div className="entity-cell"><strong>{products.find((p)=>p.id===o.productId)?.name??"Unknown"}</strong><small>{Object.entries(o.accountFields).map(([k,v])=>`${k}: ${v}`).join(" · ")}</small></div>},
    {key:"value",header:"Value",render:(o)=><div className="entity-cell"><strong>{gamingLkr(o.sellingPrice)}</strong><small>Profit {gamingLkr(o.profit)}</small></div>},
    {key:"status",header:"Status",render:(o)=><GamingStatus value={o.status}/>},
    {key:"recon",header:"Reconciliation",render:(o)=><GamingStatus value={orderReconciliation(o)}/>},
    {key:"action",header:"",width:"100px",render:(o)=><Button onClick={()=>setSelectedId(o.id)}><Eye size={13}/>View</Button>},
  ];
  const nameError=attempted?validators.required(name,"Customer name"):""; const emailError=attempted?firstError(validators.required(email,"Email"),email.trim()?validators.email(email):""):""; const requiredFieldErrors=Object.fromEntries((selectedProduct?.requiredFields??[]).map((field)=>[field,attempted?validators.required(fields[field]??"",field):""]));
  const create=()=>{setAttempted(true);if(!selectedProduct||nameError||emailError||Object.values(requiredFieldErrors).some(Boolean)||!name.trim()||!email.trim())return; const order=gamingStore.createOrder({customerName:name.trim(),email:email.trim(),phone:phone.trim(),productId:selectedProduct.id,accountFields:fields}); if(!order){notify({title:"Order not created",description:"The selected product is not currently available.",tone:"danger"});return;} notify({title:"Order created",description:`${order.number} is ready for payment confirmation.`,tone:"success"}); setOpen(false); setAttempted(false); setName("");setEmail("");setPhone("");setFields({}); setSelectedId(order.id);};
  const advance=()=>{if(!selectedOrder)return; const before=selectedOrder.status; const updated=gamingStore.advanceOrder(selectedOrder.id); if(updated)notify({title:"Order updated",description:`${selectedOrder.number}: ${gamingLabel(before)} → ${gamingLabel(updated.status)}.`,tone:updated.status==="failed"?"danger":"success"});};
  const guarded=()=>{if(!selectedOrder||!guardedAction)return; if(guardedAction==="refund"){gamingStore.requestRefund(selectedOrder.id);notify({title:"Refund review started",description:`${selectedOrder.number} moved to refund pending.`,tone:"info"});}else{gamingStore.completeRefund(selectedOrder.id);notify({title:"Refund completed",description:`${selectedOrder.number} was recorded as refunded.`,tone:"success"});}};
  return <div className="page"><SectionHeader eyebrow="Gaming Store" title="Orders" description="Track payment, validation, supplier fulfillment, completion, failure and refunds as separate operational states." />
    <div className="compact-metrics"><MetricCard label="Total orders" value={String(orders.length)} detail="Local operations" icon={ShoppingBag}/><MetricCard label="Processing" value={String(orders.filter((o)=>["validating","submitted","processing"].includes(o.status)).length)} detail="In fulfillment" icon={ShoppingBag}/><MetricCard label="Failed / refund" value={String(orders.filter((o)=>["failed","refund_pending"].includes(o.status)).length)} detail="Needs review" icon={ShoppingBag}/></div>
    <Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search orders…"><SelectInput value={filter} onChange={(e)=>setFilter(e.target.value)}><option value="all">All states</option>{["payment_pending","paid","validating","submitted","processing","completed","failed","refund_pending","refunded"].map((s)=><option key={s} value={s}>{gamingLabel(s)}</option>)}</SelectInput><Button variant="primary" onClick={()=>{setAttempted(false);setOpen(true);}}><Plus size={15}/> New order</Button></PageToolbar><DataTable rows={rows} columns={columns} getKey={(o)=>o.id}/></Card>
    <Modal open={open} onClose={()=>setOpen(false)} title="Create local Gaming order" description="Simulate the storefront handoff before a payment gateway and supplier API are connected." footer={<><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="primary" onClick={create}>Create order</Button></>}><div className="form-grid"><FormField label="Customer name" required error={nameError}><TextInput aria-invalid={!!nameError} value={name} onChange={(e)=>setName(e.target.value)}/></FormField><FormField label="Email" required error={emailError}><TextInput aria-invalid={!!emailError} type="email" value={email} onChange={(e)=>setEmail(e.target.value)}/></FormField><FormField label="Phone"><TextInput value={phone} onChange={(e)=>setPhone(e.target.value)}/></FormField><FormField label="Product" required><SelectInput value={productId} onChange={(e)=>{setProductId(e.target.value);setFields({});}}>{products.filter((p)=>p.enabled&&p.availability==="available").map((p)=><option value={p.id} key={p.id}>{p.name} · {gamingLkr(p.sellingPrice)}</option>)}</SelectInput></FormField>{selectedProduct?.requiredFields.map((field)=><FormField key={field} label={field} required error={requiredFieldErrors[field]}><TextInput aria-invalid={!!requiredFieldErrors[field]} value={fields[field]??""} onChange={(e)=>setFields({...fields,[field]:e.target.value})}/></FormField>)}</div></Modal>
    <Drawer open={!!selectedOrder} onClose={()=>setSelectedId(null)} title={selectedOrder?.number??"Order"} description={selectedOrder?`${products.find((p)=>p.id===selectedOrder.productId)?.name??"Product"} · ${customers.find((c)=>c.id===selectedOrder.customerId)?.name??"Customer"}`:undefined} footer={selectedOrder?<>{nextLabel(selectedOrder.status)&&<Button variant="primary" onClick={advance}>{nextLabel(selectedOrder.status)}</Button>}{selectedOrder.status==="failed"&&selectedOrder.customerPaid&&<Button className="button--danger" onClick={()=>setGuardedAction("refund")}>Start refund</Button>}{selectedOrder.status==="refund_pending"&&<Button className="button--danger" onClick={()=>setGuardedAction("complete-refund")}>Complete refund</Button>}</>:undefined}>{selectedOrder&&<><div className="record-detail-section"><h4>Order state</h4><KeyValueList items={[{label:"Status",value:<GamingStatus value={selectedOrder.status}/>},{label:"Reconciliation",value:<GamingStatus value={orderReconciliation(selectedOrder)}/>},{label:"Created",value:gamingDate(selectedOrder.createdAt)},{label:"Supplier order",value:selectedOrder.supplierOrderId??"Not submitted"},{label:"Idempotency key",value:selectedOrder.idempotencyKey}]}/></div><div className="record-detail-section"><h4>Account fields</h4><KeyValueList items={Object.entries(selectedOrder.accountFields).map(([label,value])=>({label,value}))}/></div><div className="record-detail-section"><h4>Financials</h4><KeyValueList items={[{label:"Customer price",value:gamingLkr(selectedOrder.sellingPrice)},{label:"Supplier cost",value:gamingLkr(selectedOrder.supplierCostLkr)},{label:"Gateway fee",value:gamingLkr(selectedOrder.gatewayFee)},{label:"Recorded profit",value:gamingLkr(selectedOrder.profit)},{label:"Customer paid",value:selectedOrder.customerPaid?"Yes":"No"},{label:"Supplier charged",value:selectedOrder.supplierCharged?"Yes":"No"},{label:"Supplier",value:suppliers.find((s)=>s.id===selectedOrder.supplierId)?.name??"Unknown"}]}/></div>{selectedOrder.failureReason&&<div className="record-detail-section"><h4>Failure reason</h4><p>{selectedOrder.failureReason}</p></div>}</>}</Drawer>
    <ConfirmDialog open={!!guardedAction} onClose={()=>setGuardedAction(null)} title={guardedAction==="refund"?"Start refund review?":"Complete refund?"} description={selectedOrder?`${selectedOrder.number} is a financial record. ${guardedAction==="refund"?"This moves the order into refund review.":"This records the customer refund as completed and changes the order economics."}`:""} confirmLabel={guardedAction==="refund"?"Start refund":"Complete refund"} danger onConfirm={guarded}/>
  </div>;
}
