import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Download, RefreshCw, ShieldAlert, ShieldCheck, TriangleAlert } from "lucide-react";
import { Badge, Button, Card, MetricCard, PageToolbar, SectionHeader, SelectInput } from "../../shared/components";
import { downloadCsv } from "../../shared/utils/csv";
import { runFinalAcceptance, type AcceptanceCategory, type AcceptanceStatus } from "../../services/acceptance/finalAcceptance";
import { APP_RELEASE, APP_VERSION } from "../../app/version";
import { useToast } from "../../shared/feedback/ToastProvider";

const tone = (status:AcceptanceStatus) => status==="pass"?"success":status==="warning"?"warning":status==="fail"?"danger":"info";
const icon = (status:AcceptanceStatus) => status==="pass"?<CheckCircle2 size={17}/>:status==="fail"?<ShieldAlert size={17}/>:<TriangleAlert size={17}/>;

export function AcceptancePage(){
  const [revision,setRevision]=useState(0); const [query,setQuery]=useState(""); const [category,setCategory]=useState<"all"|AcceptanceCategory>("all"); const [status,setStatus]=useState<"all"|AcceptanceStatus>("all"); const {notify}=useToast();
  useEffect(()=>{ const refresh=()=>setRevision((value)=>value+1); const events=["nextf:platform-store","nextf:digital-store","nextf:gaming-store","nextf:software-store","storage"]; events.forEach((event)=>window.addEventListener(event,refresh)); return()=>events.forEach((event)=>window.removeEventListener(event,refresh)); },[]);
  const report=useMemo(()=>runFinalAcceptance(),[revision]);
  const rows=useMemo(()=>report.checks.filter((item)=>{ const match=`${item.category} ${item.label} ${item.detail}`.toLowerCase().includes(query.toLowerCase()); return match&&(category==="all"||item.category===category)&&(status==="all"||item.status===status); }),[report,query,category,status]);
  const categories=Array.from(new Set(report.checks.map((item)=>item.category)));
  const rerun=()=>{setRevision((value)=>value+1);notify({title:"Acceptance checks rerun",description:"The CMS data and product invariants were evaluated again.",tone:"success"});};
  const exportReport=()=>{downloadCsv(`next-f-cms-v${APP_VERSION}-acceptance.csv`,report.checks,[{header:"Category",value:(row)=>row.category},{header:"Check",value:(row)=>row.label},{header:"Status",value:(row)=>row.status},{header:"Detail",value:(row)=>row.detail}]);notify({title:"Acceptance report exported",description:`${report.checks.length} checks exported to CSV.`,tone:"success"});};
  return <div className="page"><SectionHeader eyebrow="Platform" title="Final Product Acceptance" description={`V${APP_VERSION} ${APP_RELEASE}. Product-layer completion gate before production infrastructure integration.`} action={<div className="table-actions"><Button onClick={rerun}><RefreshCw size={15}/>Run checks</Button><Button variant="primary" onClick={exportReport}><Download size={15}/>Export report</Button></div>}/>
    <div className="metric-grid"><MetricCard label="Acceptance score" value={`${report.score}%`} icon={report.productReady?ShieldCheck:ShieldAlert}/><MetricCard label="Passed" value={String(report.pass)} icon={CheckCircle2}/><MetricCard label="Warnings" value={String(report.warning)} icon={TriangleAlert}/><MetricCard label="Failures" value={String(report.fail)} icon={ShieldAlert}/></div>
    <Card className={`acceptance-banner ${report.productReady?"is-ready":"is-blocked"}`}><span className="acceptance-banner__icon">{report.productReady?<ShieldCheck size={24}/>:<ShieldAlert size={24}/>}</span><div><small>CMS completion gate</small><strong>{report.productReady?"Product ready for infrastructure stage":"Product acceptance blocked"}</strong><p>{report.productReady?"No blocking product/data-integrity failures were found. Production services remain intentionally unconfigured.":"Resolve every failed acceptance check before beginning Cloudflare integration."}</p><span>Last evaluated {new Intl.DateTimeFormat("en-LK",{dateStyle:"medium",timeStyle:"medium"}).format(new Date(report.generatedAt))}</span></div></Card>
    <Card><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search acceptance checks…"><SelectInput value={category} onChange={(e)=>setCategory(e.target.value as typeof category)}><option value="all">All categories</option>{categories.map((item)=><option key={item} value={item}>{item}</option>)}</SelectInput><SelectInput value={status} onChange={(e)=>setStatus(e.target.value as typeof status)}><option value="all">All states</option><option value="pass">Passed</option><option value="warning">Warnings</option><option value="fail">Failures</option><option value="deferred">Deferred</option></SelectInput></PageToolbar><div className="acceptance-list">{rows.map((item)=><div className="acceptance-row" key={item.id}><span className={`acceptance-row__icon is-${item.status}`}>{icon(item.status)}</span><span className="acceptance-row__body"><small>{item.category}</small><strong>{item.label}</strong><p>{item.detail}</p></span><Badge tone={tone(item.status)}>{item.status}</Badge></div>)}</div></Card>
  </div>;
}
