import { useState } from "react";
import { PackageCheck, RefreshCw, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, DataTable, FormField, MetricCard, SectionHeader, SelectInput, TextInput, type DataTableColumn } from "../../shared/components";
import { softwareStore, type UpdateCheck } from "../data/softwareStore";
import { shortDate } from "../shared/format";
import { SoftwareStatus } from "../shared/SoftwareStatus";
import { useSoftwareStore } from "../shared/useSoftwareStore";
import { readExternalCapability, readRuntimeTruth } from "../../services/production";

const runtime=readRuntimeTruth();
const updateCapability=readExternalCapability("software.update-service");

export function UpdatesPage(){
 const checks=useSoftwareStore(softwareStore.getUpdates), licenses=useSoftwareStore(softwareStore.getLicenses), products=useSoftwareStore(softwareStore.getProducts); const [licenseId,setLicenseId]=useState(licenses[0]?.id??""); const [version,setVersion]=useState("1.0.0");
 const cols:DataTableColumn<UpdateCheck>[]=[{key:"license",header:"License",render:(u)=><div className="entity-cell"><strong>{licenses.find((l)=>l.id===u.licenseId)?.key}</strong><small>{products.find((p)=>p.id===u.productId)?.name}</small></div>},{key:"current",header:"Current",render:(u)=><span>v{u.currentVersion}</span>},{key:"available",header:"Available",render:(u)=><strong>{u.availableVersion?`v${u.availableVersion}`:"—"}</strong>},{key:"eligible",header:"Eligibility",render:(u)=><SoftwareStatus value={u.eligible?"eligible":"blocked"}/>},{key:"reason",header:"Decision",render:(u)=><span>{u.reason}</span>},{key:"time",header:"Checked",render:(u)=><span>{shortDate(u.checkedAt)}</span>}];
 return <div className="page"><SectionHeader eyebrow="NEXT F Software" title="Update Entitlement" description="Check license entitlement against available software releases."/><div className="compact-metrics"><MetricCard label="Checks" value={String(checks.length)} icon={RefreshCw}/><MetricCard label="Eligible" value={String(checks.filter((u)=>u.eligible).length)} icon={PackageCheck}/><MetricCard label="Blocked" value={String(checks.filter((u)=>!u.eligible).length)} icon={ShieldCheck}/></div>{!updateCapability.available&&<Card className="architecture-callout"><div className="operation-section__head"><div><span>Update service</span><h3>Update checks unavailable</h3></div><Badge tone="warning">Integration not connected</Badge></div><p>Connect the update service to run entitlement checks.</p></Card>}<Card className="operation-section"><div className="operation-section__head"><div><span>{runtime.isLocal?"Simulator":"Update service"}</span><h3>Run update check</h3></div><PackageCheck size={18}/></div><div className="form-grid form-grid--two"><FormField label="License"><SelectInput value={licenseId} onChange={(e)=>setLicenseId(e.target.value)}>{licenses.map((l)=><option key={l.id} value={l.id}>{l.key}</option>)}</SelectInput></FormField><FormField label="Installed version"><TextInput value={version} onChange={(e)=>setVersion(e.target.value)}/></FormField></div><div className="modal-actions"><Button variant="primary" disabled={!updateCapability.available} onClick={()=>updateCapability.available&&licenseId&&softwareStore.checkUpdate(licenseId,version)}>{updateCapability.available?"Check entitlement":"Integration not connected"}</Button></div></Card><Card><DataTable rows={checks} columns={cols} getKey={(u)=>u.id} empty="No update checks recorded."/></Card></div>;
}
