import { LockKeyhole, ShieldAlert, ShieldCheck, UserRoundX } from "lucide-react";
import { Badge, Button, Card, ConfirmDialog, MetricCard, SectionHeader, Toggle } from "../../shared/components";
import { platformOperationsStore } from "../services/platformOperationsStore";
import { usePlatformOperations } from "../shared/usePlatformOperations";
import { useState } from "react";
import { useToast } from "../../shared/feedback/ToastProvider";
import { readRuntimeTruth } from "../../services/production";

const runtime=readRuntimeTruth();

export function SecurityPage(){
  const policies=usePlatformOperations(platformOperationsStore.getSecurityPolicies);const sessions=usePlatformOperations(platformOperationsStore.getSecuritySessions);const events=usePlatformOperations(platformOperationsStore.getSecurityEvents);const [revoke,setRevoke]=useState<string|null>(null);const {notify}=useToast();
  if(runtime.mode==="production-api") return <div className="page security-page"><SectionHeader eyebrow="Platform" title="Security Center" description="Cloudflare Access authentication, sessions and security events."/><div className="compact-metrics"><MetricCard label="Authentication" value="Access" icon={ShieldCheck}/><MetricCard label="MFA" value="External" icon={LockKeyhole}/><MetricCard label="CMS session controls" value="Read only" icon={UserRoundX}/><MetricCard label="Security events" value={String(events.length)} icon={ShieldAlert}/></div><Card><div className="operation-section__head"><div><span>Authority</span><h3>Cloudflare Access</h3></div><Badge tone="success">Verified boundary</Badge></div><p>Authentication and session policy are managed in Cloudflare Zero Trust.</p></Card><Card><div className="operation-section__head"><div><span>CMS evidence</span><h3>Security events</h3></div></div>{events.length?events.map((e)=><div className="mini-record" key={e.id}><div><strong>{e.title}</strong><small>{e.detail}</small></div><span>{e.tone}</span></div>):<p className="empty-copy">No CMS security events are currently recorded.</p>}</Card></div>;
  return <div className="page security-page"><SectionHeader eyebrow="Platform" title="Security Center" description="Local development security state."/><div className="compact-metrics"><MetricCard label="Required controls" value={String(policies.filter((p)=>p.severity==="required"&&p.enabled).length)} icon={ShieldCheck}/><MetricCard label="Active sessions" value={String(sessions.filter((s)=>s.status==="active").length)} icon={LockKeyhole}/><MetricCard label="Security events" value={String(events.length)} icon={ShieldAlert}/></div><Card><div className="operation-section__head"><div><span>Policy</span><h3>Local security controls</h3></div><ShieldCheck size={18}/></div><div className="settings-rows">{policies.map((p)=><div className="settings-row" key={p.id}><span><strong>{p.name}</strong><small>{p.description} · {p.severity}</small></span><Toggle checked={p.enabled} onChange={(v)=>platformOperationsStore.updateSecurityPolicy(p.id,v)}/></div>)}</div></Card><Card><div className="operation-section__head"><div><span>Access</span><h3>Local administrative sessions</h3></div><UserRoundX size={18}/></div><div className="workflow-list">{sessions.map((s)=><div className="workflow-row" key={s.id}><div className="workflow-row__main"><strong>{s.device}</strong><p>{s.location}</p></div><div className="workflow-row__meta"><span>{s.status}</span><small>{new Date(s.lastSeenAt).toLocaleString("en-LK")}</small></div><div className="workflow-row__actions">{s.status==="active"&&<Button onClick={()=>setRevoke(s.id)}>Revoke</Button>}</div></div>)}</div></Card><Card><div className="operation-section__head"><div><span>Review</span><h3>Security events</h3></div></div>{events.map((e)=><div className="mini-record" key={e.id}><div><strong>{e.title}</strong><small>{e.detail}</small></div><span>{e.tone}</span></div>)}</Card><ConfirmDialog open={!!revoke} title="Revoke local session?" description="The selected session will be marked revoked." confirmLabel="Revoke session" danger onClose={()=>setRevoke(null)} onConfirm={()=>{if(revoke)platformOperationsStore.revokeSession(revoke);notify({title:"Session revoked",tone:"success"});setRevoke(null);}}/></div>;
}
