import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Clock3, LifeBuoy, MessageSquareText, Plus, RefreshCw, ShieldCheck, UserRoundCheck } from "lucide-react";
import { Badge, Button, Card, DataTable, Drawer, FormField, MetricCard, Modal, SectionHeader, SelectInput, StatePanel, TextInput, type DataTableColumn } from "../../shared/components";
import { useToast } from "../../shared/feedback/ToastProvider";
import { GamingStatus } from "../shared/GamingStatus";
import { gamingDate, gamingLkr } from "../shared/format";
import { commandGamingSupportCase, createGamingSupportCase, loadGamingSupportSnapshot, type GamingSupportCase, type GamingSupportSnapshot, type SupportCreateInput } from "./support";
import { MediaUploadButton } from "../media/MediaUploadButton";
import { privateMediaDownloadUrl } from "../media/media";

const categories: Array<[SupportCreateInput['category'],string]>=[["payment","Payment"],["fulfillment","Fulfillment"],["refund","Refund"],["account_details","Account details"],["delivery","Delivery"],["promotion","Promotion"],["duplicate_order","Duplicate order"],["other","Other"]];
const label=(value:string)=>value.replace(/_/g," ").replace(/(^|\s)\S/g,(c)=>c.toUpperCase());
const slaTone=(row:GamingSupportCase)=>row.sla.firstResponseBreached||row.sla.resolutionBreached?"danger":row.priority==="urgent"?"warning":"neutral";

export function SupportPage(){
  const {notify}=useToast();
  const [snapshot,setSnapshot]=useState<GamingSupportSnapshot>(); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<GamingSupportCase>(); const [createOpen,setCreateOpen]=useState(false);
  const [orderId,setOrderId]=useState(""); const [category,setCategory]=useState<SupportCreateInput['category']>("fulfillment"); const [priority,setPriority]=useState<SupportCreateInput['priority']>("normal"); const [subject,setSubject]=useState(""); const [initialNote,setInitialNote]=useState("");
  const [note,setNote]=useState(""); const [customerMessage,setCustomerMessage]=useState(""); const [evidenceLabel,setEvidenceLabel]=useState(""); const [evidenceReference,setEvidenceReference]=useState("");
  const refresh=async()=>{setLoading(true);setError("");try{const data=await loadGamingSupportSnapshot();setSnapshot(data);setSelected((current)=>current?data.cases.find((row)=>row.caseId===current.caseId):undefined);setOrderId((current)=>current||data.orders[0]?.orderId||"");}catch(e){setError(e instanceof Error?e.message:"Unable to load support cases.");}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[]);
  const run=async(fn:()=>Promise<unknown>,success:string)=>{setBusy(true);try{await fn();notify({title:success,tone:"success"});await refresh();}catch(e){notify({title:"Support action failed",description:e instanceof Error?e.message:"The support action could not be completed.",tone:"danger"});}finally{setBusy(false);}};
  const create=()=>run(async()=>{await createGamingSupportCase({orderId,category,subject,priority,...(initialNote.trim()?{initialNote:initialNote.trim()}: {})});setCreateOpen(false);setSubject("");setInitialNote("");},"Support case created");
  const command=(action:Parameters<typeof commandGamingSupportCase>[0]['action'],extra:Record<string,unknown>={})=>selected?run(()=>commandGamingSupportCase({caseId:selected.caseId,action,...extra} as never),"Support case updated"):Promise.resolve();
  const messages=useMemo(()=>snapshot?.messages.filter((row)=>row.caseId===selected?.caseId).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))||[],[snapshot,selected]);
  const evidence=useMemo(()=>snapshot?.evidence.filter((row)=>row.caseId===selected?.caseId)||[],[snapshot,selected]);
  const rows=useMemo(()=>[...(snapshot?.cases||[])].sort((a,b)=>{const activeA=['resolved','closed'].includes(a.status)?1:0;const activeB=['resolved','closed'].includes(b.status)?1:0;if(activeA!==activeB)return activeA-activeB;const p={urgent:0,high:1,normal:2};return p[a.priority]-p[b.priority]||b.updatedAt.localeCompare(a.updatedAt);}),[snapshot]);
  const cols:DataTableColumn<GamingSupportCase>[]=[
    {key:"case",header:"Case",render:(c)=><Button variant="ghost" onClick={()=>setSelected(c)}><strong>{c.caseNumber}</strong></Button>},
    {key:"issue",header:"Issue",render:(c)=><div className="entity-cell"><strong>{c.subject}</strong><small>{label(c.category)} · {c.orderNumber}</small></div>},
    {key:"context",header:"Order context",render:(c)=><div className="entity-cell"><strong>{c.orderContext.productName||c.orderContext.offerName||"Gaming order"}</strong><small>{c.orderContext.orderStatus} · {c.orderContext.paymentState} · {gamingLkr(c.orderContext.amountLkr)}</small></div>},
    {key:"priority",header:"Priority",render:(c)=><GamingStatus value={c.priority}/>},
    {key:"status",header:"Status",render:(c)=><GamingStatus value={c.status}/>},
    {key:"sla",header:"SLA",render:(c)=><Badge tone={slaTone(c)}>{c.sla.firstResponseBreached||c.sla.resolutionBreached?"Breached":c.sla.firstRespondedAt?`Resolve by ${gamingDate(c.sla.resolutionDueAt)}`:`Respond by ${gamingDate(c.sla.firstResponseDueAt)}`}</Badge>},
  ];
  if(loading&&!snapshot)return <StatePanel state="loading" title="Loading support operations" description="Reading canonical support cases from the shared Gaming commerce database."/>;
  if(error&&!snapshot)return <StatePanel state="error" title="Support operations unavailable" description={error} action={<Button onClick={()=>void refresh()}><RefreshCw size={14}/> Retry</Button>}/>;
  const summary=snapshot?.summary;
  return <div className="page">
    <SectionHeader eyebrow="Gaming Store" title="Support & Disputes" description="Canonical order-linked support cases, SLA tracking, operator notes and customer communications." action={<div className="table-actions"><Button onClick={()=>void refresh()}><RefreshCw size={14}/> Refresh</Button><Button variant="primary" disabled={!snapshot?.capabilities.manage} onClick={()=>setCreateOpen(true)}><Plus size={14}/> New case</Button></div>}/>
    <div className="compact-metrics"><MetricCard label="Active cases" value={String((summary?.open||0)+(summary?.inProgress||0)+(summary?.waitingCustomer||0)+(summary?.waitingInternal||0))} detail={`${summary?.total||0} total`} icon={LifeBuoy}/><MetricCard label="Urgent" value={String(summary?.urgent||0)} detail="Active urgent cases" icon={AlertTriangle}/><MetricCard label="SLA breached" value={String(summary?.slaBreached||0)} detail="Needs immediate attention" icon={Clock3}/><MetricCard label="Waiting customer" value={String(summary?.waitingCustomer||0)} detail="Customer response pending" icon={MessageSquareText}/></div>
    {!snapshot?.capabilities.manage&&<Card className="architecture-callout"><div className="operation-section__head"><div><span>Read-only boundary</span><h3>Support command bridge is not available</h3></div><Badge tone="warning">Read only</Badge></div><p>Cases remain visible from shared D1, but mutations require Gaming order-management permission and the dedicated CMS support bridge credential.</p></Card>}
    <Card><DataTable rows={rows} columns={cols} getKey={(row)=>row.caseId} empty="No canonical Gaming support cases yet."/></Card>

    <Modal open={createOpen} onClose={()=>setCreateOpen(false)} title="Create support case" description="Cases are permanently linked to the selected Gaming order." footer={<><Button onClick={()=>setCreateOpen(false)}>Cancel</Button><Button variant="primary" disabled={busy||!orderId||subject.trim().length<4} onClick={()=>void create()}>Create case</Button></>}>
      <div className="form-grid form-grid--two"><FormField label="Order" required><SelectInput value={orderId} onChange={(e)=>setOrderId(e.target.value)}>{snapshot?.orders.map((order)=><option key={order.orderId} value={order.orderId}>{order.orderNumber} · {order.status}</option>)}</SelectInput></FormField><FormField label="Category" required><SelectInput value={category} onChange={(e)=>setCategory(e.target.value as SupportCreateInput['category'])}>{categories.map(([value,name])=><option key={value} value={value}>{name}</option>)}</SelectInput></FormField><FormField label="Priority"><SelectInput value={priority} onChange={(e)=>setPriority(e.target.value as SupportCreateInput['priority'])}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></SelectInput></FormField><FormField label="Subject" required><TextInput value={subject} onChange={(e)=>setSubject(e.target.value)} placeholder="Short issue summary"/></FormField></div><FormField label="Initial internal note" hint="Optional. This note is never emailed to the customer."><textarea className="text-input" rows={4} value={initialNote} onChange={(e)=>setInitialNote(e.target.value)}/></FormField>
    </Modal>

    <Drawer open={Boolean(selected)} onClose={()=>setSelected(undefined)} title={selected?.caseNumber||"Support case"} description={selected?`${selected.subject} · ${selected.orderNumber}`:undefined}>
      {selected&&<div className="settings-stack">
        <Card className="operation-section"><div className="operation-section__head"><div><span>Case state</span><h3>{selected.subject}</h3></div><GamingStatus value={selected.status}/></div><div className="form-grid form-grid--two"><FormField label="Status"><SelectInput disabled={!snapshot?.capabilities.manage||busy} value={selected.status} onChange={(e)=>void command('set_status',{status:e.target.value})}>{['open','in_progress','waiting_customer','waiting_internal','resolved','closed'].map((v)=><option key={v} value={v}>{label(v)}</option>)}</SelectInput></FormField><FormField label="Priority"><SelectInput disabled={!snapshot?.capabilities.manage||busy} value={selected.priority} onChange={(e)=>void command('set_priority',{priority:e.target.value})}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></SelectInput></FormField></div><div className="table-actions"><Button disabled={!snapshot?.capabilities.manage||busy} onClick={()=>void command('assign_self')}><UserRoundCheck size={14}/> Assign to me</Button>{selected.assignee&&<Button disabled={!snapshot?.capabilities.manage||busy} onClick={()=>void command('unassign')}>Unassign</Button>}</div><p><strong>SLA:</strong> first response {gamingDate(selected.sla.firstResponseDueAt)} · resolution {gamingDate(selected.sla.resolutionDueAt)}</p></Card>
        <Card className="operation-section"><div className="operation-section__head"><div><span>Commerce context</span><h3>{selected.orderContext.productName||selected.orderContext.offerName}</h3></div><ShieldCheck size={18}/></div><p>{selected.orderNumber} · {gamingLkr(selected.orderContext.amountLkr)} · order {selected.orderContext.orderStatus} · payment {selected.orderContext.paymentState}{selected.orderContext.fulfillmentState?` · fulfillment ${selected.orderContext.fulfillmentState}`:""}</p>{selected.orderContext.risk&&<p>Risk: {selected.orderContext.risk.level} / {selected.orderContext.risk.state} ({selected.orderContext.risk.score})</p>}{selected.orderContext.refundStates.length>0&&<p>Refunds: {selected.orderContext.refundStates.join(", ")}</p>}</Card>
        <Card className="operation-section"><div className="operation-section__head"><div><span>Conversation</span><h3>Case messages</h3></div><MessageSquareText size={18}/></div>{messages.length===0?<p>No case messages yet.</p>:messages.map((m)=><div className="architecture-callout" key={m.messageId}><div className="operation-section__head"><div><span>{m.visibility==='customer'?'Customer message':'Internal note'} · {gamingDate(m.createdAt)}</span><h3>{m.author.accountId}</h3></div><Badge tone={m.visibility==='customer'?'info':'neutral'}>{m.visibility}</Badge></div><p>{m.body}</p></div>)}
          <FormField label="Internal note" hint="Visible only to staff."><textarea className="text-input" rows={3} value={note} onChange={(e)=>setNote(e.target.value)}/></FormField><Button disabled={!snapshot?.capabilities.manage||busy||!note.trim()} onClick={()=>void run(async()=>{await commandGamingSupportCase({caseId:selected.caseId,action:'add_internal_note',body:note.trim()});setNote("");},"Internal note added")}>Add internal note</Button>
          <FormField label="Customer message" hint="Creates a transactional support email through the existing notification outbox when email is enabled."><textarea className="text-input" rows={4} value={customerMessage} onChange={(e)=>setCustomerMessage(e.target.value)}/></FormField><Button variant="primary" disabled={!snapshot?.capabilities.manage||busy||!customerMessage.trim()} onClick={()=>void run(async()=>{await commandGamingSupportCase({caseId:selected.caseId,action:'send_customer_message',body:customerMessage.trim()});setCustomerMessage("");},"Customer message queued")}>Send customer update</Button>
        </Card>
        <Card className="operation-section"><div className="operation-section__head"><div><span>Evidence boundary</span><h3>Governed support evidence</h3></div><LifeBuoy size={18}/></div><p>Private screenshots/images/PDFs are stored in NEXT F Media and require authenticated CMS access. Payment reconciliation secrets remain in Finance.</p>{evidence.map((e)=><div className="mini-record" key={e.evidenceId}><div><strong>{e.label}</strong><small>{e.kind==="media_asset"?"Private NEXT F Media evidence":e.reference}</small></div>{e.kind==="media_asset"?<Button onClick={()=>window.open(privateMediaDownloadUrl(e.reference),"_blank","noopener,noreferrer")}>Open evidence</Button>:null}</div>)}<div className="table-actions"><MediaUploadButton purpose="support_evidence" owner={{ownerId:selected.caseId,orderId:selected.orderId}} accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" label="Upload private evidence" disabled={!snapshot?.capabilities.manage||busy} onUploaded={async(asset)=>{await run(()=>commandGamingSupportCase({caseId:selected.caseId,action:'add_evidence',kind:'media_asset',label:asset.fileName,reference:asset.assetId}),"Evidence uploaded");}} onError={(message)=>notify({title:"Evidence upload failed",description:message,tone:"danger"})}/></div><div className="form-grid form-grid--two"><FormField label="Reference label"><TextInput value={evidenceLabel} onChange={(e)=>setEvidenceLabel(e.target.value)} placeholder="e.g. External ticket reference"/></FormField><FormField label="Safe reference"><TextInput value={evidenceReference} onChange={(e)=>setEvidenceReference(e.target.value)} placeholder="Reference ID or safe external URL"/></FormField></div><Button disabled={!snapshot?.capabilities.manage||busy||!evidenceLabel.trim()||!evidenceReference.trim()} onClick={()=>void run(async()=>{await commandGamingSupportCase({caseId:selected.caseId,action:'add_evidence',kind:'external_reference',label:evidenceLabel.trim(),reference:evidenceReference.trim()});setEvidenceLabel("");setEvidenceReference("");},"Evidence reference added")}>Add reference</Button></Card>
      </div>}
    </Drawer>
  </div>;
}
