import { useState } from "react";
import { AlertTriangle, LifeBuoy } from "lucide-react";
import { Button, Card, DataTable, FormField, Modal, SectionHeader, SelectInput, TextInput, type DataTableColumn } from "../../shared/components";
import { gamingStore, type GamingSupportCase } from "../data/gamingStore";
import { gamingDate } from "../shared/format";
import { GamingStatus } from "../shared/GamingStatus";
import { useGamingStore } from "../shared/useGamingStore";

export function SupportPage(){
 const cases=useGamingStore(gamingStore.getSupportCases); const orders=useGamingStore(gamingStore.getOrders); const customers=useGamingStore(gamingStore.getCustomers); const [open,setOpen]=useState(false); const candidates=orders.filter((o)=>["failed","refund_pending"].includes(o.status)); const [orderId,setOrderId]=useState(candidates[0]?.id??orders[0]?.id??""); const [subject,setSubject]=useState(""); const [detail,setDetail]=useState(""); const [priority,setPriority]=useState<"normal"|"high"|"urgent">("normal");
 const cols:DataTableColumn<GamingSupportCase>[]=[{key:"case",header:"Case",render:(c)=><div className="entity-cell"><strong>{c.number}</strong><small>{gamingDate(c.createdAt)}</small></div>},{key:"subject",header:"Issue",render:(c)=><div className="entity-cell"><strong>{c.subject}</strong><small>{c.detail}</small></div>},{key:"order",header:"Order",render:(c)=><div className="entity-cell"><strong>{orders.find((o)=>o.id===c.orderId)?.number}</strong><small>{customers.find((x)=>x.id===c.customerId)?.name}</small></div>},{key:"priority",header:"Priority",render:(c)=><GamingStatus value={c.priority}/>},{key:"status",header:"Status",render:(c)=><GamingStatus value={c.status}/>},{key:"action",header:"",width:"150px",render:(c)=><div className="table-actions">{c.status==="open"&&<Button variant="primary" onClick={()=>gamingStore.updateSupportCase(c.id,{status:"in_progress"})}>Start</Button>}{c.status==="in_progress"&&<Button variant="primary" onClick={()=>gamingStore.updateSupportCase(c.id,{status:"resolved"})}>Resolve</Button>}{c.status==="resolved"&&<Button onClick={()=>gamingStore.updateSupportCase(c.id,{status:"closed"})}>Close</Button>}</div>}];
 const create=()=>{const order=orders.find((o)=>o.id===orderId);if(!order||!subject)return;gamingStore.addSupportCase({orderId:order.id,customerId:order.customerId,subject,detail,priority,status:"open"});setOpen(false);setSubject("");setDetail("");};
 return <div className="page"><SectionHeader eyebrow="Gaming Store" title="Support & Exceptions" description="Keep support focused on failed, stuck and refund-related orders with direct access to the associated transaction."/><Card><div className="operation-section__head"><div><span>Exception queue</span><h3>Gaming support cases</h3></div><Button variant="primary" onClick={()=>setOpen(true)}><LifeBuoy size={14}/> New case</Button></div>{cases.length===0&&<div className="empty-state-inline"><AlertTriangle size={18}/> No support cases.</div>}<DataTable rows={cases} columns={cols} getKey={(c)=>c.id}/></Card><Modal open={open} onClose={()=>setOpen(false)} title="Create support case"><div className="form-grid"><FormField label="Order"><SelectInput value={orderId} onChange={(e)=>setOrderId(e.target.value)}>{orders.map((o)=><option key={o.id} value={o.id}>{o.number} · {o.status}</option>)}</SelectInput></FormField><FormField label="Priority"><SelectInput value={priority} onChange={(e)=>setPriority(e.target.value as typeof priority)}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></SelectInput></FormField><FormField label="Subject"><TextInput value={subject} onChange={(e)=>setSubject(e.target.value)}/></FormField><FormField label="Detail"><TextInput value={detail} onChange={(e)=>setDetail(e.target.value)}/></FormField></div><div className="modal-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="primary" onClick={create}>Create case</Button></div></Modal></div>;
}
