import { useMemo, useState } from "react";
import { Link2, PackageSearch } from "lucide-react";
import { Button, Card, DataTable, FormField, MetricCard, Modal, PageToolbar, SectionHeader, TextInput, Toggle, type DataTableColumn } from "../../shared/components";
import { gamingStore, type GamingProduct, type SupplierProduct } from "../data/gamingStore";
import { gamingLkr, gamingMoney } from "../shared/format";
import { GamingStatus } from "../shared/GamingStatus";
import { useGamingStore } from "../shared/useGamingStore";

export function ProductsPage(){
 const products=useGamingStore(gamingStore.getProducts); const sources=useGamingStore(gamingStore.getSupplierProducts); const suppliers=useGamingStore(gamingStore.getSuppliers); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<GamingProduct|undefined>(); const [price,setPrice]=useState("");
 const rows=useMemo(()=>products.filter((p)=>`${p.name} ${p.game} ${p.storefrontLabel}`.toLowerCase().includes(query.toLowerCase())),[products,query]); const unmapped=sources.filter((s)=>!products.some((p)=>p.supplierProductId===s.id));
 const columns:DataTableColumn<GamingProduct>[]=[
  {key:"product",header:"NEXT F product",render:(p)=><div className="entity-cell"><strong>{p.storefrontLabel}</strong><small>{p.game} · {p.requiredFields.join(" + ")}</small></div>},
  {key:"supplier",header:"Supplier offer",render:(p)=>{const s=sources.find((x)=>x.id===p.supplierProductId);return <div className="entity-cell"><strong>{suppliers.find((x)=>x.id===p.supplierId)?.name}</strong><small>{s?.externalId} · {s&&gamingMoney(s.cost,s.currency)}</small></div>}},
  {key:"price",header:"Selling price",render:(p)=><div className="entity-cell"><strong>{gamingLkr(p.sellingPrice)}</strong><small>Suggested {gamingLkr(p.suggestedPrice)}</small></div>},
  {key:"availability",header:"Availability",render:(p)=><GamingStatus value={p.availability}/>},
  {key:"enabled",header:"Storefront",render:(p)=><Toggle checked={p.enabled} onChange={(enabled)=>gamingStore.updateProduct(p.id,{enabled})}/>},
  {key:"action",header:"",render:(p)=><Button onClick={()=>{setSelected(p);setPrice(String(p.sellingPrice));}}>Edit</Button>},
 ];
 const sourceCols:DataTableColumn<SupplierProduct>[]=[{key:"offer",header:"Unmapped supplier offer",render:(s)=><div className="entity-cell"><strong>{s.game} {s.title}</strong><small>{s.externalId} · {s.region}</small></div>},{key:"cost",header:"Cost",render:(s)=><strong>{gamingMoney(s.cost,s.currency)}</strong>},{key:"status",header:"Status",render:(s)=><GamingStatus value={s.available?"available":"unavailable"}/>},{key:"action",header:"",render:(s)=><Button variant="primary" onClick={()=>gamingStore.mapSupplierProduct(s.id)}><Link2 size={14}/> Map</Button>}];
 return <div className="page"><SectionHeader eyebrow="Gaming Store" title="Products & Mapping" description="NEXT F storefront products are controlled separately from supplier offers, but retain a traceable supplier mapping."/><div className="compact-metrics"><MetricCard label="Mapped products" value={String(products.length)} detail="NEXT F catalog" icon={PackageSearch}/><MetricCard label="Sellable" value={String(products.filter((p)=>p.enabled&&p.availability==="available").length)} detail="Enabled + available" icon={PackageSearch}/><MetricCard label="Unmapped offers" value={String(unmapped.length)} detail="Supplier catalog" icon={Link2}/></div><Card className="operation-section"><PageToolbar query={query} onQueryChange={setQuery} placeholder="Search products…"/><DataTable rows={rows} columns={columns} getKey={(p)=>p.id}/></Card><Card><div className="operation-section__head"><div><span>Supplier catalog</span><h3>Unmapped offers</h3></div><Link2 size={18}/></div><DataTable rows={unmapped} columns={sourceCols} getKey={(s)=>s.id} empty="Every current supplier offer is mapped."/></Card><Modal open={!!selected} onClose={()=>setSelected(undefined)} title="Edit storefront product" description={selected?.name}><div className="form-grid"><FormField label="Storefront label"><TextInput value={selected?.storefrontLabel??""} onChange={(e)=>selected&&setSelected({...selected,storefrontLabel:e.target.value})}/></FormField><FormField label="Selling price (LKR)"><TextInput type="number" value={price} onChange={(e)=>setPrice(e.target.value)}/></FormField></div><div className="modal-actions"><Button onClick={()=>setSelected(undefined)}>Cancel</Button><Button variant="primary" onClick={()=>{if(selected){gamingStore.updateProduct(selected.id,{storefrontLabel:selected.storefrontLabel,sellingPrice:Number(price)||selected.sellingPrice});setSelected(undefined);}}}>Save</Button></div></Modal></div>;
}
